### DISCUSSION TITLE
How to fail if `stderr` is non-empty during `prepare`?

### DISCUSSION THREAD

**Discussion by abitrolly** [teemtee/tmt#1364] [Q&A]
```
summary: Basic smoke test for python3-m2crypto
prepare:
  - how: install
    package:
      - python3
      - python3-m2crypto
execute:
    script: python3 -c "import M2Crypto"  
```
This install step fails on Fedora 37, because there is this message on stderr.
```
 Problem: cannot install both python3-3.11.0~b4-1.fc37.x86_64 and python3-3.10.4-1.fc37.x86_64
  - package python3-m2crypto-0.38.0-2.fc35.x86_64 requires python(abi) = 3.10, but none of the providers can be installed
  - cannot install the best candidate for the job
  - conflicting requests
```
Even if `dnf` doesn't report it as an error (https://bugzilla.redhat.com/show_bug.cgi?id=2110223) I still want to fail it.

So how?

**Comment by psss** [comment]
From the bug I see you were able to resolve the problem. So I guess there is nothing to be done on the `tmt` side, right?

**Reply by abitrolly** [reply]
Not exactly. I still want to fail the test if there is this message during install.

**Reply by psss** [reply]
You mean checking the output for a particular string like `- conflicting requests`? Or convincing `dnf` to exit with a non-zero status by using some special option?

**Reply by psss** [reply]
For reference, I just tried the following plan and it works nicely:

```yaml
summary: Basic smoke test for python3-m2crypto
provision:
    how: container
    image: fedora:37
prepare:
  - how: install
    package:
      - python3
      - python3-m2crypto
execute:
    script: python3 -c "import M2Crypto"
```

How do you reproduce the issue?
