### DISCUSSION TITLE
Simplified `prepare:` `install:` syntax

### DISCUSSION THREAD

**Discussion by abitrolly** [teemtee/tmt#1368] [Ideas]
How about simplifying this.
```
prepare:
  - how: install
    package:
      - python3-setuptools
      - python3-m2crypto
```
Into this.
```
prepare:
  install:
    python3-setuptools
    python3-m2crypto
```
