### DISCUSSION TITLE
Multihost Support

### DISCUSSION THREAD

**Discussion by psss** [teemtee/tmt#1702] [Ideas]
This discussion is dedicated for announcing new multihost support topics, issues and pull requests. If you are interested in the area of detailed hardware specification you might want to subscribe to this discussion to get notified about the new stuff available for feedback.

**Comment by kkaarreell** [comment]
I would like to present my use case.
In keylime we are using tests also as setup tasks, e.g. to configure swtpm or kernel parameters ([example](https://github.com/RedHat-SP-Security/keylime-tests/blob/main/plans/upstream-keylime-tests-github-ci.fmf#L14)).
We expect to use similar approach also for multihost tests, i.e. we would be mixing singlehost and multihost tests together within a plan.

To easy things on `tmt` side I think it would help to have separate configs in `discover` for singlehost and multihost tests.
Example:
```
discover:
  - name: Server setup
    where:
      - server
    test:
      - /setup/install_upstream_keylime
  - name: Client setup
    where:
      - client
    test:
      - /setup/configure_tpm_emulator
      - /setup/install_upstream_keylime
  - name: Multihost test
    where:
      - client
      - server
    test:
      - /Multihost/basic-attestation
```
Please note that for "Setup" parts we actually do not need any syncing, however for the "Multihost test" part we need to have `server` and `client` synced. Eventually, if there would be more multihost tests present in a plan we would like to have them synced for each test.
Finally, we assume one test could be listed multiple times in a plan and therefore we need sync mechanism to be able to handle that correctly.

One additional note on syncing. On the mtg there was an example:
```
        discover:
            how: shell
            tests:
              - name: run-the-client-code
                test: client.py
                where: client
              - name: run-the-server-code
                test: server.py
                where: server
```
In this example the need of syncing is not obvious. In fact, such a need should be stated explicitly. I think that the default "sync" behavior could assume that tests with identical names should be synced but that won't apply to `shell` example above. I think one could also "group" items that should be synced.
E.g.
```
        discover:
            how: shell
            tests:
              - name: run-the-client-code
                test: client.py
                where: client
                sync: group1
              - name: run-the-server-code
                test: server.py
                where: server
                sync: group1
```
This idea could be extended further where different "groups" can be defined first and then later referenced by specific tests or steps, overriding a global plan default.

**Comment by sopos** [comment]
Currently I use just the simplest scenario we use in beaker for ages, i.e. 1:1 test sets synchronized as `each`.

However I can easily imagine following semi-multihost setup for _clevis_ testing:
* spin up a SUT for _tang_ server instance
* spin up a SUT for _clevis_ where singlehost tests run against the _tang_ server

The thing is that the _clevis_ tests may start after and only after the _tang_ server is running and responding, i.e. the _clevis_ SUT start needs to be synced to the _tang_ readiness.

Such scenario would be probably done by running the _tang_ setup in the prepare step on one machine and tests in the execute step on the other machine where the execute step of the _tang_ machine would be empty. The syncing would be done on the steps only.

Together with what I proposed in https://github.com/teemtee/tmt/issues/969#issuecomment-1326560445 it could look like:
```yaml
discover:
  - how: fmf
    url: ...
    tests:
      - /setup/some_service
    name: SETUP
  - how: fmf
    url: ...
    filter: tag:!setup
    name: TEST
prepare:
    how: tmt
    what: SETUP
    where: server
execute:
    how: tmt
    what: TEST
    where: client
```
or
```yaml
discover:
  - how: fmf
    url: ...
    tests:
      - /setup/some_service
    name: SETUP
    where: server
  - how: fmf
    url: ...
    filter: tag:!setup
    name: TEST
    where: client
prepare:
    how: tmt
    what: SETUP
execute:
    how: tmt
    what: TEST
```
Depending on where we actually want to decide the tests assignment to the specific SUT.

**Comment by sopos** [comment]
Another multihost approach would be the controller-base or orchestrated. The idea is simple, one SUT would run special tests which would control the others which would just wait for instructions. The setup would be similar to the previous use-case syncing on the steps:

```yaml
discover:
  - how: fmf
    url: ...
    filter: tag:!setup
provision:
  - name: CONTROLLER
    ...
  - name: SUT1
    ...
  - name: SUT2
    ...
execute:
    how: tmt
    where: CONTROLLER
```

Assuming there would be metadata available on the SUTs so the running tests on the CONTROLLER would know hostnames / IPs of the other SUTs.

**Comment by adiosnb** [comment]
The sync specification and implementation discussion can be also found here: https://github.com/teemtee/tmt/issues/1705

**Comment by The-Mule** [comment]
I am wondering - is there some implementation (of the original version of the specification) available for testing?

**Reply by psss** [reply]
Only the very [simple scenario](https://github.com/teemtee/tmt/blob/main/tests/multihost/web/data/plan.fmf) is working. But please note that support for the `where` key under the `execute` step is planned to be dropped in favor of #1606.

**Comment by lukaszachy** [comment]
Controller approach - What is the idea?
I understand it in the high level idea: tmt plan specifies it needs multiple machines, tmt run has machine provisioned and prepared (prepare config assigned by 'where' key) and in execute single machine is controller and decides what should run where.

But I fail to understand how one write it.

Questions:
- Will this support multiple tests within single plan?
- How tests on other machines will be executed? 
- How and who will process the results / logs? Beakerlib needs special processing, in the future there should be additional checks (avc detection).
- Will there be libraries (and which languages) to help writing the controller script?

Possible use case:
Plan for chat application, 2 clients and 1 server. Two tests: 1) client A sends msg to client B, both online. 2) client B sends message  client A while A is offline, later A connects and receives the message. 

Should the above be a plan similar to bellow and tmt will capture just the output of test (/a-to-b) ran on the controller? So the responsibility to log / capture everything will be on this test? In other words: tmt in the execute step will only connect to the controller.

How about test dependencies? Controller will have different set than server/client. Should the burden of installing requires be moved to the prepare script? E.g. /a-to-b on controller needs beakerlib, on server foo-server and on client foo-client.
Where will that information (and how) be stored?
```
discover:
   how: fmf
   tests:
   - /a-to-b
   - /b-to-offline-a
   where: controller
prepare:
  - name: setup on server
    how: ansible
    where: server
  - name: setup on client
    how: ansible
    where: client
provision:
  - role: server
  - role: client
  - role: client
  - role: controller
 execute:
    how: tmt
    sync: start
```

**Reply by sopos** [reply]
Very good questions!
> Questions:
> 
>     * Will this support multiple tests within single plan?
Originally I was thinking of that as a test per plan, but it actually makes sense to make it possible to have more of them in one plan as you sketched up above.
> 
>     * How tests on other machines will be executed?
There would be no tests executed on the other machines. There would be just the _controler-based_ test executed. The rest would be on the test itself. It would be just server with enough data to be able to access and control the other SUTs.
> 
>     * How and who will process the results / logs? 
The logs would be produced by the controller only. If there are some log on the SUTs, the test should gather them on its own.
>       Beakerlib needs special processing, in the future there should be additional checks (avc detection).
This might a real issue. There would not be any place to hook an AVC test if there were not tests on the SUTs. We cannot expected the test owner will be able to cover all the necessary check which normally would run automatically by the framework.
> 
>     * Will there be libraries (and which languages) to help writing the controller script?
Definitely it is a place to use libraries like https://github.com/beakerlib/ControlFlow/tree/master/SessionControl in case of beakerlib tests. Beakerlib might not be the best thing to use for such type of tests, thought.
> 

>  How about test dependencies? Controller will have different set than server/client. 
This is also an issue as the tests would be planned to controlled only. There might be some additional L1 metadata for this purpose
```yaml
test_type: controller
require:
    controller:
      - beakerlib
    server:
      - apache
    client:
      - wget
```
That would, of course, mean that the L1 and L2 metadata must meach.

**Comment by kkaarreell** [comment]
I would like to follow up a bit on a topic discussed on yesterday's mtg, I mean the question of parallelism of discover configs.
Starting with Lukas's example above, how should we understand it?
```
discover:
   how: fmf
   tests:
   - /a-to-b
   - /b-to-offline-a
   where: controller
...
 execute:
    how: tmt
    sync: start
```
Discover says that those two tests should be run on controller. What does that mean for server and clients? Is there an assumption that these systems are blocked until tests running on controller are finished? Clearly we do not want to dispose those systems while tests are running but from where in multihost design is this behavior comes from?

It becomes even more unclear when multiple configs are present in a discover step (to simplify it I am using the other syntax with sync in the dicover step)
```
discover
  - name 1on1 peer tests
    how: fmf
    tests:
      - /test1
      - /test2
    where:
      - server
      - client
    sync: name
 - name controller tests
   how: fmf
   tests:
    - /test-A
    - /test-B
    where: controller
  sync: start
```
What a user would like to get is to have server and client systems synced at the beginning of each test from "peer tests" set and then sync ALL systems synced at the beginning of "controller tests" and last until the very end.

However, one could also understand this syntax differently. It could mean that "peer tests" are run just on client and server and since controller is not required here it can proceed with the other config and run "controller tests". This would clearly lead to undesired behavior. So the crucial question here is: Does `where` apply both to where tests are run and what systems are synced or are all provisioned systems always synced? In the example above we want/assume the 2nd to be true.

Just to present a use case for the 1st behavior (without controller role):
```
discover
  - name: server setup
    how: fmf
    tests:
      - /server/setup
    where:
      - server
 - name: client setup
   how: fmf
   tests:
    - /client/setup
    where: client
  - name: the actual test
    how: fmf
    tests:
      - /test1
    where:
      - server
      - client
    sync: start
```
Here we benefit from server and client configs being run in parallel.
And just to present it a bit differently:
```
discover
  - name: common setup and sync
    how: fmf
    tests:
      - /common/setup
    where:
      - server
      - client
    sync: finish   (not sure this is defined somewhere but I want here them to be synced when the test/setup ends)
  - name: server part of tested scenario
    how: fmf
    tests:
      - /server/part
    where:
      - server
 - name: client part of tested scenario
   how: fmf
   tests:
    - /client/part1
    - /client/part2
    - /client/part3
    where: client
  - name: log collection
    how: fmf
    tests:
      - /log/collection
    where:
      - server
      - client
    sync: start

```
which utilize the parallelism and also the fact that server and client tests may have different names. This could in fact become handy, e.g. when server part is doing some generic setup while clients when be performing different tasks against this setup. I could also add more discover configs changing the setup on the server and then running again various client tasks. This would allow me to test multiple scenarios in a single test plan. 

I think that this behavior is even more important when `how: shell` is used instead.

Above I tried to present on examples why I believe it is crucial to define the expected behavior for the `where` step and discover with multiple configs, each possibly requesting different `sync`.  I am not saying we should support every use case presented above, I am just trying to present that the actual behavior would influence the actual test case and test plan design.

And just to make it even more complicated. `tmt` could export the actual system role in a context and therefore `discover` could return different test set for client or server role even in the same discover config..  In fact, this could happen even without that assuming client and server have different system configuration and test relevancy takes system configuration into account. The point is that users knowing that could utilize it for generating different server and client test sets on purpose, within a single discover.

**Reply by sopos** [reply]
At the end the the mtg we actually hit the crucial question - are we gonna solve the _in step_ syncing (task/test syncing) or just the _step_ syncing? There are two separate things where the former one is much more complicated and may bring more confusion.

It was considered as a food for thoughts for the Xmas period.

May be we should focus on the simple scenarios, i.e. `sync: start` for the _step_ sync and possibly `sync: index` for the _in step_ sync which would cover the backwards _wow_-compatible workflow.

Those more complicated setups would be probably preferred to treat as the _controller_ based approach.

**Reply by adiosnb** [reply]
+1 for the `finish` sync value

**Reply by adiosnb** [reply]
What if you add `sync: start` to the second discover config? Can this solve the problem int the last example?

**Reply by adiosnb** [reply]
I added extend example of multihost and sync usage into the [PR#1706](https://github.com/teemtee/tmt/pull/1706/files#diff-5311c1419ec81d9fdb5cbfdb6e595afcac980d90e3e508c34b592595564d386f). Please have a look and any tips, how it can be improved.

**Reply by sopos** [reply]
however, considering it as s dicover "config" stuff is rather the _in step_ kind of sync

**Comment by adiosnb** [comment]
The question from the last meeting discussion. In the example pasted below, which guests should be synchronized in the beggining? All guests or guests specified by `where`? 

```
discover:
 - name: client part of tested scenario
   how: fmf
   tests:
    - /client/part1
    - /client/part2
    - /client/part3
    where: client
    sync: index
    # Question: Which host to sync?

  - name: server part of tested scenario
    how: fmf
    tests:
      - /server/part
    where:
      - server
```

**Comment by adiosnb** [comment]
I have also another question or proposal for the `start` sync method. What if it synchronizes all guests at the beginning of the step? In the case of multiple configs with start, all guests are synced together regardless `where` at the begging of different config parts. What do you think?

**Comment by adiosnb** [comment]
And the last topic for the discussion. What do you think about the implicit synchronization barrier between all step phases? I mean all provision steps for all guests start at once, then all prepare steps start at once, execute, report, etc.

Do you have any preferences about this?

**Reply by sopos** [reply]
This was the _step_ sync we thought about initially, I guess. In particular the `sync: start`. While we kind-of agreed the default would be `sync: none`  I would refuse this implicit syncing.

**Comment by kkaarreell** [comment]
I've spent some time thinking about synchronization yesterday and I think we should consider making things as simple as possible. We didn't really gather much real-life scenarios (it would be nice to have them gathered somewhere - I mean not links to existing tests but rather an outline how the tmt plan would look like in some proposed/abstract syntax) and it therefore seems to me that we may be over-engineering the syntax too much without having a real need for high flexibility.

I will be talking about this example
```
discover
  - name: server setup
    how: fmf
    tests:
      - /server/setup
    where:
      - server
 - name: client setup
   how: fmf
   tests:
    - /client/setup
    where: client
  - name: the actual test
    how: fmf
    tests:
      - /test1
    where:
      - server
      - client
    sync: start
```
My question is: Is there a real need to run subsequent phases (or steps) in parallel? For the example above it means, we we need to be able to run server setup and client setup together? I think it will make the implementation more complicated and I am not sure this use case is really necessary/justified. We should make things simple in `tmt`, delegating the complexity to tests and their custom sync frameworks.

So my proposal goes a bit against what is mentioned by @sopos above. I would propose that each phase (one named block in discover above) would be synced at the beginning *for all provisioned systems* independently on whether these systems are mentioned in `where` clause - this would be used only to define on which systems the actual command/test should be executed. But all systems will be synced and with the beginning of the next phase all systems with be synced again. I believe it will make implementation way easier. Also, it would reduce a risk that some systems would be asked to run two distinct tests/commands at the same time.
Clearly, we will loose something (running tests/commands on some systems in parallel to running other tests/commands on other systems) but I think it is worth it, at least for the initial implementation.

The above applies to phases, what remains is sync between individual tests. For that I think we could utilize options that have been already proposed (by name, index etc.).

**Reply by happz** [reply]
@kkaarreell to better understand, what would the flow of phases look like? Would this diagram correspond to what you propose?

![tmt phases   ticks, simple sync (5)](https://user-images.githubusercontent.com/116509/210564713-abfeeae6-d011-4357-8f93-4924d5312372.jpg)

**Reply by kkaarreell** [reply]
I believe it does.

**Reply by happz** [reply]
Ok, that's good. I think this would be my idea for the basic "synchronization" proposal on the step- and phase- level - I wouldn't touch *test* synchronization yet. Extended above the `execute` step, steps would run in lockstep as well, moving from `prepare` to `execute` once all guests are done with their `prepare` phases, and so on. With a bit more stuff to highlight the behavior even more:

```yaml
discover
  - name: server setup
    how: fmf
    tests:
      - /server/setup
    where:
      - server

 - name: client setup
   how: fmf
   tests:
    - /client/setup
    where:
      - client1
      - client2

 - name: extra client1 setup
   how: fmf
   tests:
    - /client/setup
    where:
      - client1

  - name: the actual test
    how: fmf
    tests:
      - /test1
    where:
      - server
      - client1
      - client2

  - name: another test
    how: fmf
    tests:
      - /test2
    where:
      - client1
      - client2

  - name: yet another test
    how: fmf
    tests:
      - /test3
    where:
      - client1
```

![tmt phases   ticks, simple sync (7)](https://user-images.githubusercontent.com/116509/210586933-1d14aa95-5231-4a27-a289-82a0c1ac378b.jpg)

* phases moving in lockstep;
* each guest has its own queue of phases;
* all queues are of the same length, the maximal length needed, padded with no-op phases when needed;
* phases are put into queues in the order given by - by what? in the order of their `order` keys? I'd expect them to be sorted by `order`, with some stable sorting algorithm to preserve their order from fmf nodes.

Implementation of such a workflow should be relatively simple, we already do have something similar in BaseOS CI. Guest queues can be prepared easily, processed by a dumb state machine, etc.

Adding support for some kind of tied phases would be also relatively simple to add, as it'd be just a matter of sorting, preserving order, and copying phases to guests according to `where`.

```yaml
discover:
  ...
  - name: shared teardown
    how: fmf
    tests:
      - /test4
    where:
      - server
      - client1
      - client2
    in-sync-with:
      - server
      - client1
      - client2

  - name: client2 teardown
    how: fmf
    tests:
      - /test5
    where:
      - client2
```

![tmt phases   ticks, simple sync (8)](https://user-images.githubusercontent.com/116509/210589963-b3464dd0-2edc-485a-b3bc-46b717ff2911.jpg)

**Reply by sopos** [reply]
These _in step_, _phase_, or _config_ syncs may be a bit tricky in general. What could help here is some kind of "bracketing" to express what can be run in parallel. Another possibility would be to use _order_ where the _configs_ / _phases_ with the same _order_ would be executed in paralel, whle with different would be executed subsequently in the numeric order.
I.e., an addition to the above mentioned metadata:
```yaml
discover:
  - name: server setup
    order: 1
  - name: client setup
    order: 1
  - name: extra client1 setup
    order: 2
  - name: the actual test
    order: 3
  - name: another test
    order: 4
  - name: yet another test
    order: 5
  - name: shared teardown
    order: 6
  - name: client2 teardown
    order: 7
```

**Reply by kkaarreell** [reply]
The point is there won't be any parallel phases. Enabling parallel phases (client and server setup in your example) makes things more complicated (e.g. what if there is a system overlap between two phases?)

**Reply by sopos** [reply]
According to the second picture above there are, at least the server setup and client setups.
Otherwise the first picture, where no parallelism on the _config_ / _phase_ level is allowed, seems fine to me as well.

**Reply by kkaarreell** [reply]
> I wouldn't touch _test_ synchronization yet. 

Exactly. Our primary motivation for test synchronization was compatibility with beaker. But what beaker/restraint does is synchronization of tests with multihost type and such synchronization is be pretty simple to implement. E.g. using semaphores and following implementation in sync library (https://github.com/RedHat-SP-Security/keylime-tests/tree/main/Library/sync) 
for `server, client, storage` being provisioned and having
```
- name: tests
  where: server, client
```
one (`tmt`) needs to schedule this:

1. for each multihost test build unique semaphore name (involving iteration counter for repetitive test executions), e.g. `MULTI_SYNC_1_TEST_FOO_BAR`
2. for server and client do `syncSet MULTI_SYNC_1_TEST_FOO_BAR`
3. for server and client do `syncBlock MULTI_SYNC_1_TEST_FOO_BAR server client` - since we are syncing servers where `tmt` would run a multi-host test

If we wouldn't be willing to build-in such execution into `tmt` directly we could insert explicite sync task prior each multi-host test or at the worst (as a temporary solution) update (migrate) every multihost test to do this kind of sync internally where `tmt` would only help to build that unique semaphore name (similarly to what restraint does with `XTRA` variable).

**Reply by kkaarreell** [reply]
> According to the second picture above there are, at least the server setup and client setups. Otherwise the first picture, where no parallelism on the _config_ / _phase_ level is allowed, seems fine to me as well.

I see. TBH I do not get the second example, I do not understand why `in-sync-with` is there and necessary.

Also, the parallel client and server setup is incorrect, my proposed implementation would separate these two phases.

**Reply by happz** [reply]
Ok, I think we're still seeing something different, and this time it's definitely my fault, my diagrams do not describe what I wanted to convey. So much for clearing a table with a simple-to-understand picture :/ Let me start again.

**Reply by happz** [reply]
> > According to the second picture above there are, at least the server setup and client setups. Otherwise the first picture, where no parallelism on the _config_ / _phase_ level is allowed, seems fine to me as well.
> 
> I see. TBH I do not get the second example, I do not understand why `in-sync-with` is there and necessary.
> 
> Also, the parallel client and server setup is incorrect, my proposed implementation would separate these two phases.

Sorry, that was my mistake. I misunderstood & draw something that did not match my understanding anyway. I'm trying to start from scratch, I must admit I'm struggling to keep up with all the ideas around, and I'm trying to look for some concrete, materialized "common ground" I could grasp, understand and build upon. Again, sorry for the confusion. https://github.com/teemtee/tmt/discussions/1702#discussioncomment-4594240

**Comment by happz** [comment]
My take. I'd like to focus on some basics, multiple guests, and multiple phases to be run on each guest, with some parallelization.

Let's start with the following tmt configs, nothing fancy:

```yaml
discover
  - name: server setup
    how: fmf
    tests:
      - /server/setup
    where:
      - server

 - name: client setup
   how: fmf
   tests:
      - /client/setup
    where:
      - client1
      - client2

  - name: the actual test
    how: fmf
    tests:
      - /test1
      - /test2
      - /test3
    where:
      - server
      - client1
      - client2

  - name: another test
    how: fmf
    tests:
      - /test4
      - /test5
    where:
      - client1
      - client2

  - name: yet another test
    how: fmf
    tests:
      - /test6
    where:
      - client1
```

![tmt phases   ticks, simple sync (9)](https://user-images.githubusercontent.com/116509/210610427-95bd63dd-41f8-47f4-b54e-e2ee224d38e1.jpg)

I see the parallel aspect as being crucial and unavoidable. tmt can perform each guest queue after another, in a true sequential manner, but then I see much harder support for the server/client test scenarios: `the actual test` @ `client2` might run **hours** after `the actual test` @ `server` (if phases run one by one, let's say from the left to right, from top to bottom). But:

* for runs where synchronization is not needed - e.g. testing a Koji build on multiple architectures -, tmt would finish sooner, no harm done.
* for runs with server/client tests, it would be much more easier for whatever user synchronization library `the actual test` might be using to synchronize its tests if `the actual test` phase would start at the same time, more or less, on `server` and both clients.

This seems to me like the very basic prototype we could land.

* No complicated implementation. If there are more phases to be run on the same guest, they would be run in sequence, just like today, just waiting for their counterpart in the same position in other queues. Provision guests, establish a queue for each of them, process `discover` phases, and distribute them into correct queues (a phase might be copied into several queues if needed).
* If the synchronization between phases is not needed, we're good.
* If the synchronization between phases is needed, split queues into parallel slots by barriers where different tmt threads of testing would wait for queues to reach before starting another phase.
* The order of phases and their distribution into queues is given by `order` and the order of phases in source fmf nodes.
* Both types of barriers are optional: both `steps` and `phases` lockstep can be enabled or disabled, whatever is the default. For the first example, none of them is needed, for the server/client, both might be necessary to guarantee a stable environment for the test-level synchronization.

My point was, AFAICT, this would be the very basic prototype supporting both trivial scenarios, "run plan on multiple hosts" and the very basic "run tests on server and client". User libraries can take care of synchronizing individual tests as needed, tmt would guarantee phases would begin at the same time & can export necessary variables, to describe the topology.

On top of this, we should be able to build more features. The bracketing @sopos suggested I accidentally illustrated in my previous diagrams. Or any other custom synchronization or parallelization modes, the core implementation would exist and *would be already testable for the basic use cases*.

Now, I'm adding yet another idea on top of the pile of ideas here, but I'd like to ask you to bear with me. I tried to add a diagram to illustrate the workflow, and I'd like to discuss various use cases or ideas & try to amend them with this proposal. If you something that's an obvious blocker, please, point it out.

**Reply by sopos** [reply]
All but the first set makes sense to me. Where _tmt_ gets the information to run the server and client setups in parallel?

**Reply by happz** [reply]
@sopos by the mere fact both server and client setup phases are the first two phases discovered, and the do not overlap when it comes to guests. The server setup is placed in server queue first, then client setup is placed in both cluent queues, and becase there were no other phases put into client queues before, it makes them sitting in the first positions of all three queues.

No magic, just take phases one by one and stack them into correct queues. Minimal example & basic functionality.

I believe the explicit synchronization - run this phase with that phase - can be added, sure, absolutely. It would be just a matter of shaping those queues, the machine crunching phases wouldn’t care. But until we agree on how, why, when, we can maybe agree on & build an MVP which doesn’t close any door to advanced features.

**Comment by kkaarreell** [comment]
The problem I see with such parallelism is that it is in fact more tricky than it seems. At first we need to implement some logic that would be deciding which phases on which systems can be run or which systems can wait. E.g.
```
discover:
 - name: /phase/1
    where: server, client1
 - name: /phase/2
   where: server, client2
 - name: /phase/3
   where: client1, client2
```
What should be the rigth sequence?
 1. /phase/1 on server and client1
 2. /phase/2 on server and client2
 3. /phase/3 on client1 and client2

 or

 1. /phase/1 on server and client1 + /phase/2 on client2
 2. /phase/2 on server + /phase/3 on client1 and client2

I know you will say the first one but the problem is that it is not obvious at the first sight, especially if there would be more systems involved.

The other problem is that the question which systems should run a test script (`where`)  is not the same as the question which systems should be synced and involved in test scenario. E.g.
```
discover:
 - name: ssh to client2 and create something
   where: server
 - name: ssh to client2 and destroy something
   where: client1
```
presents this discrepancy quite well I guess. Do we want to run both actions in parallel (race condition present) or one phase after the other? 
From these reasons I believe that avoiding parallelism is justified, at least for the initial implementation. It should be easier to improve it later with more features than to implement those features properly from scratch.
```

**Reply by happz** [reply]
> The problem I see with such parallelism is that it is in fact more tricky than it seems. At first we need to implement some logic that would be deciding which phases on which systems can be run or which systems can wait. E.g.
> 
> ```
> discover:
>  - name: /phase/1
>     where: server, client1
>  - name: /phase/2
>    where: server, client2
>  - name: /phase/3
>    where: client1, client2
> ```
> 
> What should be the rigth sequence?
> 
> 1. /phase/1 on server and client1
> 2. /phase/2 on server and client2
> 3. /phase/3 on client1 and client2
> 
> or
> 
> 1. /phase/1 on server and client1 + /phase/2 on client2
> 2. /phase/2 on server + /phase/3 on client1 and client2

The logic already exists: obey the user. The user expressed themselves already, and it's in the configuration: take one phase after another and perform them. `/phase/1` on `server` and `client1`, plus `/phase/2` on `client2`, because `server` is occupied. When done, move to the next.

If this is *not* what the user wanted, then we need to give him the tools to better express their needs, explicitly. For example:

```yaml
discover:
  - name: /phase/1
    where: server, client1
  - name: /phase/2
    where: server, client2
  - name: /phase/3
    where: client1, client2
    in-sync-with: client1, client2
```

I took the liberty to add a new field, `in-sync-with`, to allow user to let tmt know it's their wish to run `/phase/3` at the same time on `client1` and `client2`. Given the order of phases, this will wait after `/phase/2` finishes on `client2`, simulating your first suggested workflow. While `server` and `client2` crunch `/phase/2`, `client1` just sits and waits.

> 
> The other problem is that the question which systems should run a test script (`where`) is not the same as the question which systems should be synced and involved in test scenario. E.g.
> 
> ```
> discover:
>  - name: ssh client2 'touch something'
>    where: server
>  - name: ssh client2 'destroy something'
>    where: client1
> ```
> 
> presents this discrepancy quite well I guess. Do we want to run both actions in parallel (race condition present) or one phase after the other? From these reasons I believe that avoiding parallelism is justified, at least for the initial implementation.

Again, the default is to obey the user: one phase for `server`, one for `client1`. If they are *not* supposed to run at the same slot of guests' queues, the user must say so:

```yaml
discover:
 - name: ssh client2 'touch something'
   where: server
 - name: ssh client2 'destroy something'
   where: client1
   after: ssh client2 'touch something' @ server
```

Again, new directive. Wrap it with `sync`, or not, not important, `again` just expresses what I wanted to achieve: the user tells this phase runs after that phase.

I'm afraid we're trying to teach tmt to guess a lot, and we're trying to make it all happen at once, all features supported and specified, and it makes things harder and harder and messier and messier. At the core, it's a simple matter of queues, items in those queues, and points where tmt should wait for something. I just wanted to propose a basic MVP which would add those queues, very simple schema to fill them with phases, and very basic set of places where tmt would wait and for what. That we could prototype, and, when the dust settles, the state machine and queues will be there no matter what we agree on for `sync` to be like. tmt already has logic and rules for performing phases, runs them in sequence as they come from fmf files - I'd say that's good enough. At least it's good enough for current single-host scenarios. For cases where it's *not* good enough, yeah, for those we definitely need `sync` or something like that, but until we agree on what it should behave like, I wanted to propose https://github.com/teemtee/tmt/discussions/1702#discussioncomment-4594240 as something we might start with, as long as it wouldn't make anyone angry, break their existing workflow or close door to future enhancements.

The two scenarios you described here are definitely compatible with what I proposed as a starting point, and the functionality can be added once fully specified. I'm sure of that.
