### DISCUSSION TITLE
Override test attributes from plan

### DISCUSSION THREAD

**Discussion by lukaszachy** [teemtee/tmt#2430] [Ideas]
Use case is #1843 but while at it we can extend it for require/recommend as well - so, why not to make it generic enough? 
Or isn't it worth the trouble? (I see the use case for renamed packages (e.g. dual package or collections)

How about this syntax (PLAN)?
```
discover:
  how: fmf
  url: http://example.com/foo.git
  set:
    duration: '*2'
    require+: [ 'foo']
    require-: ['bar']
    recommend: []
  edit:
    - key: require
      pattern: 'foo'
      replace: 'foo-ng'  
```

I'm not good at UX but the my goal will be to allow :
- extend attibute (+) or set if not exists
-  remove attribute value (-), no operation if not there
- set new attribute values
- run re.sub on all values of selected attribute
- in the case of duration be able to 'multiply' current value

**Comment by psss** [comment]
The overall idea sounds reasonable and useful. Furthermore, another related use cases are coming (e.g. enable the `avc` check for all tests). Regarding implementation, a quick brainstorm question: Would it make sense to use the `adjust` syntax here as well?

```yaml
discover:
  how: fmf
  url: http://example.com/foo.git
  adjust:
    - duration+: 1h
    - require+: ['foo']
      when: distro == rhel-9
```

The `when` condition is optional so if no context limitations are to be applied the syntax could look quite concise and consistent with what users already know. Plus the implementation would be quite simple, probably just one additional `adjust()` call.

**Reply by LecrisUT** [reply]
+1 for this UX, would also addreas #2340 if it was made generic, i.e. `adjust()` for altering the imported plan, `plans.prepare`, etc. to run in the context of the calling plan

**Reply by happz** [reply]
Looks good, using `adjust` concept makes sense. But, I would propose using a different keyword instead of `adjust`, because `adjust` has an effect of modifying the object that contains it, while in this case, the discovered tests would be modified. Maybe something like `adjust-tests` & "it's the `adjust` you know and love, but applies to tests discovered by the phase."

```yaml
discover:
  how: fmf
  adjust-tests:
    check+:
      - name: avc
```

Yeah, that should work :)

**Reply by LecrisUT** [reply]
Oh indeed, it would be confusing if it refers to `adjust` plan or `adjust` test, especially since there would only be 2 spaces distinguishing them

**Comment by jchecahi** [comment]
This feature would be highly valuable for a use case we're trying to implement: reusing LLVM tests in the compat packages. LLVM compat packages are named with a version suffix, similar to `python3.x` packages. In order to reuse a test, we must be able to modify a test's `require` list so instead of requesting `clang`, `clang-libs` etc, it requests `clang17`, `clang17-libs`, etc.

Implementing this without the feature proposed here would be a challenge. We'd need to either duplicate all the code using a branched scheme (one branch per compat package version) and replace all the ocurrences of `clang` with `clangXX` (XX = llvm version), or introduce a series of `adjust:` conditions based on context variables(?) that would difficult the maintainability. LLVM is comprised of 7 components so either option would need to be implemented in each repo.

The approach proposed here aligns perfectly with the use case, and would easily allow us to reuse them without actual changes in the tests:
```
discover:
  how: fmf
  url: https://src.fedoraproject.org/tests/clang.git
  edit:
    - key: require
      pattern: 'clang'
      replace: 'clang17'
    - key: require
      pattern: 'llvm'
      replace: 'llvm17'
    # And so on with the rest of LLVM components...
```

**Comment by lukaszachy** [comment]
Since we go with 'adjust' syntax I'd like to ask for help with deciding  the way how adjust can edit values. From the implementation PoV I'd say `re.sub` with check that  if the final string is empty the value will be removed from the list.

Motivation for the 'drop if empty' is that if test has `require: [make, patch, python3-test, python3-foo ...]` it is easier to drop all `python3-*` require using regexp than enumeration all to the `require-:[...`

Problem is how to write that in `adjust` syntax. I'm thinking of another merge operator, probably `~` suffix. 
However - should the pattern/repl strings be in single string (similar to sed-like "s/regexp/replacement/") OR it will be better to have explicit pattern/replace keys processed during the adjust?

Lets' say that the discovered test has `require: [ foo, bar]`. UC is to change 'foo' to 'foo2-ng' and drop 'bar'

The 'sed-like' could be - Downside in escaping '/' (or allowing custom char to separate?)
```
discover:
  how: fmf
  adjust-tests:
  - require~:
     - "foo/foo2-ng"
     - "bar/"
```

The explicit way  - too chatty, isn't it?
```
discover:
  how: fmf
 adjust-tests:
   - require~:
     - pattern: foo
       replace: foo2-ng
     - pattern: bar
       replace: ""
```

Edit: This merge operator will land in fmf package, but this discussion has already the audience and necessary background.

**Reply by happz** [reply]
`sed`-like approach doesn't sound bad at all. Would backreferences be supported? Might be handy:

```yaml
require:
  ...
  - libjpg-ng
  - zlib-ng

...

adjust-tests:
  - when: distro == rhel-10
    require~:
      # yeah, these are for RHEL-10 only, older RHEL ships similar ones, just drop the suffix.
      - "(libjpg|zlib)-ng/\\1"
```

Also, making the syntax more aligned with `sed` by accepting leading and trailing slashes too might make it clearer for users: `/(libjpg|zlib)-ng/\\1/`

**Reply by LecrisUT** [reply]
What about:
- `-~` -> `-` operator and regex matching `~`. Delete any that match the regex. (Similar to the `+<` operator that prepends)
- `~` -> regex find-and-replace using groups

`sed`-like syntax would be interesting, but supporting both formats (`sed` and `pattern`/`replace`) might be confusing, especially since in `-~` there is no replace. Probably better to support only one

**Reply by lukaszachy** [reply]
Thanks, Personally I like 'sed-like' more but I'm afraid of documenting and explaining that it is just 'search' part of sed and regexp is the python one, not the sed (perl?) one. Backreferences should be supported. If going this way I'd would split "/regexp/replacement/" into parts and just call `require = [re.sub(regexp, replacement, val) for val in require]`. AFAIK backreferences are supported by re.sub.

Hm, `-~` as dedicated 'delete' operation seems interesting, what would be the effect of `~` leading to empty str? eg. `/.*//` Warning? I'm not sure require/recommend will be happy with empty values

**Reply by lukaszachy** [reply]
Btw I prefer the leading char in sed-like too - more used to it after seeing it daily :D

**Reply by LecrisUT** [reply]
> what would be the effect of `~` leading to empty str? eg. `/.*//` Warning? 

Maybe the user will have use-cases for setting a list with empty values. Maybe in a plugin. I have found myself wondering what to do with `test` variable for `tmt-copr`, where the actual framework test script is defined by the framework, but `test` must be populated (even to an empty string) in order to go around the `__init__` check.

**Reply by jchecahi** [reply]
I do like the sed-like format, however from user perspective might be confusing because it's not really sed syntax, but python regex. On the other hand, the `pattern` and `replacement` format seems like more readable and should support backreferences as long as the strings follow the format as documented in (re.sub docs)[https://docs.python.org/3/library/re.html#re.sub]. It's not clear to me if  the `~` operator rules out the `+` and `-` operators. The merge operator would be able to handle deletions, but not additions.

Also, I'm not sure if it's relevant at this point of the discussion, but another thing to consider is the order in which the edits are done. In this example, the added dependency might be modified by the subsequent merge operation:
```
adjust-tests:
  - require+:
    - foo-ng
  - require~:
    - 's/(foo|bar)/\1-suffix/'
```
Which would result in foo-suffixbar being added.

**Reply by LecrisUT** [reply]
> It's not clear to me if the ~ operator rules out the + and - operators.

Good question, especially the order part. We can already use multiple operations, e.g.:
```yaml
my_var:
  - one
  - two

/overwrite:
  my_var-: [ two, three ]
  my_var+: [ three, four ]
```
But if you run `fmf show` on that it will give you `my_var: one and four`, probably because the yaml is sorted before operations are processed. I've made an issue about it: https://github.com/teemtee/fmf/issues/232

**Reply by lukaszachy** [reply]
fmf does sort keys, so operatos are processed in `['+', '+<', '-', '-~', '~']` order

**Reply by jchecahi** [reply]
Hmm if the `+` is processed before `~` it means that the use case I mention in my last comment would not work, right? Unless the edit is done only to the elements that were present *before* `adjust-tests`, right?

**Reply by LecrisUT** [reply]
That should depend on what is viewed as expected results, I can see it going both ways. Normally using `adjust.when: true` should take care of overwriting the order you desire, but having `adjust` nested in `adjust-tests` (btw, isn't the syntax going to be plain `adjust`?) feels odd, yet intuitive :shrug:.

**Reply by lukaszachy** [reply]
I'm not sure about just 'adjust'  -- see https://github.com/teemtee/tmt/discussions/2430#discussioncomment-7870532

IMO it will be confusing that 'adjust' of the plan contains PLAN keys but 'adjust' in the discover should contain just TEST keys
Having 'adjust-tests' is IMO more descriptive.

```
$ cat plan.fmf
adjust:
- prepare+:
  how: install ....
/execute:
  how: tmt
/discover:
  how: fmf
  adjust:
  - require~:
    - "/foo/bar/"
```

**Reply by lukaszachy** [reply]
As for the order of what will happen with TEST tree metadata:
1. load Tree  - apply fmf format features
2. apply context (from tmt -c CONTEXT) followed by these 'adjust-tests' rules

**Reply by LecrisUT** [reply]
> I'm not sure about just 'adjust' -- see https://github.com/teemtee/tmt/discussions/2430#discussioncomment-7870532

Don't remember in which issue comment (not in this discussion thread) it was, but I remember being some mention of `adjust` vs `adjust-something-else`. Within the last week or two? Don't remember the context of it unfortunately.

> As for the order of what will happen with TEST tree metadata:

We have multiple orders that could be confusing:
- Natural order of operators `['+', '+<', '-', '-~', '~']`
- Order of `fmf` parsing w.r.t. `adjust` and inheritance
- Order of `adjust-tests`

One super confusing scenario would be if something like this was encountered:
```yaml
/root/my_plan:
  discover+:
    adjust-tests+:
      ...
```

**Reply by lukaszachy** [reply]
> One super confusing scenario would be if something like this was encountered:

Exactly. I can't find the issue now, maybe we just chat about it - but it would be nice to have tmt command to explain what is being done to the metadata.

Well, good luck to documenting how this 'adjust' on test metadata work.

**Reply by lukaszachy** [reply]
Maybe some plan with `adjust` and `adjust-tests` used on all possible places and do the break-down of what is the test metadata in which processing part?

**Reply by LecrisUT** [reply]
Oh, I just realized, don't we have a cleaner approach with [`graft`](https://github.com/teemtee/fmf/issues/99#issuecomment-2058971411) operations? For discover we just need to specify the tree path to graft on top or below it. Then the `adjust` are specific to `context` adjusts and always require `when`

**Reply by lukaszachy** [reply]
Grafting as adjust-test? I don't think so - number of nodes stays the same. IMO the 'edit' is more suitable name, but that is something we can change.

**Reply by LecrisUT** [reply]
I think it would offer more flexibility:
- Edit the base of all tests (`reverse-graft`): have a `root.fmf` tree and graft the `discover` tree on top of that
  - If only the root is populated, no new leaves are produced
- Edit specific tests (`forward-graft`): after the `discover` tree is produced, graft `my_test.fmf` on top of that
  - If names are for leaf tests, than you can overwrite any variable defined by discover. (Similar to having a `/root/my_test` defined in a top-level `main.fmf` and then adding a `/root/my_test/main.fmf` file on top of that)

And these can be mixed together. Ignoring my bad naming intuition a UX would be:
```yaml
execute:
  how: tmt
discover:
  how: fmf
  url: https://src.fedoraproject.org/tests/clang.git
  graft-on: /path/to/base/tree
  graft-from: /path/to/leaf/tree
```
Where `/path/to/base/tree` could have a `main.fmf` as
```yaml
environment:
  PACKAGE_TO_TEST: my_package
```
And `/path/to/leaf/tree` could have:
```yaml
/root/specific_test:
  result: xfail
```

This format can be better for the user because:
- User can make arbitrary tree structures (new `.fmf/version`) to fit their need
- Effect of `adjust` is well-defined within the file
