### DISCUSSION TITLE
link type as a list?

### DISCUSSION THREAD

**Discussion by sopos** [teemtee/tmt#922] [Q&A] [answered]
https://github.com/psss/tmt/blob/dad121eb19dd4312e3044e9b5de689a0574b3ce5/spec/core/link.fmf#L93
can I write
```yaml
    link:
      - verifies: /stories/cli/init/base
      - verifies: https://bugzilla.redhat.com/show_bug.cgi?id=1234
```
this way:
```yaml
    link:
      verifies:
      - /stories/cli/init/base
      - https://bugzilla.redhat.com/show_bug.cgi?id=1234
```
Logically, it perfectly makes sense.
