### ISSUE TITLE
(F35) TMT hangs when there are left processes running

### ISSUE THREAD

**Issue by pvalena** [teemtee/tmt#1007]
On F35 (might be fixed since), I need to kill all processes that I've run in background, otherwise the tasks is left hanging indefinitely (duration does not help!).

In both `prepare` and `execute`.

Example:
```
prepare:
  - name: tbd
     script: |
         nohup sleep indefinitely &
         disown
  - name: does not start
     script:  echo never
```
(Example not tested, sorry.)

**Comment by psss** [comment]
Tried with the following plan

```yaml
prepare:
  - name: tbd
    script: nohup sleep 10 & disown
  - name: does not start
    script:  echo never
execute:
    script: /bin/true
```

Works fine with `container` provision, gets stuck with `local` and `virtual`.
