### ISSUE TITLE
convert attribute's sub-tree to a list

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#1041]
Convert
```yaml
provision:
  image: fedora-rawhide
  /node+:
    how: virtual
    name: node
    image: fedora-35
  /server+:
    how: virtual
    name: server
```
into
```yaml
provision:
  - how: virtual
    name: node
    image: fedora-35
  - how: virtual
    name: server
    image: fedora-rawhide
```
This will allow standard logic of fmf inheritance to be applied to attributes expansion. It could be probable also deeper structure where the leafs would basically define the list item content.
There is still a question how to know if an attribute should be processed this way. It might be based on presence of a key starting with `/` or there may be some explicit "switch".

This would allow overriding the _image_ from the command line for the _server_ but not for the _node_ as discussed in https://github.com/psss/tmt/issues/68#issuecomment-1027235587
