### ISSUE TITLE
A plan installs deps from all the tests

### ISSUE THREAD

**Issue by TomasTomecek** [teemtee/tmt#1067]
http://artifacts.dev.testing-farm.io/c089aa49-7fb6-4c72-acca-c19c3af59f00/
http://artifacts.dev.testing-farm.io/49368cf2-f543-4163-a3ca-d72b8928376a/

the rpmlint plan is failing above, this is the plan
```
summary:
￼  Execute rpmlint on the spec file
￼prepare:
￼  - name: packages
￼    how: install
￼    package:
￼    - rpmlint
￼execute:
￼  script:
￼  - rpmlint packit.spec
```

we have a few tests with `require`: it seems the plan inherits all of those requirements which is incorrect for us

if I want to run rpmlint on a spec in our upstream repo, what is the best way to do it? plan or a test?

**Comment by psss** [comment]
Looking at the plan I see the local test `discover` using `fmf` is enabled:

```
> tmt plan show rpmlint
/plans/rpmlint
     summary Execute rpmlint on the spec file
    discover 
         how fmf
     prepare 
        name packages
         how install
     package rpmlint
     exclude 
     missing fail
     execute 
         how tmt
      script rpmlint packit.spec
     enabled true
```

This is because it's inherited from `main.fmf`:

```yaml
execute:
    how: tmt
discover:
    how: fmf
```

The solution is to use `discover --how shell`, the config can look like this:

```yaml
summary:
    Execute rpmlint on the spec file
discover:
    tests:
      - name: rpmlint
        test: rpmlint packit.spec
prepare:
    how: install
    package: rpmlint
```
