### ISSUE TITLE
Support fetching tests from another git repo

### ISSUE THREAD

**Issue by jencce** [teemtee/tmt#1125]
Something like this:

```yaml
discover:
    how: shell
    tests:
    - name: some-tests
      url: https://git.xxxx/test.git
      ref: master
      path: xx/some/tests
      test:  make run
```

This is a part of a tmt plan, while the test code is in another git repo with tmt metadata added.  Now, tmt is not fetching from the url.

Thanks.

**Comment by psss** [comment]
> the test code is in another git repo with tmt metadata added

If the other repository includes `tmt` metadata you can use the [fmf](https://tmt.readthedocs.io/en/stable/spec/plans.html#fmf) method for the test discovery:

```yaml
discover:
    how: fmf
    url: ...
    ...
```

Or are you proposing to add the git repository fetching support to the [shell](https://tmt.readthedocs.io/en/stable/spec/plans.html#shell) method instead?
