### ISSUE TITLE
Single `exclude` doen't work in `discover` config

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1130]
When a single `exclude` value is provided in the `discover` step config tests are not excluded as expected:

```yaml
discover:
    how: fmf
    url: https://github.com/teemtee/tmt
    exclude: /tests/unit
execute:
    how: tmt
```

The `exclude` implementation iterates over all letters of the `/tests/unit` string and thus no tests are selected:

```
 tmt run discover -v
/var/tmp/tmt/run-118

/plans/example
    discover
        how: fmf
        url: https://github.com/teemtee/tmt
        hash: ec2e296
        summary: 0 tests selected
        warning: No tests found, finishing plan.
```

Would be good to `tmt.utils.listify()` the `exclude` key and add test coverage for this case. @Ajchler, would you be interested in this?
