### ISSUE TITLE
New execute plugin `upgrade` for testing in-place upgrades

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1142]
On the tmt/upgrades hacking session we've discussed the best approach for handling in-place upgrades testing using `tmt`. The following syntax has been proposed:

```yaml
execute:
    how: upgrade
```

Optionally the source and target distribution release could be provided:

```yaml
execute:
    how: upgrade
    from: rhel-7
    to: rhel-8
```

The following steps would be performed:

* Run all discovered tests on the source distribution release
* Run a dedicated set of upgrade tasks in the form of tmt tests
* Run all discovered tests on the target distribution release

Under the hood, something like this would happen:

```yaml
execute:
  - name: old
    how: tmt
    environment:
        IN_PLACE_UPGRADE=old
  - name: upgrade
    how: tmt
    url: https://git.repo.with/upgrade/tests
  - name: new
    how: tmt
    environment:
        IN_PLACE_UPGRADE=new
```

The new `upgrade` plugin would not implement the upgrade itself, instead, it would just fetch a set of `tmt` tests from a defined repository which would cover the upgrade tasks. A simple example open source upgrade repo would demonstrate the functionality on Fedora.

**Comment by psss** [comment]
Regarding the `from` and `to` keys: This was really just a brainstorm. If I remember correctly, the Upgrades QE team currently uses something like `profile` for selecting the appropriate set of upgrade tasks. @mkluson, please share your view on this.

When I was thinking a bit more about the `upgrade` plugin config, I realized that, perhaps, it could be very much close with the `discover` step config for the [fmf](https://tmt.readthedocs.io/en/latest/spec/plans.html#fmf) method (or even completely identical except for the special `dist-git-*` or `modified-*` keys): Imagine that the upgrade tasks are just a well chosen set of tmt tests from the given repo.

Let's have a tangible example: The git repo could contain some common upgrade tasks/tests which are shared across profiles and some which are specific for given upgrade scenario. For these `tag` key could be used to select the right subset of upgrade tests:

```yaml
execute:
    how: upgrade
    url: https://git.repo.with/upgrade/tests
    filter: "tag: rhel8to9"
```

Or tests could be selected by name as it is already supported using the `test` key:

```yaml
execute:
    how: upgrade
    url: https://git.repo.with/upgrade/tests
    test:
      - /tests/initialize
      - /tests/disable-whatever
      - /tests/update-and-reboot
      - /tests/after-upgrade-checks
```

@mkluson, @lukaszachy, @thrix, @FrNecas, what are your thoughts on this?

**Comment by thrix** [comment]
No idea from me, I am a bit lost here sorry :(

**Comment by psss** [comment]
@mkluson, what are your thoughts on the general approach to filter tests from the upgrade repo using `filter` or `test` instead of introducing new keys?

**Comment by mkluson** [comment]
Hi @psss, before I answer your question, I would like to clarify the second test plan example you provided:
```yaml
execute:
    how: upgrade
    url: https://git.repo.with/upgrade/tests
    test:
      - /tests/initialize
      - /tests/disable-whatever
      - /tests/update-and-reboot
      - /tests/after-upgrade-checks
```
In my opinion, it should not contain tests, which do the upgrade itself (`/tests/update-and-reboot`). These tests will be included by the `upgrade` plugin. The plan should just choose, which test will run before and after the upgrade. So it would rather look like this:
```yaml
execute:
    how: upgrade
    url: https://git.repo.with/upgrade/tests
    test:
      - /tests/upgrade-test
      - /tests/another-upgrade-test
      - /tests/one-more-upgrade-test
```
Please correct it in your comment if my point is valid :-)

**Comment by mkluson** [comment]
Now to your question:

> what are your thoughts on the general approach to filter tests from the upgrade repo using filter or test instead of introducing new keys?

It seems to my like two different use cases:

1. To **choose which tests from repository** will be included in the upgrade test plan - in this case, usage of `filter` or `tests` makes perfect sense for me.
2. To **choose which upgrade plan** will be used for testing given upgrade path (examples of upgrade paths can be: RHEL 7 to RHEL 8, RHEL 8 to RHEL 9, Minor version upgrade of RHEL 8 or Major version upgrade od Fedora).  I expect that component will have to have more tmt upgrade plans to test more that one upgrade path. So we need some kind of mechanism to identify upgrade paths, where tmt upgrade plan is relevant. - here `from`, `to`, `profiles` or some naming convention come into a play.

**Comment by psss** [comment]
Seems we have a little misunderstanding: Let's clarify/agree on the terminology first:

* **upgrade tests** are the actual component tests which verify the expected functionality and support choosing setup/test/cleanup based on the `IN_PLACE_UPGRADE` variable
* **upgrade tasks** are the Upgrades QE magic which takes care of upgrading the system from the older distro to the newer one, does various necessary system adjustments and finally checks that everything went well

The proposed `upgrade` plugin would take care of the following steps:

* Run selected upgrade tests (selection is done in `discover` step)
* Run upgrade tasks from the upgrade repo (but which ones?)
* Run selected upgrade tests (selection is done in `discover` step)

What I'm trying to clarify is how to select the proper set of upgrade tasks from the upgrade repository. Or do you expect that for each upgrade path there will be a separate git repository? I guess it would make sense to share common upgrade stuff in a single repository to minimize maintenance.

```yaml
execute:
    how: upgrade
    url: https://git.repo.with/upgrade/tests
    upgrade-path: 8to9
```

The config above could be for example translated (under the hood) into selecting all upgrade tasks from that git repository which are relevant for the `8to9` upgrade path (could be done by the `tag` key, also environment variables could be used to instruct upgrade tasks to perform the desired upgrade path). Does it make it a bit more clear?
