### ISSUE TITLE
Keep library() untouched when upstream repo doesn't exist (raises conflict url in some cases instead)

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1220]
For beaker libraries tmt allows short form 'library(REPO/name)' and attempts to clone 'repo' from github.com/beakerlib/REPO. 
When successful it fetches it into 'workdir/libs/REPO' directory. Since there can be only single directory called 'REPO' tmt asserts that url used to clone it was the same.

However this check happens before the attempt to check if repo exists at all. 
So if test1 require library which is fetched into 'REPO' directory, tmt fails to convert library(REPO/name) even if REPO doesn't exist at all on beakerlib github. -  their url are different and exception is raised.

So for example this plan fails because t1 cloned privaterepo/foot and t2 tries to clone github.com/beakerlib/foo however it sees that destination 'foo' already exists but urls are different. It doesn't matter that github.com/beakerlib/foo doesn't exist at all.

Correct behaviour is to check if github.com/beakerlib/REPO exists first and only after that assert the same url.

```
/plan:
  discover:
    how: fmf
  execute:
    how: tmt
/t1:
  test: echo
  require:
  - url: privaterepo/foo
    name: /lib1
/t2:
  test: echo
  require:
  - library(foo/lib2)
```
