### ISSUE TITLE
Option to append post installation script to kickstart

### ISSUE THREAD

**Issue by juk** [teemtee/tmt#1282]
Kernel tests require an option to append post installation script to kickstart

Beaker xml example with kickstart post installation script
```
<ks_append>
<![CDATA[
%post --nochroot
umount --recursive /mnt/sysimage
%end                      							]]> 
</ks_append>
```

**Comment by lukaszachy** [comment]
Hm, isn't 'artemis' the only provision plugin which installs machine (in some cases)? All other provision plugins start image (so there is no kickstart used at all)

**Comment by psss** [comment]
@juk, just to clarify the use case: The above-mentioned example mentions a shell script. Is this something which could possibly be executed after the guest is installed and booted? In other words, could this use case be covered by a [prepare --how shell](https://tmt.readthedocs.io/en/latest/spec/plans.html#spec-plans-prepare-shell) step configuration? Or is something which definitely needs to be included in the kickstart? If the latter, what would be the difference when compared to implementing this using the `prepare` step?

**Comment by sztsian** [comment]
> Is this something which could possibly be executed after the guest is installed and booted? In other words, could this use case be covered by a [prepare --how shell](https://tmt.readthedocs.io/en/latest/spec/plans.html#spec-plans-prepare-shell) step configuration? Or is something which definitely needs to be included in the kickstart?

Hi,

In my scenario this must be executed in anaconda installation session before the guest booted. To explain the use scenario a bit, our team works on driver update disk. That is used during [system installation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/performing_an_advanced_rhel_9_installation/index#updating-drivers-during-installation_installing-rhel-as-an-experienced-user). In order to test if the driver update disk works with the installation media and anaconda installer, we need to run tests in installation phase. So currently we use post install scripts in kickstart to run our tests before the guest boot up.

> If the latter, what would be the difference when compared to implementing this using the `prepare` step?

IIUC the prepare step is executed in the installed system. We won't be able to test the function with anaconda installer and the installation media in such phase.

**Comment by psss** [comment]
Thanks much for clarification, @sztsian. So it seems this together with #1281 would need a dedicated config section for peforming tasks during the installation. Would it make sense to introduce a `kickstart` section under the `provision` step? It could look like this:

```yaml
provision:
    how: artemis
    image: fedora-35
    hardware:
        arch: x86_64
        memory: 8 GB
    kickstart:
        preinstall:
            nochroot: true
            script: umount --recursive /mnt/sysimage
```

Or should we rather try to introduce a generic section for configuring actions during installation? Perhaps something like this?

```yaml
provision:
    how: artemis
    image: fedora-35
    install:
        before:
            nochroot: true
            script: umount --recursive /mnt/sysimage
        after:
            script: a-custom-post-installation-script.sh
```

@lukaszachy, @thrix, @happz, any thoughts here?

Also would be good to check whether Resource Hub is planning to support kickstart configuration as well.

**Comment by lukaszachy** [comment]
Having generic option would be nice however [kickstart](https://docs.fedoraproject.org/en-US/fedora/latest/install-guide/appendixes/Kickstart_Syntax_Reference/#appe-kickstart-syntax-reference) can do too many things and adding them one-by-one while making it generic enough will be too resource consuming IMO.

I'd vote for "kickstart" section but I'm not sure about its content - [Beaker](https://beaker-project.org/docs/user-guide/customizing-installation.html) supports many options / ways to configure it.
Does tmt wants to do  the same? Since we don't install at all yet there is nothing as tmt kickstart to modify (and tmt will need it if it supports unattended installation).

**Comment by happz** [comment]
I'd take the generic road, but... It's true Kickstart can do a lot of stuff, and I'm mostly worried it'd be used for things that don't necessarily need to be performed by Kickstart, effectively locking the provisioning to just a single possible backend. Maybe I'm just worrying about the wrong thing and `kickstart` section would be fine.

Maybe something like this? Since it's not a HW requirement per se (even though it does affect the choice of provision plugin, right?), having `kickstart` outside of `hardware` makes sense to me, although I'm not sure there's the need for more internal structure:

```yaml
provision:
    how: artemis
    image: fedora-35
    hardware:
        arch: x86_64
        memory: 8 GB
    kickstart: |
      %post --nochroot
      umount --recursive /mnt/sysimage
      %end
```
