### ISSUE TITLE
Decouple frameworks from internal execute plugin

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1305]
Why??

* Framework implementation "leaks" into `internal` plugin - shady border, no clearly visible API or responsibilities, hard to add new frameworks.
* Frameworks have a very limited set of "entrypoints" (add requirements, add envvars, evaluate a test result) - relatively easy to define internal API and extract their code.

(I like borders and borders between components, this seems to be an obvious piece to improve while opening tmt code to possible contributors - I'm looking at you, `pytest`!)

**Comment by lukaszachy** [comment]
+100 Lovely, looking forward to the PR.

**Comment by eskultety** [comment]
@happz what do you need from other frameworks to make this possible? I can see a potential adoption of TMT if the Avocado framework could be integrated somehow rather than just creating a single test plan covering all Avocado test cases like a single unit.

**Comment by martinhoyer** [comment]
+1000

**Comment by happz** [comment]
Here's what's been in my buffer since February: https://github.com/teemtee/tmt/pull/2160

* it's a draft, and I'm 100 % sure it's broken - after the rebase, the recent multi-host-related changes were not moved correctly into their respective frameworks
* the idea is there, there's a plugin registry for frameworks, they have some defined points where execute plugin consults with them, etc.
* lacks docs.

I'll try to review it this week & make it up-to-date, and since I don't recall any serious blocker there, it could be a good starting point.

**Comment by martinhoyer** [comment]
> special preparation and requirements, e.g. adding python3-virtualenv, creating a virtualenv, installing pytest, etc.;

Just fyi, this is my 'workaround' for pytest (not everything is available in rpm packages).  
I like the pipx inject option to add plugins and libs.

```
prepare:
  - name: 'Prepare pytest environment'
    how: shell
    script:
      - python3 -m pip install pipx
      - python3 -m pipx ensurepath && source ~/.bashrc
      - python3 -m pipx install pytest
      - python3 -m pipx inject pytest sts-libs==0.0.6 pytest-variables[yaml] pytest-testinfra
    order: 50
```

pytest-variables is being used for more complex vars not suitable for environment variables tmt uses.
