### ISSUE TITLE
`tmt plans show` prints twice `dist-git-source`

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1343]
See dist-git-source printed two times:
```
$ tmt p show
/
    discover 
         how fmf
dist-git-source true
dist-git-source true
     enabled true

```
Plan is defined as 
```
discover:
    how: fmf
    dist-git-source: true
execute:
    how: tmt
```
