### ISSUE TITLE
Add `minidep` template

### ISSUE THREAD

**Issue by abitrolly** [teemtee/tmt#1363]
`tmt` test syntax is non-trivial to learn, because it has no own syntax. So having a template that shows how to install dependent package would save a lot of time. I would post it here, but am still trying to figure it out, because https://docs.fedoraproject.org/en-US/ci/tmt/ doesn't cover it.

**Comment by abitrolly** [comment]
Here is the example.
```
summary: Basic smoke test for python3-m2crypto
prepare:
  - how: install
    package:
      - python3-setuptools
      - python3-m2crypto
execute:
    script: python3 -c "import M2Crypto"
```

**Comment by psss** [comment]
I believe this should be now covered by the following two sections of the Guide:

* https://tmt.readthedocs.io/en/stable/guide.html#plans
* https://tmt.readthedocs.io/en/stable/guide.html#tests

What do you think? Or do you suggest to include your example in the `tmt init` templates? For this particular use case I'd suggest rather creating a test:

```yaml
summary: Basic smoke test for python3-m2crypto
test: python3 -c "import M2Crypto"
require:
  - python3-setuptools
  - python3-m2crypto
```
