### ISSUE TITLE
podman provisioner escaping needs work

### ISSUE THREAD

**Issue by t184256** [teemtee/tmt#137]
```
provision:
    how: container
    image: fedora:latest
prepare:
    how: shell
    script:
    - echo test > /test
```

tries to write to host FS.

```
    - sh -c "echo test > /test"
```

works as I expected

**Comment by thrix** [comment]
This is resolved for some time now, the problem is not apparent with the current version and `tmt` executor.

Tested via

```
❯ cat plans/example.fmf
---
summary: Basic smoke test
execute:
    how: tmt
    script: 
        - echo test > test
        - grep ^test$ test
```

```
    workdir: /var/tmp/tmt/run-118/plans/example/report
        how: display
        order: 50
            pass /script-00
                output.txt: /var/tmp/tmt/run-118/plans/example/execute/data/script-00/output.txt
        Read file '/var/tmp/tmt/run-118/plans/example/execute/data/script-00/output.txt'.
                content: 
            pass /script-01
                output.txt: /var/tmp/tmt/run-118/plans/example/execute/data/script-01/output.txt
        Read file '/var/tmp/tmt/run-118/plans/example/execute/data/script-01/output.txt'.
                content: test
```
