### ISSUE TITLE
link in discover/fmf should be one or more strings

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#1374]
Found during review of https://github.com/teemtee/tmt/pull/1241#discussion_r930704393

**Comment by lukaszachy** [comment]
Idea is that all other filters accept single str as a valid input, there shouldn't be exceptions unless really, really necessary. 
Adding simple reproducer:
```
/plan:
  execute:
    how: tmt
  discover:
    how: fmf
    link: /1374$
/test:
  test: ls
  link:
  - verifies: https://github.com/teemtee/tmt/issues/1374
```
Currently it does
```
$ tmt run discover
/var/tmp/tmt/run-002

/repro/plan
    discover
        how: fmf
        directory: /tmp/r_164909_lXr
        link: /
        link: 1
        link: 3
        link: 7
        link: 4
        link: $
        summary: 1 test selected
```
but it should be 
```
/repro/plan
    discover
        how: fmf
        directory: /tmp/r_164909_lXr
        link: /1374$
        summary: 1 test selected


```
