### ISSUE TITLE
fmf sync-repo: plan vs cmdline behaviour

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1379]
While trying to create plan and command for #1375 I found that .git is copied only if I specify --sync-repo on the commandline.

This is the plan (tests/full/plan.fmf):
```
discover:
    how: fmf
    sync-repo: true
provision:
    how: virtual
    memory: 4000
    disk: 40
execute:
    how: tmt
    interactive: true
```

If I run (in tests/full) `tmt run -vvv -ddd --id cmdline discover -h fmf --sync-repo` then .git exists at `/var/tmp/tmt/cmdline/plan/discover/default/tests/.git`

However if I run (again in tests/full) `tmt run -vvv -ddd --id plan discover ` then .git does not exist

Step files /var/tmp/tmt/plan/plan/discover/step.yaml and /var/tmp/tmt/cmdline/plan/discover/step.yaml are same and contain
```
status: done
data:
  - how: fmf
    sync-repo: true
    name: default
```

I see no reason why these two commands should behave different way as `cwd` was in both cases in tests/full
I'm inclined to say that 'plan' is correct as fmf root is in tests/full so we should not escape from there.
