### ISSUE TITLE
Support out-of-tree step schemas in plan schema

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1392]
Schemas for out-of-tree plugins can be put into tmt's schema directory, and they would be loaded correctly, but `plan.yaml` does not allow them:

```yaml
  provision:
    oneOf:
      - $ref: "/schemas/provision/artemis#"
      - $ref: "/schemas/provision/connect#"
      - $ref: "/schemas/provision/container#"
      - $ref: "/schemas/provision/local#"
      - $ref: "/schemas/provision/virtual#"
      - type: array
        items:
          anyOf:
            - $ref: "/schemas/provision/artemis#"
            - $ref: "/schemas/provision/connect#"
            - $ref: "/schemas/provision/container#"
            - $ref: "/schemas/provision/local#"
            - $ref: "/schemas/provision/virtual#"
```

This is a fairly frozen list - new schema would be part of the schema store, but `provision` plugins with unlisted `how` would be marked as invalid. We need a way to not just load them into the schema store, but also extend the plan schema to allow them.
