### ISSUE TITLE
virtual.testcloud not recognized as valid provision plugin

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1447]
Real name is 'virtual.testcloud' and that is not recognized by plan schema. However user should be able to type (basically) any unique prefix and idea is that if user types "virtual"  it can be any plugin which has "virtual" in the name.... (they should be compatible...)

**Comment by lukaszachy** [comment]
Reproducer:
```yaml
provision:
  how: virtual.testcloud

execute:
  how: tmt
```
and ` tmt p lint` ends with `warn: /plan:provision - {'how': 'virtual.testcloud'} is not valid under any of the given schemas`
