### ISSUE TITLE
`discover` using dist-git source should apply downstream patches before running tests

### ISSUE THREAD

**Issue by thozza** [teemtee/tmt#1482]
Using the following Plan:
```
summary: Run unit tests from source
discover:
    how: fmf
    dist-git-source: true
execute:
    how: tmt
```
results in TMT not taking downstream patches into consideration and not applying them at all on the extracted sources before executing tests. However downstream patches may be sometimes required for the unit tests to pass in the first place.

If tests are run on sources without applying downstream patches first, then as a result they are run on a version of sources which is not used anywhere (even not for building RPMs). TMT should really use the available RPM tooling and instead run something like `***pkg prep` and take the result (extracted archive + applied patches) and execute tests on such sources.

The relevant code is https://github.com/teemtee/tmt/blob/26fe39b82b94dea366073e934a6c1f77b797d7d9/tmt/steps/discover/__init__.py#L274-L305
