### ISSUE TITLE
Parametrize plans using context value

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#1513]
Similarly to variable parametrization described in
https://tmt.readthedocs.io/en/latest/examples.html#parametrize-plans
I would like to be able to parametrize using context value.

Example:
For tests I do mimic RHEL-9/C9S branch model, i.e. I have the following branches: `main rhel-9-main rhel-9.1.0`
In my plan I would like to use:

- main branch for upstream GitHub CI (and as a default if not specified)
- rhel-9-main branch for the latest RHEL-9 and C9S testing
- rhel-9.1.0 branch for the RHEL-9.1.0 ZStream testing

An example of such plan could be
```
summary: run Tier1 keylime e2e tests with swtpm and revocation notifier enabled

tag:
 - Tier1
 - CI-Tier-1

tier: 1

context:
  swtpm: yes

discover:
  - name: Configure system with SW TPM and IMA
    how: fmf
    url: https://github.com/RedHat-SP-Security/keylime-tests
    ref: main
    test:
      # setup TPM emulator
      - /setup/configure_tpm_emulator
      # change IMA policy to signing
      - /setup/configure_kernel_ima_module/ima_policy_signing
  - name: Tests
    how: fmf
    url: https://github.com/RedHat-SP-Security/keylime-tests
    ref: main
    filter: "tag:CI-Tier-1 | tag:CI-Tier-1-IMA"

execute:
  how: tmt

```
Instead of `ref: main` I would like to use the particular branch and I would like to avoid having to maintain (or update) plans every single release (in order to rewrite `ref` to the proper value).
My idea is that an extra context like `build_branch` could be passed by CI or a user and I would simply pass that value to the `ref`.
E.g. something like
```
  ref: $@{build_branch}
```
Eventually, one could use `adjust` to fine tune parameters (syntax may not be correct but you should get the idea)
```
adjust:
   - when: build_branch is not defined
     context+:
       test_branch: main
     because: no build branch is defined
     continue: false
   - when: build_branch == c9s
     context+:
       test_branch: rhel-9-main
     because: use rhel-9-main branch for c9s testing
     continue: false
   - when: build_branch is defined
     context+:
       test_branch: $@{build_branch}
     because: using the provided build branch as test branch

...
...
   
  ref: $@{test_branch}
```

**Comment by kkaarreell** [comment]
Additional food for thoughts, not necessarily in scope for this issue. Let's say I have multiple plans and each plan should do the same context adjustment in order to configure `test_branch`. It would be reasonable to move such adjustment to `main.fmf`. However, let's say I am the plan owner but I am not the (targeted) test repo owner. It would therefore make more sense to do the evaluation using some file (`main.fmf` or a different one?) in the target test repository. This would make sense especially in situations where I reference multiple test repositories from my plan and each repo is using different branching approach.

I repeat, I consider this to be out of scope for this issue but I just wanted to add some more context related to the possible use case.

**Comment by kkaarreell** [comment]
I did some research on this topic and identified some problems to solve:

1. ATM neither variable expansion is being done for the `adjust context` part, i.e.
```
adjust:
  - when: foo is not defined
    context:
      foo: ${FOO}
```
won't work. I don't know and which moment the current expansion is happening but possible we need to do it on other place too and maybe even sooner.

2. I have found a hack how to implement context expansion, sort of. I use `$@{context}` syntax and beside the existing `os.path.expandvars` I do also
 - `os.environ.clear()`
 - `os.environ.update(self.context)`
 - apply `os.path.expandvars` on `value.replace('$@', '$')`
etc.

3. However, the approach above doesn't work completely, as
 - we also need to expand the actual values in the context dictionary
 - `self.context` doesn't seem to contain context defined on cmd line and that one should be taken into account too
 - having `$@{some_context}` on the right side of the `context` definition opens a space for incomplete expansion or loops, i.e. for
```
adjust:
  - when: foo is not defined
    context:
      test_branch: $@{build_branch}
```
we need to make sure we know the actual value for $@{build_branch}.

Not sure how much helpful these notes are though.

**Comment by kkaarreell** [comment]
A also tried avoid using context and use rather environment variables but even in this case I hit an issue that variables are not expanded in `adjust` rules.
```
summary: run Tier1 keylime e2e tests with swtpm and revocation notifier enabled

discover:
  - name: Setup swtpm repo
    how: fmf
    url: https://github.com/RedHat-SP-Security/keylime-tests
    ref: ${TEST_BRANCH}
    test:
      # setup TPM emulator
      - /setup/configure_tpm_emulator
execute:
  how: tmt

adjust:
   - when: build_branch is not defined
     environment:
       TEST_BRANCH: main
     because: no build branch is defined
     continue: false
   - when: build_branch == c9s
     environment:
       TEST_BRANCH: rhel-9-main
     because: use rhel-9-main branch for c9s testing
     continue: false
   - when: build_branch is defined
     environment:
       TEST_BRANCH: ${BUILD_BRANCH}
     because: using the provided BUILD_BRANCH as test branch

```
```
$ tmt -c build_branch=rhel-9.1.0 run --environment BUILD_BRANCH=rhel-9.1.0 discover -h fmf -vvv 
/var/tmp/tmt/run-222

/plans/tier1-swtpm
    discover
        how: fmf
        name: Setup swtpm repo
        order: 50
        url: https://github.com/RedHat-SP-Security/keylime-tests
        ref: ${BUILD_BRANCH}

stderr (1/1 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: pathspec '`' did not match any file(s) known to git

```
As you can see `${BUILD_BRANCH}` has not been expanded despite being defined on a command line.
