### ISSUE TITLE
support guest/hostname for context:dimension

### ISSUE THREAD

**Issue by yizhanglinux** [teemtee/tmt#1544]
Hello
Could you help support the guest/hostname for context:dimension, I want to pass different environments when the test running on different servers, just like below:

https://tmt.readthedocs.io/en/stable/spec/context.html#dimension
```
adjust:
  - environment:
        TEST_DEVS: nvme0n1
    when: guest == server1
```

Thanks
Yi
