### ISSUE TITLE
proposal for plan discovery where schema specification for multihost

### ISSUE THREAD

**Issue by olichtne** [teemtee/tmt#1545]
The format of the multihost execute https://tmt.readthedocs.io/en/latest/spec/plans.html#where may need more thinking as defining multiple steps from multiple hosts in the same list may get confusing - e.g. the following two lists are functionally identical and there’s other ‘identical’ permutations which imo can lead to confusion:

* [host1.test1, host1.test2, host2.test1, host2.test2]
* [host2.test1, host2.test2, host1.test1, host1.test2]

This would be currently written as:
```yaml
execute:
  - name: c_test1
    script: client1.py
    where: client
  - name: c_test2
    script: client2.py
    where: client
  - name: s_test1
    script: server1.py
    where: server
  - name: s_test2
    script server.py
    where: server
```

and
```yaml

execute:
  - name: s_test1
    script: server1.py
    where: server
  - name: s_test2
    script server.py
    where: server
  - name: c_test1
    script: client1.py
    where: client
  - name: c_test2
    script client2.py
    where: client
```

i think the easiest "proposal" to improve this would be to do something like:

```yaml
execute:
  server:
    - name: s_test1
      script: server1.py
    - name: s_test2
      script server.py
  client:
    - name: c_test1
      script: client1.py
    - name: c_test2
      script client2.py
```

the goal here is to reduce the number or identical permutations that are written differently but result in the exact same test execution.

I'm not sure how the proposal would work with roles instead of guest names directly but that's why this is a proposal to start some form of a discussion :).

**Comment by psss** [comment]
Pasting a short summary and example from yesterday's discussion. The default place for defining tests which should be executed (including multihost tests) should be the `discover` step:

```yaml
discover:
    how: fmf
    filter: tag:multihost
```

The optional `where` key can be used to limit where the discovered tests should be executed:

```yaml
discover:
  - how: fmf
    filter: tag:client-tests
    where: client
  - how: fmf
    filter: tag:server-tests
    where: server
```

Alternative syntax using a `where` dictionary encapsulating the `discover` config under keys corresponding to guest names or roles can be used as well:

```yaml
discover:
    where:
        client:
          - how: fmf
            filter: tag:client-tests
        server:
          - how: fmf
            filter: tag:server-tests
```

This can result in much more concise config especially when defining several shell scripts for each guest or role:

```yaml
discover:
    where:
        server:
            how: shell
            tests:
              - test: first server script
              - test: second server script
              - test: third server script
        client:
            how: shell
            tests:
              - test: first client script
              - test: second client script
              - test: third client script
```

In the `execute` steps it would be possible to define where the synchronization among the guests should happen on both `step` and `test` level:

```yaml
execute:
    how: tmt
    sync:
        step:
          - prepare
          - execute
        test: each
```

@adiosnb is going to prepare a pull request with the spec update.
