### ISSUE TITLE
Order is not working in prepare elements

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#1581]
According to the docs: https://tmt.readthedocs.io/en/latest/spec/plans.html#prepare

```
Use the 'order' attribute to select in which order the preparation should happen if there are multiple configs.
```
and https://tmt.readthedocs.io/en/latest/spec/core.html#order
```
Must be an integer, negative values are allowed as well. The default value is 50.
```
This isn't working: https://artifacts.dev.testing-farm.io/12b12250-6d17-487a-8f63-2c3183326d97/
```
prepare:
  - name: a
    how: shell
    order: 1
    script: |
      set -euxo pipefail
      curl -o /tmp/run_test_pb_localhost.sh https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_scripts/run_test_pb_localhost.sh
      curl -o /tmp/prepare_localhost.yml https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_playbooks/prepare_localhost.yml
  - name: b
    how: ansible
    order: 99
    playbook:
      - /tmp/prepare_localhost.yml
```
The output doesn't even show that `order` is being read!
```
    prepare
        how: shell
        name: a
        overview: 1 script found
        script: 
            set -euxo pipefail
            curl -o /tmp/run_test_pb_localhost.sh https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_scripts/run_test_pb_localhost.sh
            curl -o /tmp/prepare_localhost.yml https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_playbooks/prepare_localhost.yml
    
        how: ansible
        name: b
        playbook: /tmp/prepare_localhost.yml
...
ERROR! the playbook: /tmp/prepare_localhost.yml could not be found
```
It is difficult to tell, but I believe because `order` is omitted from the output, it is not being taken into consideration.

So, just for the sake of completeness, I tried with the order inverted - same result.

Copied from: https://gitlab.com/testing-farm/general/-/issues/53

**Comment by thrix** [comment]
@richm FYI

**Comment by thrix** [comment]
I do believe the problem here is the file you create is on the test host, but the playbook is searched on the machine where tmt is executed.

@psss @happz @lukaszachy I wonder if we want to support these use cases somehow?

Seems to me maybe for this particular use case maybe support for remote playbooks would work: https://github.com/teemtee/tmt/pull/1489

**Comment by happz** [comment]
> According to the docs: https://tmt.readthedocs.io/en/latest/spec/plans.html#prepare
> 
> ```
> Use the 'order' attribute to select in which order the preparation should happen if there are multiple configs.
> ```
> 
> and https://tmt.readthedocs.io/en/latest/spec/core.html#order
> 
> ```
> Must be an integer, negative values are allowed as well. The default value is 50.
> ```
> 
> This isn't working: https://artifacts.dev.testing-farm.io/12b12250-6d17-487a-8f63-2c3183326d97/
> 
> ```
> prepare:
>   - name: a
>     how: shell
>     order: 1
>     script: |
>       set -euxo pipefail
>       curl -o /tmp/run_test_pb_localhost.sh https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_scripts/run_test_pb_localhost.sh
>       curl -o /tmp/prepare_localhost.yml https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_playbooks/prepare_localhost.yml
>   - name: b
>     how: ansible
>     order: 99
>     playbook:
>       - /tmp/prepare_localhost.yml
> ```
> 
> The output doesn't even show that `order` is being read!

That does not necessarily mean it's ignored - so far we can tell it's not shown at this point, like many other keys.

According to more detailed logs, `order` is noticed, with expected values:

```
02:02:53         how: shell
02:02:53         name: a
02:02:53         order: 1
02:02:53         overview: 1 script found
02:02:53         script: 
            set -euxo pipefail
            curl -o /tmp/run_test_pb_localhost.sh https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_scripts/run_test_pb_localhost.sh
            curl -o /tmp/prepare_localhost.yml https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_playbooks/prepare_localhost.yml
02:02:53         Execute command 'set -eo pipefail; set -euxo pipefail
curl -o /tmp/run_test_pb_localhost.sh https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_scripts/run_test_pb_localhost.sh
curl -o /tmp/prepare_localhost.yml https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_playbooks/prepare_localhost.yml
' on guest ...
...
02:02:54         how: ansible
02:02:54         name: b
02:02:54         order: 99
02:02:54         playbook: /tmp/prepare_localhost.yml
02:02:54         Applying playbook '/tmp/prepare_localhost.yml' on guest ...
```

Both steps were performed in the expected order, but let's say that might have been because they already were in this order in the fmf source.

> 
> ```
>     prepare
>         how: shell
>         name: a
>         overview: 1 script found
>         script: 
>             set -euxo pipefail
>             curl -o /tmp/run_test_pb_localhost.sh https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_scripts/run_test_pb_localhost.sh
>             curl -o /tmp/prepare_localhost.yml https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_playbooks/prepare_localhost.yml
>     
>         how: ansible
>         name: b
>         playbook: /tmp/prepare_localhost.yml
> ...
> ERROR! the playbook: /tmp/prepare_localhost.yml could not be found
> ```
> 
> It is difficult to tell, but I believe because `order` is omitted from the output, it is not being taken into consideration.
> 
> So, just for the sake of completeness, I tried with the order inverted - same result.

Now *this* would be the interesting log, `shell` and `ansible` switching their positions in the file, and being executed in this order - that would be clear proof that `order` is ignored. @richm could you point us to this particular experiment? it would be very helpful for ruling out the `order` issue. Although, I think @thrix is right about the actual issue, see below.

---

> I do believe the problem here is the file you create is on the test host, but the playbook is searched on the machine where tmt is executed.

I think you're correct, Ansible expects playbooks to exist on the control host, and I think it would be hard to change, as running a playbook on the remote host is not in Ansible's toolbox. Consuming playbook steps and executing them on the remote host, absolutely, but consuming steps from a remote playbook, likely not.

> 
> @psss @happz @lukaszachy I wonder if we want to support these use cases somehow?
> 
> Seems to me maybe for this particular use case maybe support for remote playbooks would work: #1489

Yes, that might be a solution, this should be supported:

```yaml
prepare:
  - name: a
    how: shell
    order: 1
    script: |
      set -euxo pipefail
      curl -o /tmp/run_test_pb_localhost.sh https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_scripts/run_test_pb_localhost.sh
  - name: b
    how: ansible
    order: 99
    playbook:
      - https://raw.githubusercontent.com/richm/tox-lsr/basic-smoke-test/src/tox_lsr/test_playbooks/prepare_localhost.yml
```

If `prepare_localhost.yml` needs `run_test_pb_localhost.sh` for something, it might be necessary to parametrize its location in the playbook, but that should be trivial if the remote playbook feature would be acceptable.
