### ISSUE TITLE
Consider using yq instead of grep when testing YAML content

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1585]
I spend some time updating a regular expression in https://github.com/teemtee/tmt/blob/main/tests/execute/basic/test.sh#L29. The input is a file like this one:

```yaml
/test/shell/bad:
    name: /test/shell/bad
    result: fail
    note:
    duration: 00:00:00
    ids:
        id:
        extra-nitrate:
        extra-task:
    log:
      - data/test/shell/bad/output.txt
    __class__:
        module: tmt.base
        name: Result
/test/shell/good:
    name: /test/shell/good
    result: pass
    note:
    duration: 00:00:00
    ids:
        id:
        extra-nitrate:
        extra-task:
    log:
      - data/test/shell/good/output.txt
    __class__:
        module: tmt.base
        name: Result
/test/shell/weird:
    name: /test/shell/weird
    result: error
    note:
    duration: 00:00:00
    ids:
        id:
        extra-nitrate:
        extra-task:
    log:
      - data/test/shell/weird/output.txt
    __class__:
        module: tmt.base
        name: Result
```

One of the expressions is supposed to verify whether a "good" result has an expected log named `output.txt`. Because the order of keys is not guaranteed, I ended up with the following regular expression, trying to match a multiline section of a file, with non-greede qualifiers to not peek into different results:

```shell
$ grep -Pzo '(?sm)^/test/shell/good:$.*?^ +log:$.*?^ +- data/.+?$' /tmp/tmp.HqL5Ij00ud/plan/shell/tmt/execute/results.yaml
/test/shell/good:
    name: /test/shell/good
    result: pass
    note:
    duration: 00:00:00
    ids:
        id:
        extra-nitrate:
        extra-task:
    log:
      - data/test/shell/good/output.txt
```

Similar but slightly less complicated expressions are needed to verify a "good" test has `result: pass` key:

```shell
$ grep -Pzo '(?sm)^/test/shell/good:$.*?^ *result: pass$' /tmp/tmp.HqL5Ij00ud/plan/shell/tmt/execute/results.yaml
/test/shell/good:
    name: /test/shell/good
    result: pass
```

It works.

Is tmt community open to using `yq` whenever possible for tests like this?

```shell
$ yq -r '."/test/shell/good" | .log | .[]' /tmp/tmp.HqL5Ij00ud/plan/shell/tmt/execute/results.yaml
data/test/shell/good/output.txt
$ yq -r '."/test/shell/good" | .result' /tmp/tmp.HqL5Ij00ud/plan/shell/tmt/execute/results.yaml
pass
```
If I'm not mistaken, `yq` can be installed from PyPI, its dependency - `jq` - should be available either in system repos, or from EPEL (https://pkgs.org/download/jq). Adopting it as a tool for dissecting YAML files would make tests much easier to develop and maintain.
