### ISSUE TITLE
tmt test import adds "RhtsRequires:" as a dependency under recommend when Makefile "Requires" is empty

### ISSUE THREAD

**Issue by olivergs** [teemtee/tmt#1687]
When a test has an empty Requires section in the makefile to generate testinfo.desc, it adds 'RhtsRequires:' to the recommend section. Also it duplicates the dependencies under require and recommend.

Sample generated main.fmf (original test can be found at: https://gitlab.com/redhat/centos-stream/tests/kernel/kernel-tests/-/tree/main/networking/wireless/tests/utility/ping4)

```
summary: Ping (IPv4) test using established connections
description: |
    Decription: Ping (IPv4) test using established connections
    Author: Ken Benoit <kbenoit@redhat.com>
    ...
contact: Ken Benoit <kbenoit@redhat.com>
component:
  - kernel
test: ./runtest.sh
framework: beakerlib
require:
  - nc
  - iputils
  - kernel-kernel-test-framework
  - kernel-kernel-wireless_tests
  - kernel-kernel-wireless_tests-utility
recommend:
  - 'RhtsRequires:'
  - nc
  - iputils
  - kernel-kernel-test-framework
  - kernel-kernel-wireless_tests
  - kernel-kernel-wireless_tests-utility
duration: 1h
extra-summary: /kernel/wireless_tests/utility/ping4
extra-task: /kernel/wireless_tests/utility/ping4
```

I suppose the problem is that TMT understands that an empty Requires does not exist and takes next value as the one for the requires.
