### ISSUE TITLE
Multihost synchronization

### ISSUE THREAD

**Issue by adiosnb** [teemtee/tmt#1705]
The issue gathers all discussions regarding synchronization problems in multi-host tests.

**Comment by adiosnb** [comment]
Adding several points and proposals from the last discussion.

## All `sync` is an enumerator with these values:
- **start** - synchronize at the beginning of the step, the first test execution
-  **name** - synchronize with the same test names
-  **index** - synchronize all tests, synchronization barrier before each test
-  **none** - do not synchronize

## Multihost
- L1 metadata (test metadata) key multihost: true
    - Could be used for filtering relevant multihost tests
    - Could be worked around by “filter: tag:multihost”
    - Could also be useful for syncing multihost tests only
- Mixing singlehost & multihost tests has a real use case
    - For example single host setup tasks
    - There could be a different number of setup tasks on server/client
    - Or sandwich testing: setup / test / inter-setup / test-again
- wow differentiates setup tasks and init tasks
    - BeakerJobWatch uses this information


## Keyword correct location
Defining `sync` in the `execution` step is too late and hard to process. The current proposal is to make `sync` a step attribute with the values defined above.

### Examples

```yaml
prepare:
  - name: packages
    how: ansible
    playbook: plans/packages.yml
 - name: services
    how: shell
    script: systemctl start service
    sync: index

execute:
  how: tmt
  sync: start
```

```yaml
discover:
  - name: setup-tasks
    how: fmf
    url: https://github.com/teemtee/tmt
    sync: none
  - name: multihost-tests
    how: fmf
    url: https://src.fedoraproject.org/rpms/tmt/
    where: client
    sync: name
```
