### ISSUE TITLE
New guide chapter: Efficient Metadata Handling

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#1721]
Discussed yesterday with @lukaszachy that it would be nice to summarize all features which are available for efficient metadata handling and preventing data duplication. The new guide chapter should cover these:

 * using `fmf` inheritance
 * `adjust` based on `context`
 * `yaml` referencing features
 * sharing tests across repositories

**Comment by psss** [comment]
Simple example demonstrating `yaml` referencing:

```yaml
discover:
  - name: upstream
    how: fmf
    filter: &selection tier:1 & tag:container
    url: https://github.com/teemtee/tmt
  - name: fedora
    how: fmf
    filter: *selection
    url: https://src.fedoraproject.org/rpms/tmt/
```
