### ISSUE TITLE
Add a plan of plans feature

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#1770]
This is an extension on plan import. The goal is to be able to reference multiple plans with just one link (fmf id).

Imagine following situation:

an SST-A repo:
```yaml
/plans/Tier1:
    tag:
      - tier
    discover:
      - how: fmf
        filter: tag:tier1
      - how: fmf
        url: https://remote.url
        filter: tag:tier1
    execute:
      - how: tmt
/plans/Tier2:
    tag:
      - tier
    discover:
      - how: fmf
        filter: tag:tier2
      - how: fmf
        url: https://remote.url
        filter: tag:tier2
    execute:
      - how: tmt
```

Now, I want to run all the Tier plans from the SST-A's repo. To include whole sub-tree of plans or filtered plans my plan should look like this:
```yaml
/SST-A:
    plan:
        include:
            url: https://sstA.repo.url
            name: /plans
            filter: tag:tier
```

It could be easily internally converted to the known problem:
```yaml
/SST-A:
    /plans/Tier1:
        import:
            url: https://sstA.repo.url
            name: /plans/Tier1
    /plans/Tier2:
        import:
            url: https://sstA.repo.url
            name: /plans/Tier2
```

Which in turn would effectively be:
```yaml
/SST-A:
    /plans/Tier1:
        tag:
          - tier
        discover:
          - how: fmf
            filter: tag:tier1
          - how: fmf
            url: https://remote.url
            filter: tag:tier1
        execute:
          - how: tmt
    /plans/Tier2:
        tag:
          - tier
        discover:
          - how: fmf
            filter: tag:tier2
          - how: fmf
            url: https://remote.url
            filter: tag:tier2
        execute:
          - how: tmt
```
*+* correctly cloned remote repository for the local discovery to work.

**Comment by happz** [comment]
I'm trying to understand the difference between what tmt already has - "take a plan from a repo and replace the current plan with it" - and what's the proposal here. Is it "just" about taking *multiple* plans from a repo, and sort of replacing the current plan with all of them? Sorting them under the current plan as its children, but effectively doing import of multiple plans instead of one?

**Comment by martinpitt** [comment]
@happz That sounds more or less what we need, but more like a "recursive import". E.g. we want to run [cockpit-podman's three plans](https://github.com/cockpit-project/cockpit-podman/blob/main/plans/all.fmf)  in [podman](https://github.com/containers/podman/blob/main/plans/cockpit-podman.fmf). Currently podman's (and all other consumers, like [SELinux](https://github.com/fedora-selinux/selinux-policy/blob/rawhide/plans/cockpit.fmf) has to keep a duplicate of cockpit's plan structure, and kept in sync. This doesn't scale well if the plans change over time, as that change has to be applied to all other projects which want to run these "foreign" plans. 

A [naive approach](https://github.com/cockpit-project/cockpit/commit/3e4c1fb3666a461c6b2af78b91239dacb892d5ea) of just pointing to a foreign repo and not duplicating the plan structure results in a single plan which runs all of the repo's (intended) plans as tests -- i.e. serially in a single instance.

**Comment by idorax** [comment]
Hi @sopos and @martinpitt, here is a summary after discussion - `add plan of plans`.

* A single plan would expand into many plans, and parent-child relationship will be used instead of replacing the local plan.
* For the naming, we would like to concatenate local `(referencing)` plan name + remote `(referenced)` plan name. e.g.
  ```yaml
  /plans/local/plans/remote
      /plans/something
  ```
* For selecting plans, it is very likely to support to select by a regular expression. By default, all plans would be imported when name is not provided.
* To trigger the new functionality, just omit the name or use a regular expression.   And the implementation would be backward compatible with the sing one-one mapping.
* To support mixing local config with remote content, tmt should complain about such a combination:
   ```yaml
   execute:
       how: tmt
       script: echo
   plan:
       import:
           url: here
           name: (optional) REGEX
   ```
* To avoid recursion, we would not pay efforts to implement it from the start. We can consider it
  in the future.

Hi @psss, @happz,  @lukaszachy and @thrix, please help to correct the summary above if anything is incorrect, thanks very much!

**Comment by happz** [comment]
> Hi @psss, @happz, @lukaszachy and @thrix, please help to correct the summary above if anything is incorrect, thanks very much!

+1.

One thing I'm not sure about is how the feature is enabled: not specifying the name is fine, but "use a regular expression" - `/foo` is also a regular expression, matches `/foobar` and many other strings, yet it contains no interesting regex-ish characters like dot. It's very hard to tell whether a string is not supposed to be a regular expression...

I think we should add a flag, another key to enable this feature, to make it clear that the user really wants us to import remote plans - even just a single plan! - under the local one. We do have the whole `import` mapping to play with.

```yaml
plan:
    import:
        url: https://src.fedoraproject.org/tests/binutils
        # No name set, imports all plans.

    import:
        # Not a regular expression, but all plans in the repo start with `/plans`.
        name: /plans

    import:
        # Not a regular expression, yields just a single plan - shall we replace the local
        # one, or did the user want it to be put under the local plan?
        name: /plans/build-gating/common

    #
    # With a flag telling tmt to "import and slot under the local plan". Let's call it `integrate` for now.
    #

    import:
        url: https://src.fedoraproject.org/tests/binutils

        # No name set, imports all plans.
        # integrate: true -> nothing changes, remote plans slotted under the local plan.
        # integrate: false -> raise an error, tmt is not replacing a single plan with multiple remote ones.

    import:
        # Not a regular expression, but all plans in the repo start with `/plans`.
        name: /plans
        # integrate: true -> nothing changes, remote plans slotted under the local plan.
        # integrate: false -> raise an error, tmt is not replacing a single plan with multiple remote ones.

    import:
        # Not a regular expression, yields just a single plan - shall we replace the local
        # one, or did the user want it to be put under the local plan?
        name: /plans/build-gating/common

        # integrate: true -> slot the remote plan under the local one. This would be a new
        #                    behavior when 1:1 import happens, special case of "import and
        #                    slot under" for a single plan.
        # integrate: false -> replace the local plan with the remote one. This is the current
        #                     behavior of "import a plan".
```
