### ISSUE TITLE
failed debuginfo package installation does not fail tmt prepare

### ISSUE THREAD

**Issue by sopos** [teemtee/tmt#1780]
```
        debuginfo: 1 package requested                      
            kernel                                          
        Execute command 'dnf install -y /usr/bin/debuginfo-install' on guest 'sopos-rhel88-brq.usersys.redhat.com'.                                                                                                                             
        Run command: ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oServerAliveInterval=60 -oServerAliveCountMax=5 -S/run/user/1000/tmt/tmpj3ueomxs root@sopos-rhel88-brq.usersys.redhat.com 'export TMT_PLAN_D
ATA=/var/tmp/tmt/rhel-88/plans/default/data; dnf install -y /usr/bin/debuginfo-install'                                 
            cmd: dnf install -y /usr/bin/debuginfo-install                                                              
            out: Updating Subscription Management repositories.                                                         
            out: Unable to read consumer identity           
            out:                                            
            out: This system is not registered with an entitlement server. You can use subscription-manager to register.                                                                                                                        
            out:                                            
            out: Last metadata expiration check: 1:08:20 ago on Thu 05 Jan 2023 07:00:29 PM CET.                        
            out: Package yum-utils-4.0.21-17.el8.noarch is already installed.                                           
            out: Dependencies resolved.                     
            out: Nothing to do.                             
            out: Complete!                                  
        Execute command 'debuginfo-install -y "kernel"' on guest 'sopos-rhel88-brq.usersys.redhat.com'.                 
        Run command: ssh -oForwardX11=no -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oServerAliveInterval=60 -oServerAliveCountMax=5 -S/run/user/1000/tmt/tmpj3ueomxs root@sopos-rhel88-brq.usersys.redhat.com 'export TMT_PLAN_D
ATA=/var/tmp/tmt/rhel-88/plans/default/data; debuginfo-install -y "kernel"'                                             
            cmd: debuginfo-install -y "kernel"              
            out: Updating Subscription Management repositories.                                                         
            out: Unable to read consumer identity           
            out:                                            
            out: This system is not registered with an entitlement server. You can use subscription-manager to register.                                                                                                                        
            out:                                            
            out: Last metadata expiration check: 1:08:25 ago on Thu 05 Jan 2023 07:00:29 PM CET.                        
            out: Could not find debuginfo package for the following installed packages: kernel-4.18.0-444.el8.x86_64                                                                                                                            
            out: Could not find debugsource package for the following installed packages: kernel-4.18.0-444.el8.x86_64                                                                                                                          
            out: Dependencies resolved.                     
            out: Nothing to do.                             
            out: Complete!                                  
```
