### ISSUE TITLE
support `result:custom` reporting for the test itself

### ISSUE THREAD

**Issue by comps** [teemtee/tmt#1855]
Using `result: custom` in a test's `main.fmf` metadata, and having the test produce
```yaml
- name: /some/test
  result: pass
- name: /some/other/test
  result: fail
```
in `results.yaml`, assuming the test name (path in a repo) is `/parent`, this produces
```yaml
    report
        how: display
            pass /parent/some/test
            fail /parent/some/other/test
        summary: 1 test passed and 1 test failed
```
The problem is that there is no way to report a result for `/parent` itself, using `name: /` like
```yaml
- name: /some/test
  result: pass
- name: /some/other/test
  result: fail
- name: /
  result: pass
```
results in an appended trailing `/`:
```yaml
    report
        how: display
            pass /parent/some/test
            fail /parent/some/other/test
            pass /parent/
        summary: 2 tests passed and 1 test failed
```

---

Finally, there is a possible bug allowing `name:` to start with a non-slash character, consider:
```yaml
- name: -some/test
  result: pass
```
resulting in:
```yaml
    report
        how: display
            pass /parent-some/test
        summary: 1 test passed
```
