### ISSUE TITLE
`+` character removed from plan path

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#1857]
Tiers are running a plan with this name: `/plans/cs_infra_services/tier1/memtest86+`.

See a test result [here](http://artifacts.osci.redhat.com/testing-farm/59989ee4-c1c8-4f71-9083-f2810c830b09/pipeline.log)

After initial investigation why the test errors out, we found out that TF could not find `results.yaml` and that is because `+` is removed from the path, see yourself [here](http://artifacts.osci.redhat.com/testing-farm/59989ee4-c1c8-4f71-9083-f2810c830b09/work-memtest86+o3g_7iup/plans/cs_infra_services/tier1/)

Downstream issue: https://issues.redhat.com/browse/TFT-1881

**Comment by lukaszachy** [comment]
Simpler reproducer
```
/test:
  test: echo

/foo+:
  provision:
    how: local
  discover:
    how: fmf
  execute:
    how: tmt
```

See that while `/foo+` is listed as plan in `run.yaml`, its created directory is `foo`

**Comment by happz** [comment]
> TF constructs the path to the plan directly according to the plan name, the code is [here](https://artifacts.dev.testing-farm.io/e19ec3d4-b006). It feels like, if there is some other path name we should use, tmt should provide it us rather then implemeting the logic of safe_name on both places. `tmt plan export` should potentially expose the used path by `tmt`?

In theory, possible. `tmt * export` does expose `name`, I see no problem with throwing in `safe_name` as well - it's not in the list of exposed keys though.

**Comment by happz** [comment]
```diff
diff --git a/tmt/base.py b/tmt/base.py
index 81fe2f51..0c716af9 100644
--- a/tmt/base.py
+++ b/tmt/base.py
@@ -538,8 +538,11 @@ class Core(
         if keys is None:
             keys = self._keys()
 
-        # Always include node name, add requested keys, ignore adjust
-        data: Dict[str, Any] = dict(name=self.name)
+        # Always include node name (and its "safe for paths" variant),
+        # add requested keys, ignore adjust.
+        data: Dict[str, Any] = dict(
+            name=self.name,
+            safe_name=self.safe_name)
         for key in keys:
             # TODO: provide more mature solution for https://github.com/teemtee/tmt/issues/1688
             # Until that, do not export fields that start with an underscore, to avoid leaking
```

And with

```yaml
"/really weird !@#$%^&*()_-+=[]":
    summary: Some really weird characters in the name.
```

I get:

```
  - name: /plan/really weird !@#$%^&*()_-+=[]
    safe_name: /plan/really-weird-_
    summary: Some really weird characters in the name.
    description: Testing data for test the feature to export plans to yaml or dict
    enabled: true
    order: 50
    link: []
    id:
    tag: []
    tier:
    context: {}
    gate: []
    discover:
        how: fmf
        name: default-0
    execute:
        how: tmt
        name: default-0
```

Needs a test, I used `/tests/plan/export/data/plan.fmf` for this quick check, tests and stories suffer the same issue & let's copy it there as well. It's all yours, @thrix ;)
