### ISSUE TITLE
Add distro and arch info to guests.yaml

### ISSUE THREAD

**Issue by jchecahi** [teemtee/tmt#1921]
It might be useful to have some of the extra information that `tmt run` prints for the provision step dumped in the result `guests.yaml` file located under `<tmt-run-dir>/<plan>/provision/`. 
For example when running with `tmt run -vv provision -h container -i fedora:38` tmt prints this info for the provision step:
```
    provision
        how: container
        image: fedora:38
        Check for container image 'fedora:38'.
        name: tmt-195-XueQEvTE
        distro: Fedora Linux 38 (Container Image Prerelease)
        kernel: 6.0.12-300.fc37.x86_64
        summary: 1 guest provisioned
```
However, when inspecting `guests.yaml` we see this:
```
default-0:
    role:
    guest: tmt-198-FipCKXmQ
    image: fedora:38
    user: root
    force_pull: false
    container: tmt-198-FipCKXmQ
    __class__:
        module: tmt.steps.provision.podman
        name: PodmanGuestData
```
It would be very useful to have at least the distro and architecture (or kernel, from which we can infer the arch) for later inspection. That way we can see where a past run was run.
