### ISSUE TITLE
tmt does not print ansible output even if extra-args: '-vvv' are used

### ISSUE THREAD

**Issue by mmacura311** [teemtee/tmt#1936]
Hi, I have this example prepare step:
```
prepare:
  - name: Basic setup playbook
    how: ansible
    extra-args: '-vvv'
    playbook: ./ansible/setup.yml
    order: 81
```
and no matter what I do I cannot get a printout of that particular ansible prepare step. Shell prepare methods print without issue.
I tried `tmt run -vvv` and even `tmt run -dvvv` but I still no output is produced, just tmt output:
```
        how: ansible
        name: Basic setup playbook
        order: 81
        playbook: ./ansible/setup.yml
        ok: 2 tasks
        changed: 2 tasks
        skipped: 2 tasks
        ignored: 1 task
```

according to the docs this is implemented and does not mention any other conditions to have this working.
https://tmt.readthedocs.io/en/stable/spec/plans.html#spec-plans-prepare-ansible
