### ISSUE TITLE
Add fmf-id info to results.yaml

### ISSUE THREAD

**Issue by jchecahi** [teemtee/tmt#1940]
It would be very useful to have fmf-id information per test in `results.yaml`. That would allow to cross-reference different testruns and identify where a given test was run regardless it was run in different plans, imported from a remote repository, or run several times in the same plan but with different parameters.

For example, consider these two testplans of different Fedora packages:
https://src.fedoraproject.org/rpms/llvm/blob/rawhide/f/tests/build-gating.fmf
https://src.fedoraproject.org/rpms/libomp/blob/rawhide/f/tests/build-gating.fmf

Both runs this tmt test:
https://src.fedoraproject.org/tests/llvm/blob/main/f/integration-test-suite

When running the first plan and inspect `results.yaml` file for that test we see this:
```
  - name: /integration-test-suite
    serialnumber: 3
    result: pass
    note:
    duration: 00:00:25
    ids:
        id:
        extra-nitrate: TC#0614094
        extra-task: /tools/llvm/integration-test-suite
  [ omitted log, guest, etc.]
```

When running the second plan and look at `results.yaml` we see:
```
  - name: /upstream-llvm-integration-testsuite/integration-test-suite
    serialnumber: 2
    result: pass
    note:
    duration: 00:00:26
    ids:
        id:
        extra-nitrate: TC#0614094
        extra-task: /tools/llvm/integration-test-suite
  [ omitted log, guest, etc.]

```

If it wasn't for `extra-task` or `extra-nitrate` it would be very hard to tell this is in fact the same test. Unfortunately these fields (as well as id) are not mandatory and might or might not be present for a given test. IIUIC, fmf-id should be present in all tmt tests as long as they belong to a git repo..

Does it sound reasonable to add this feature?

**Comment by happz** [comment]
I believe this issue has been implemented long time ago:

```yaml
  - name: /Test name escaping/tests/01-basic quote's error
    result: pending
    original-result: pending
    note: []
    log: []
    start-time:
    end-time:
    duration:
    serial-number: 1
    fmf-id:
        name: /Test name escaping/tests/01-basic quote's error
```
