### ISSUE TITLE
Implement restraint plugin for the execute step

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#197]
[Restraint](https://restraint.readthedocs.io/en/latest/index.html) allows custom plugins (e.g. `scl enable`)  and has support for avc_check, dmesg etc from the box. 

Since restraint is client-server, tmt would need to
a) install restraint on VM  (depends on 3rd party packages)
b) prepare job.xml from tests.yml
c) spawn restraint on host, set it to connect to VM and feed on job.xml 
d) convert test outcome to internal format

As for custom plugins - they are just shell script placed to the right location, IMHO we should create way to "install" them via tmt - so user doesn't need to create their own ansible scripts to detect right destination directory (in case they differ between systems). E.g.
```
how: restraint
plugins: 
  task_run: source_path [source_path]
  report_result: source_path
```
