### ISSUE TITLE
Test name matching using re.fullmatch()

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#2002]
Current implementation using `match()` for test name matching is confusing from a user perspective. It would be better if `tmt` would be using `fullmatch()` which would make intentions of the test plan owner more obvious.

Today
```
tests:
 - /tests/prefix
 - /tests/exact$
```
After
```
tests:
 - /tests/prefix.*
 - /tests/exact
```
One way to enable smooth migration for the users would be enabling to configure the required behavior in the `.tmt/config` file. At some point in the future we could announce switchich of the default.

Doing hard switch would be difficult due to different `tmt` versions used in our infrastructure.

**Comment by psss** [comment]
Summary from the triage:

* makes sense
* need to implement this using config not to break existing stuff (make it opt-in)
* currently blocked on the more advanced config implementation (e.g. user, in git repo, system wide)

**Comment by comps** [comment]
> need to implement this using config not to break existing stuff (make it opt-in)

This was also raised on Slack, but I think it's a really bad idea here.

For example - if I give another person a `tmt` CLI to run, with `tmt run ... tests -n /some/test`, they might not have the system-wide (or user-wide) config snippet, so it runs `/some/test`, but also `/some/testing`, etc. for them.

Similarly - if tmt doesn't want to break the compatibility, will Testing Farm do it? If not, the opt-in feature becomes kind of useless, if we can't reliably use it on CLI and (especially) in plans.

Consider how this (real) example would look / impact things:
```
discover:
    how: fmf
    test:
      # every remediation method, but only the basic reference environment,
      # without GUI variants
      - /hardening/oscap/[^/]+$
      - /hardening/anaconda/[^/]+$
      - /hardening/kickstart/[^/]+$
      - /hardening/ansible/[^/]+$
      - /hardening/image-builder/[^/]+$
      # UEFI tests, due to capacity we run them only on RHEL-10
      - /hardening/[^/]+/uefi
      - ...
```

*Please*, consider some way of changing this for everybody, so it's consistent (assuming new enough tmt version). Sooner or later, you'll find more breaking changes that could use the same process (a "will be changed soon" or "breaking changes" section in release notes, or something like that).

If it's an opt-in config, we will not use it. It's too dangerous to rely on it.

edit: It would be fine if stored in the repo (maybe inside `.fmf`, as some "feature flags"?) and not overridable by some user/system config, the point above still stands, IMHO.
