### ISSUE TITLE
`tmt lint` fails with fmf path not in root

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2006]
Here is a minimum example:
```console
$ tree -a
.
└── a
    ├── .fmf
    │   └── version
    └── plan.fmf
$ tmt --root a lint
/plan
pass correct attributes are used
fail No tree found in repo 'None', missing an '.fmf' directory?
```
with `plan.fmf`:
```yaml
summary:
  simple example
discover:
  how: fmf
  filter: "tag: something"
execute:
  how: tmt
```

`tmt --root a run` works fine, but I did not confirm that others work.
