### ISSUE TITLE
`discover.dist-git-source` fails with relative `path`

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2097]
This one could either be a tmt issue or a testing-farm issue (also reported [here](https://gitlab.com/testing-farm/general/-/issues/68)), and I don't know how to test this locally. I suspect this could be related to the `path` being a hidden folder.

```
#fmf_file
discover:
  how: fmf
  dist-git-source: true
  path: .distro
```
[Downstream PR](https://src.fedoraproject.org/rpms/python-scikit-build-core/pull-request/15), [Testing farm artifact](https://artifacts.dev.testing-farm.io/fbc1661a-4514-4ef1-8d27-433aedcdd926/)

**Comment by lukaszachy** [comment]
Thanks you for the report,  reproduced. I guess some parts of tmt omit hidden folders when copying but I will need to dig into it more.

Steps to reproduce:
```
git clone https://src.fedoraproject.org/forks/packit/rpms/python-scikit-build-core.git
cd python-scikit-build-core/
git co -t origin/0.4.0-rawhide-update-propose_downstream
tmt run discover
```

**Comment by LecrisUT** [comment]
About the steps to reproduce, note that it is missing `tmt --root`. It should be added by `discover.path`. Also note the [`packit.yaml`](https://github.com/scikit-build/scikit-build-core/blob/27a9d620212814e7ba932a0388665e572abde108/.packit.yaml#L12-L21) file is setup as:
```yaml
files_to_sync:
  # tmt setup
  - src: .distro/.fmf/
    dest: .fmf/
  - src: .distro/plans/
    dest: plans/
    filters:
      - "- .distro/plans/main.fmf.dist-git"
      - "- .distro/plans/rpmlint.fmf"
  - src: .distro/plans/main.fmf.dist-git
    dest: plans/main.fmf
```
So the fmf_root on dist-git and fmf_root in the source are different, which is what `discover.path` is supposed to fix.
