### ISSUE TITLE
Test with empty custom results should end as an ERROR

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#2127]
Currently the test 'disappears' from the run. IMO it is an error - test requested to be allowed to provide the result but failed to do so.

Note that 2 tests were selected but only 1 was executed. If there is just a single test the `tmt run` finishes with `total: no results found`. 

Reproducer:
```
/t:
  test: echo '[]' >${TMT_TEST_DATA}/results.yaml
  result: custom
/t2:
  test: echo

/p:
  execute:
    how: tmt
  discover:
    how: fmf
  provision:
    how: local
```

When executed:
```
/var/tmp/tmt/run-142

/plan/p
    discover
        how: fmf
        directory: /tmp/r_124829_QLS
        summary: 2 tests selected
    provision
        how: local
        multihost name: default-0
        distro: Fedora Linux 37 (Workstation Edition)
        summary: 1 guest provisioned
    prepare
        summary: 0 preparations applied
    execute
        how: tmt
        summary: 1 test executed
    report
        how: display
        summary: 1 test passed
    finish
        summary: 0 tasks completed

total: 1 test passed
```
