### ISSUE TITLE
Is network HW requirement "contains" or "equals", i.e. these NICs and no other?

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2137]
```yaml
# Select by vendor and device name
network:
  - type: eth
```

Does this requirement mean no other NICs are allowed on the machine? If that's so, how would one express other NICs are allowed? And if this means other NICs are allowed, how would one express that this NIC and no other is allowed on the guest?

We're trying to enlarge the pool of machines available for a particular plan. The plan lists 2 `type: eth` entries under `network`, and it's not clear what is the expectation - the user is fine with "at least these, don't care about the rest", that would enlarge the pool of available boxes, but is that aligned with the specification? And how would we express the other case, no matter which one would it be?

Edit: the same applies to `disk`:

```yaml
disk:
  - size: '>= 2 GB'
  - size: '>= 20 GB'
```

Only these two disks, or can the machine have 10 disks, but two must match this requirement?

**Comment by mm0ran** [comment]
If the current expectation is that this will give you 2 and only 2 nics:
```
- eth
- eth 
```

Then to keep backwards compatibility with that expectation and at the same time allow less strict requirements to the number of NICs, we could just add a `count` field to `network`:
```
network:
  - type: eth
    count: ">=2"
```

**Comment by happz** [comment]
Unfortunately, `count: ">=2"` does not say anything about the number of allowed `type: not-so-much-eth` NICs.

```yaml
network:
  - type: eth
    count: ">= 2"
  - type: .*
    count: ">= 0"
```

Feels weird :/
