### ISSUE TITLE
Fetch a library with both `url` and `path` defined

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#2149]
Fetching a library when both `url` and `path` are defined in the `require` key to import a the library from a repository where the `fmf` tree is nested deeper in the directory structure does not work. Example test metadata:

```yaml
/test:
    test: ./test.sh
    framework: beakerlib
    require:
      - url: https://github.com/beakerlib/example
        ref: deep-library
        path: /deep
        name: /file
        type: library
```

The config above results into the following error:

```
Repository 'https://github.com/teemtee/try' does not contain fmf metadata.

The exception was caused by 1 earlier exceptions

Cause number 1:

    Unable to find tree root for '/var/tmp/tmt/lib/plan/discover/default-0/libs/try'.
```
