### ISSUE TITLE
Hardware requirements for a GPU

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#2154]
We have a request to be able to test against AWS instances with a GPU:

https://discussion.fedoraproject.org/t/setting-up-fedora-ci-for-rocm/84373/11

Seems to start, it would be enough to ask for a HW with a dedicated GPU and maybe to say if it is NVIDIA or Intel.

Any more ideas are welcome.

**Comment by Mystro256** [comment]
From the thread, for ROCm testing I would need either a vega or navi HW. Anything before that is really buggy and not great for testing.

**Comment by happz** [comment]
How would one look for "a vega or navi HW"?  As a GPU noob, I presume it could boil down to something like a "graphic card" name, model names, vendors, something that would be similar to the current CPU requirement specs, https://tmt.readthedocs.io/en/stable/spec/hardware.html#cpu.

```
00:1e.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 12 [Radeon Pro V520/V540] (rev c3)
```

A bit of brainstorming: a "vendor" seems to be something to recognize, "Radeon Pro V520/V540" smells feels like `cpu.model-name`, "Navi" is supposed to be a "code name", the architecture is called different, probably no point trying to fit it into the CPU's "family" or "family-name".

```yaml
gpu:
    # Probably not precise, might end up way too verbose
    model-name: "~ Radeon Pro .+"
    # Sure, this should be cheap to support, even though it's fairly useless on its own
    vendor: AMD
    # "I would need either a vega or navi HW"
    arch: "~ vega|navi"
```

It needs to be configurable for instance-type-based providers like AWS or OpenStack, we already can extract CPU info from AWS EC2 `describe-instance-types` and route `model-name: Graviton3` to the right set of instance types, and different instance types may easily share vendor but not model-name; and Beaker needs to expose GPU info, we could then create a filter to match it, even if it would be merged from these distinct keys (I bet it does expose the info, but I don't recall the right XML element for the filter).
