### ISSUE TITLE
Beaker provision plugin schema lacks "role"

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2204]
```yaml
provision:
  - how: beaker
    role: client
  - how: beaker
    role: server
```

results in the following:

```warning: provision - [{'how': 'beaker', 'role': 'client'}, {'how': 'beaker', 'role': 'server'}] is not valid under any of the given schemas.```

https://github.com/teemtee/tmt/blob/main/tmt/schemas/provision/beaker.yaml is missing schema for `role` key.
