### ISSUE TITLE
Test require ref doesn't support variable expansion nor dynamic ref

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#2228]
In a test I have library requires:
```
 require:
   - url: https://github.com/RedHat-SP-Security/keylime-tests
     ref: ${REF_BRANCH}
     name: /Library/test-helpers
```
where `REF_BRANCH` is defined in a plan.
However this doesn't work as I am getting
```
fail: Reference '${REF_BRANCH}' for library 'keylime-tests/test-helpers' not found.
```
Also, dynamic ref is most likely not supported too.
