### ISSUE TITLE
tmt lint doesn't support dynamic ref

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#2246]
For plans with dynamic ref 
```
discover:
   - name: Tests
      how: fmf
      url: https://github.com/RedHat-SP-Security/keylime-tests
      ref: "@.tmt/dynamic_ref.fmf"
      filter: "tag:CI-Tier-1 | tag:CI-Tier-1-IMA"
```
tmt lint produces failures like
```
fail P005 remote fmf id in "Tests" is invalid, git ref '@.tmt/dynamic_ref.fmf' is invalid
```

tmt lint should not report dynamic ref as a failure.
