### ISSUE TITLE
Fail the test the first time it detected an unsupported framework.

### ISSUE THREAD

**Issue by guoguojenna** [teemtee/tmt#2255]
In the test fmf file, I set the  'framework: python', and run the test.

At discover step, it prints a warn " **warn: /rdma/sanity/server:framework - 'python' is not one of ['beakerlib', 'shell']**".  The test continued to provision, prepare, and finally failed at execute step with error "fail: Unknown framework 'python'." Are these following steps(provision, prepare, and execute ) still necessary? I am thinking if it's ok to fail the test the first time it detected an unsupported framework, it is 'discover' step here. 

"
plan failed

The exception was caused by 1 earlier exceptions

Cause number 1:

    execute step failed
    The exception was caused by 1 earlier exceptions
    Cause number 1:
        Unknown framework 'python'.
"

**Comment by idorax** [comment]
Hi @guoguojenna， would you please paste your fmf file then I can give it a try to reproduce this this issue?

**Comment by idorax** [comment]
After talking with @guoguojenna, the fmf file looks like:
```yaml
summary: KS-RDMA-TC:sanity
description: RDMA sanity test
contact: Zhaojuan Guo 
component:
  - rdma
framework: python
test: bash -x ./runtest.sh
duration: 1h
tag:
  - regression
  - functional
tier: 1
```
