### ISSUE TITLE
Allow custom process to implement the `discover` step

### ISSUE THREAD

**Issue by mkoncek** [teemtee/tmt#2256]
## Motivation
As a developer of a custom framework that contains multiple generic tests for many packages, I do not want to maintain a separate `.fmf` [file listing the tests](https://src.fedoraproject.org/fork/mkoncek/tests/javapackages/blob/f39/f/main.fmf). Each test corresponds to a [Java class](https://github.com/mkoncek/javapackages-validator/blob/v2/src/main/resources/META-INF/services/org.fedoraproject.javapackages.validator.Validator) within my framework and it would be much simpler for me to provide a listing of the tests by calling into the custom framework.

## Concerns
Allowing the execution of arbitrary processes from withing the `discover` step on the host machine can obviously be dangerous for the user.

This can be alleviated by allowing to run only containers and with some specified deadline, like 5 seconds.

## Example
```yaml
discover:
  how: custom
  container: quay.io/mkoncek/javapackages-validator
  environment:
    KEY1: value
    KEY2: ${variable} # variable from the current env
  arguments:
  - org.fedoraproject.javapackages.validator.MainTmt
  - discover
 ```
will execute roughly:
`podman run --rm --env KEY1="value" --env KEY2="${variable}" quay.io/mkoncek/javapackages-validator org.fedoraproject.javapackages.validator.MainTmt discover`

## Open questions
* How to pass the output file from the container back to `tmt`?
  1) Implicitly mount some specific directory
      * Danger of dangling large files?
  2) Read the result from the container's stdout
