### ISSUE TITLE
Support fetching git repositories in `prepare` steps

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#2270]
It could be useful to provide an option to fetch a remote git repository so that its content could be used during the `prepare` step execution. It could look like this:

```yaml
prepare:
    how: ansible
    git: https://github.com/teemtee/guest-setup
    playbook: guest-setup/prepare-guests.yaml
```

Might be handy for the `shell` prepare plugin as well:

```yaml
prepare:
    how: shell
    git: https://github.com/teemtee/guest-setup
    script: guest-setup/prepare.sh
```

This could be useful for the common guest setup playbooks use case as well. Thoughts?
