### ISSUE TITLE
`test.environment` is not expanded

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2275]
For example if we want to define the following environment variables:
```yaml
environment:
  GIT_URL: ${PACKIT_SOURCE_URL:-https://github.com/owner/repo}
  GIT_SHA: ${PACKIT_SOURCE_SHA:-${PACKIT_COMMIT_SHA:-main}}
```

This does not work, and instead the values are treated as plain text
