### ISSUE TITLE
Explict plan form

### ISSUE THREAD

**Issue by The-Mule** [teemtee/tmt#2309]
The basic view of a test plan is a list of tests. Let's call it "explicit" plan (everything is expanded). Having it in this form is useful for various reasons. For instance, you might want to run only a subset of tests.  

Real world tmt plans are often using clever tricks in discover step such as tests filtering over multiple repositories, for instance. This looks neat but it bites when you want to do some plan reductions (e.g. you want to run just a subset of tests). Suddenly, you need the "explicit" plan rather than what you have. 

Would it be possible to have a way in TMT to generate this "explicit" for of a test plan? That is, the could be an option for plan command  that would take any TMT plan and generate the same plan but with everything listed out (expanded), all filters applied and so on?

My main motivation is to be able to re-execute the failed tests of a test plan and it would be rather complicated to do so without having a full list of tests of a test plan.

**Comment by psss** [comment]
To clarify, would you like to have the complete list of tests which will/would be executed including all related metadata gathered or you're looking for test names only? Let's see what's currently possible:

```
> tmt run discover --verbose plan --name core
/var/tmp/tmt/run-173

/plans/features/core
    discover
        how: fmf
        directory: /home/psss/git/tmt
        hash: 2a115333
        filter: tier: 0, 1
        summary: 37 tests selected
            /tests/core/adjust
            /tests/core/debug
            /tests/core/docs
            /tests/core/dry
            /tests/core/enabled
            /tests/core/env
            /tests/core/environment-file
            /tests/core/error
            /tests/core/escaping
            ...
```

For the full test metadata we can check the `tests.yaml` file:

```yaml
  - name: /tests/core/adjust
    summary: Verify test/plan adjustments based on context
    description: Perform a basic check using 'tmt test/plan show'.
    enabled: true
    order: 50
    link: []
    id:
    tag:
      - container
      - virtual
    tier: '1'
    contact:
      - Petr Šplíchal <psplicha@redhat.com>
    component: []
    test: ./test.sh
    path: /default-0/tests/tests/core/adjust
    framework: beakerlib
    manual: false
    require:
      - beakerlib
      - tmt
      - tmt-provision-container
    recommend: []
    environment:
        TMT_PLAN_DATA: /var/tmp/tmt/run-173/plans/features/core/data
        TMT_TREE: /var/tmp/tmt/run-173/plans/features/core/tree
        TMT_VERSION: running from the source
    duration: 5m
    result: respect
    where: &id001 []
    serialnumber: 1
    returncode:
    starttime:
    endtime:
    real_duration:
    discover_phase: default-0
  - name: /tests/core/debug
    summary: Verify that options are propagated correctly
    description:
    enabled: true
    ...
```

Which contains all the details.

**Comment by The-Mule** [comment]
I would be interested in the second option. Actually, this `tests.yaml` looks quite promising. But I cannot really re-use it? I mean, I cannot use it as separate test list for the original test plan. Or can I? Can I do the following?

0. Suppose I have a tests-less plan (ie. without explicit discover step).
1. I run the plan from the command line using `discover --how fmf --url ... --filter 'tier:1'`.
2. Something fails, I would take a look at `tests.yaml` in run working directory but I will keep only tests I want to rerun there.
3. I run the plan again but now I would like run to use this reduced `tests.yaml`.

**Comment by psss** [comment]
Actually, the list of tests to be executed is loaded from the `tests.yaml` when you work with the same `tmt` run, so this works nicely already now. Verified using a simple setup:

```yaml
/plan:
    provision:
        how: local
    discover:
        how: fmf
    execute:
        how: tmt

/test:
    test: /bin/true

    /one:
    /two:
    /three:
```

First we run the `discover` step only, then select desired tests and finally continue with the execution:

```
> tmt run --id explicit discover -v
/var/tmp/tmt/explicit

/plan
    discover
        how: fmf
        directory: /tmp/explicit
        summary: 3 tests selected
            /test/one
            /test/three
            /test/two

> vim /var/tmp/tmt/explicit/plan/discover/tests.yaml

> tmt run -v --id explicit --until finish
/var/tmp/tmt/explicit
Found 1 plan.

/plan
    discover
        status: done
        summary: 1 test selected
            /test/one
    provision
        how: local
        guest: localhost
        multihost name: default-0
        arch: x86_64
        distro: Fedora Linux 37 (Workstation Edition)
        kernel: 6.4.13-100.fc37.x86_64
        package manager: dnf
        selinux: yes
        is superuser: no
        summary: 1 guest provisioned
    prepare
        queued push task #1: push on default-0

        push task #1: push on default-0


        summary: 0 preparations applied
    execute
        queued execute task #1: default-0 on default-0

        execute task #1: default-0 on default-0
        how: tmt
            00:00:00 pass /test/one (on default-0) [1/1]

        summary: 1 test executed
    report
        how: display
            pass /test/one
        summary: 1 test passed
    finish

        summary: 0 tasks completed

total: 1 test passed

```
