### ISSUE TITLE
TMT_GUEST[role] is null if how is beaker in multi-host scenario

### ISSUE THREAD

**Issue by linup2011** [teemtee/tmt#2352]
with tmt 1.26.1 (514544b2), when I use beaker for multi-host, the provision as shown:

```yaml
provision:
 - how: beaker
  name: client-1
  role: client
 - how: beaker
  name: server-1
  role: server
execute:
  how: tmt
```

there is no content contained in the variant TMT_GUEST[role]:

```shell
$ cat tmt-test-topology.sh
declare -A TMT_GUEST
TMT_GUEST[name]="server-1"
TMT_GUEST[role]=""
TMT_GUEST[hostname]="dell-per730-20.rhts.eng.pek2.redhat.com"
TMT_GUEST_NAMES="client-1 server-1"
declare -A TMT_GUESTS
TMT_GUESTS[client-1.name]="client-1"
TMT_GUESTS[client-1.role]=""
TMT_GUESTS[client-1.hostname]="dell-pr7610-01.khw2.lab.eng.bos.redhat.com"
TMT_GUESTS[server-1.name]="server-1"
TMT_GUESTS[server-1.role]=""
TMT_GUESTS[server-1.hostname]="dell-per730-20.rhts.eng.pek2.redhat.com"
TMT_ROLE_NAMES=""
declare -A TMT_ROLES
```

more details:

```yaml
$ cat plans/example.fmf
summary: Essential command line features
discover:
 - how: fmf
  test: tests/example
prepare:
 - how: shell
  script:
   - echo test >> "$TMT_TOPOLOGY_BASH"
   - source "$TMT_TOPOLOGY_BASH"
    SERVERS=""
    CLIENTS=""
    export SERVERS="${TMT_ROLES[server]}"
    export CLIENTS="${TMT_ROLES[client]}"
    export
    echo SERVERS="$SERVERS" >> $TMT_TOPOLOGY_BASH
    echo CLIENTS="$CLIENTS" >> $TMT_TOPOLOGY_BASH
provision:
 - how: container
  name: client-1
  role: client
 - how: container
  name: server-1
  role: server
execute:
  how: tmt
```

```shell
$ cat tests/example/test.sh
#!/bin/sh -eux
. "$TMT_TOPOLOGY_BASH"
echo "TMT_GUEST name: ${TMT_GUEST[name]}"
echo "TMT_GUEST role: ${TMT_GUEST[role]}"
echo "TMT_GUEST hostname: ${TMT_GUEST[hostname]}"
export
if [ x"${TMT_GUEST[role]}" == x"server" ]
then
    echo "i_am_server"
    echo "SERVERS:$SERVERS"
elif [ x"${TMT_GUEST[role]}" == x"client" ]
then
    echo "i_am_client"
    echo "CLIENTS:$CLIENTS"
fi
```

```yaml
$ cat tests/example/main.fmf
summary: Concise summary describing what the test does
test: ./test.sh
```
