### ISSUE TITLE
Allow for privilege escalation for tests to enable test portability

### ISSUE THREAD

**Issue by carlosrodfern** [teemtee/tmt#2366]
Some third-party companies or projects may have CI already written with TMT. This creates the opportunity for collaboration between those projects and CentOS Stream CI (for example), by sharing a common place where to host those tests, or simply by porting them over into the redhat/centos-stream project. These can be hundreds of tests.

The Zuul CI system works well with TMT, as it runs the tests with the root users, however those other third-party projects may not be able to login as root in their environment because of security constraints and limitations (e.g. cloud environments like AWS). Basically, the tests are not that cleanly portable as-is.

Many tests may be written with sudo because of those security limitations, e.g.: 
```
test: sudo perf record -F 99 -a -g -- sleep 1
...
test: sudo bpf-biopattern 1 1
```
...but in places like Zuul CI, that is not necessary, so there would be a lot of `sudo` overhead if we run them as-is. So we have to remove the `sudo`s manually:

```
test: perf record -F 99 -a -g -- sleep 1
...
test: bpf-biopattern 1 1
```

I propose an extra configuration in the `connect` provisioner to specify privilege escalation via sudo so that tests can be written in a portable way, so they can be reused as-is in root or sudo settings.

For example,

```yaml
provision:
    how: connect
    guest: hostname or ip address
    user: username
    password: password
# Options: sudo, su, none. Default to sudo. We assume this is always desirable for tests because of portability.
    privilege_escalation: sudo 
```

I'm planning to work on a PR for this unless there is already something in the making.
