### ISSUE TITLE
Aborted test is sometimes reported as a passed test

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#2367]
It seems that `tmt-abort` sometimes does not work as expected when used with the `virtual` provision plugin and reports the abort test with a `pass`. Here's a simple config:

```yaml
/plan:
    provision:
        how: virtual
    discover:
        how: fmf
    execute:
        how: tmt

/test:
    /1:
        test: /bin/true
    /2:
        test: tmt-abort
    /3:
        test: /bin/true
```

Report then looks like this:

```
report
    how: display
        pass /test/1
        pass /test/2
        pass /test/3
    summary: 3 tests passed
```

Adding some `sleep` after the `tmt-abort` command seems to make it working. But didn't have more time to investiage more properly. @pfdaly, could you possibly have a look?
