### ISSUE TITLE
Add files submitted via tmt-file-submit as logs to results

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2398]
Files processed by `tmt-file-submit` - or `rlFileSubmit` - seem to be unreachable through results. They are available in `data` directory, but they are not references. How about adding some kind of list which would then be added to `Result.log`?

**Comment by happz** [comment]
I consider this to be a fairly big gap in reporting. Kicking of with `priority | must`, adding to triage meeting, maybe the priority gets reconsidered.

**Comment by comps** [comment]
A related consideration might be - added to *which* result/report?

What if the user calls 3x `tmt-file-submit` followed by `tmt-report-result` (to report a subresult)? What if the user calls `tmt-report-result` with `-o`?

(I know the TMT interface is just a list of `log` entries, the above is rhetorical. Maybe a small refactor of how CLI scripts handle logs overall might be good, I hit the 1-file limit of the rhts compatibility layer several times now. Even old Beaker HTTP API [supports](https://github.com/RHSecurityCompliance/contest/blob/07f85a5c7fba35b4a90869903be510f9dfbf98fb/lib/results.py#L162-L178) multiple log files per subresult, but restraint also chose to retain the rhts layer.)

**Comment by psss** [comment]
> What if the user calls 3x `tmt-file-submit` followed by `tmt-report-result` (to report a subresult)?

I'd suggest to keep the implementation rather simple: If the `tmt-file-submit` is called, I would add the log file to the main test result, just as an additional log.

> What if the user calls `tmt-report-result` with `-o`?

In this case the `-o` parameter should add the main output of the subresult so this should go (and I believe this is already implemented) to the respective subresult.

> I know the TMT interface is just a list of `log` entries, the above is rhetorical.

The [results specification](https://tmt.readthedocs.io/en/stable/spec/results.html) defines the `log` key for `subresult` as well:

```yaml
subresult:
    # String, name of the test phase.
  - name: First test case

    # String, the effective outcome of the phase execution.
    result: "pass"|"fail"|"info"|"warn"|"error"|"skip"|"pending"

    # String, the original outcome of the phase execution.
    original-result: "pass"|"fail"|"info"|"warn"|"error"|"skip"|"pending"

    # List of strings, optional comments to report with the result.
    note:
      - Things were great.

    # List of strings, paths to log files.
    log:
      - path/to/subresult/log1.txt
      - path/to/subresult/log2.log
        ...
```

So adding support for multiple subresult logs should be possible. I'd rather suggest to cover that in a separate pull request though.
