### ISSUE TITLE
[RFE] Discover step attribute that prevents application of cmdline test name filter

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#2426]
I am requesting to implement discover step attribute that would disable test filter passed from the outside (e.g. command line).
So that with tmt plan like this:
```
discover:
  - name: setup
    disable_test_filter: true
    tests:
      - /setup/part1
      - /setup/part2
  - name: tests
    tests:
      - /sanity/foo
      - /sanity/bar
```
and command line
```
tmt run discover test -n foo
```
I would like to get a test sequence that looks like this
```
/setup/part1
/setup/part2
/sanity/foo
```
