### ISSUE TITLE
tmt lint doesn't check that manually specified test path actually exists

### ISSUE THREAD

**Issue by fernflower** [teemtee/tmt#2428]
If you define a test directly in a plan like 
```
/multiple_nic:
    discover:
      how: shell
      tests:
        - summary: Multiple NIC test
          name: /tests/destructive/multiple_nic
          path: /poc_generator/testcases/multiple_nic
          test: pytest -svv
          duration: 30m
    provision:
      how: artemis
      hardware:
          network:
              - type: eth
              - type: eth
``` 
If the directory specified by `path` doesn't exist - tmt lint won't give you any warning, you will actually learn about it the hard way only after scheduling the test and getting a bunch of errors during execute step.
