### ISSUE TITLE
Add support for ad hoc commands to ansible plugin

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2433]
A possible solution of https://github.com/teemtee/tmt/issues/1279:

> ... there is also a possibility to extend `ansible` plugin to accept ad hoc commands in a way similar to `ansible` *command*, https://docs.ansible.com/ansible/latest/command_guide/intro_adhoc.html. The usage might then look like this:

```yaml
prepare:
  - how: ansible
    module: yum_repository
    module-args:
      baseurl: http://foo.dot.com/some/repo
      description: A repository
      gpgcheck: 1
```

```bash
tmt run ... prepare --insert \
                    --how ansible \
                    --module yum_repository \
                    --module-args "baseurl=http://foo.dot.com/some/repo description=\"A repository\" gpgcheck=1"
```
