### ISSUE TITLE
Editing imported plan does not work on testing-farm

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2446]
Executor: https://github.com/scikit-build/scikit-build-core/pull/518
Imported plan: https://github.com/packit/tmt-plans/pull/7

Could it be a clash with testing-farm's setting of `environment`?

**Comment by thrix** [comment]
@LecrisUT could you bit expand more what is exactly the problem here pls?

**Comment by LecrisUT** [comment]
Hi @thrix. Basically, if we call a tmt plan with:
```yaml
# /plans/rpminspect
plan:
  import:
    url: https://github.com/LecrisUT/tmt-plans
    ref: doc/rpminspect
    name: /plans/rpminspect
environment:
  RPMINSPECT_EXCLUDE: disttag
```
The configuration in `environment` is not picked up when it is being executed on `testing-farm`
