### ISSUE TITLE
Environment variables  TMT_PLUGIN_REPORT_POLARION_* defined in fmf did not take effect

### ISSUE THREAD

**Issue by guoguojenna** [teemtee/tmt#2479]
Hi, 

Here is my plan file:
```
summary: pyverbs-tests-2
prepare:
    how: install
    package: python3-pyverbs
discover:
    how: fmf 
    test:
      - /pyverbs-tests-2
provision:
    how: connect
    guest: rdma-qe-41.rdma.lab.eng.rdu2.redhat.com
    user: root
    password: redhat
execute:
    how: tmt 
environment:
    TMT_PLUGIN_REPORT_POLARION_PROJECT_ID: RHELKNET
    TMT_PLUGIN_REPORT_POLARION_ASSIGNEE: Zhaojuan Guo 
    TMT_PLUGIN_REPORT_POLARION_POOL_TEAM: sst_network_drivers
    TMT_PLUGIN_REPORT_POLARION_ARCH: X86_64
report:
  - name: polarion
    how: polarion
    project-id: RHELKNET

```

The run the plan, $tmt run plans --name /rdma/plans/pyverbs-tests -ddd -vvv

 Actual result: the test run was created, but these fields were empty.
Expected result:  test run was created and these fields(ASSIGNEE, POOL_TEAM, ARCH) are filled in according to the environment variables defined in the fmf file.

**Comment by happz** [comment]
This is a correct behavior. Environment variables like `TMT_PLUGIN_REPORT_POLARION_PROJECT_ID` are providing for fmf keys or command line options - this means they must be set in the environment of the tmt process itself. On the other hand, `environment` sets the environment for tests. These two environments do not overlap in any way, and `environment` cannot affect the tmt process.

**Comment by thrix** [comment]
Yep, I would close this as not a bug.

**Comment by guoguojenna** [comment]
Thanks for the explanation, I had a misunderstanding on it. How can I well define static variables which will be used for most of all plans? Define one time, and use then in many places.

**Comment by guoguojenna** [comment]
The assignee and arch fields were not filled into the polarion test run even I defined them

-  in yaml file
```
$ cat env_polarion.yaml 
TMT_PLUGIN_REPORT_POLARION_PROJECT_ID: RHELKNET
TMT_PLUGIN_REPORT_POLARION_ASSIGNEE: Zhaojuan Guo 
TMT_PLUGIN_REPORT_POLARION_POOL_TEAM: sst_network_drivers
TMT_PLUGIN_REPORT_POLARION_ARCH: x86_64

environment-file:
  - rdma/plans/env_polarion.yaml

report:
  - name: polarion
    how: polarion
    project-id: $TMT_PLUGIN_REPORT_POLARION_PROJECT_ID
    pool-team: $TMT_PLUGIN_REPORT_POLARION_POOL_TEAM
    assignee: $TMT_PLUGIN_REPORT_POLARION_ASSIGNEE
    arch: $TMT_PLUGIN_REPORT_POLARION_ARCH
```
- or  in the fmf environment
```
environment:
    TMT_PLUGIN_REPORT_POLARION_PROJECT_ID: RHELKNET
    TMT_PLUGIN_REPORT_POLARION_ASSIGNEE: "Zhaojuan Guo" 
    TMT_PLUGIN_REPORT_POLARION_POOL_TEAM: sst_network_drivers
    TMT_PLUGIN_REPORT_POLARION_ARCH: x86_64
report:
  - name: polarion
    how: polarion
    project-id: $TMT_PLUGIN_REPORT_POLARION_PROJECT_ID
    pool-team: $TMT_PLUGIN_REPORT_POLARION_POOL_TEAM
    assignee: $TMT_PLUGIN_REPORT_POLARION_ASSIGNEE 
    arch: $TMT_PLUGIN_REPORT_POLARION_ARCH
```
- or in the plan report part directly
```
report:
  - name: polarion
    how: polarion
    # here
    assignee: "Zhaojuan Guo" 
```
- or set env in command line like
 "tmt run -e TMT_PLUGIN_REPORT_POLARION_ARCH="x86_64" plans --name /rdma/plans/pyverbs-tests -ddd -vvv"
```
report:
  - name: polarion
    how: polarion
    project-id: $TMT_PLUGIN_REPORT_POLARION_PROJECT_ID
    pool-team: $TMT_PLUGIN_REPORT_POLARION_POOL_TEAM
    assignee: $TMT_PLUGIN_REPORT_POLARION_ASSIGNEE 
    arch: $TMT_PLUGIN_REPORT_POLARION_ARCH
```
