### ISSUE TITLE
`plans.import` save the `TMT_TREE` of all imported plans

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2572]
The idea is to have a structure as follows:
```console
$ tree -L 1
/plans/.../
├── data
├── discover
├── execute
├── finish
├── prepare
├── provision
├── report
└── tree
    ├── 0
    ├── 1
    └── 2
```
Where we save all of the `tmt.tree` of the callers for `plans.import` (assuming we could call it recursively at some point). The numbering goes from `0`: the top-most plan that it is being called, and then each `plans.import` increases the index. Then for navigability expose:
- `TMT_TREE` points to the currently active `TMT_TREE`
- `TMT_TREE_ROOT` points to `${TMT_TREE}/..`
- `TMT_CURRENT_DEPTH`: the current index
- `TMT_TREE_ROOT` should be mounted instead of `TMT_TREE`

This is related with the ideas in #2340

**Usecase:**
This is part of my attempts at writing an [`rpmlint` reusable plan](https://github.com/packit/tmt-plans/tree/main/plans/rpmlint). The issue there is that the `.rpmlintrc` files would only be accessible from the caller's git repo, so we need a way to access this caller's data. Enabling this structure should be a quick fix for these kind of issues.

**Potential issues:**
- Name confusion as it can be confused with the `fmf` tree navigation
- Plain numbering of the depth could be a bit jarring, but it would also be the simplest to manipulate in bash

**Comment by psss** [comment]
Each imported plan has its own directory including the `tree` which contains the full git repo content. Let's have the following example:

```yaml
/one:
    plan:
        import:
            url: https://github.com/teemtee/tests
            name: /plans/remote

/two:
    plan:
        import:
            url: https://github.com/teemtee/tests
            name: /plans/remote
```

After running both remote plans we get this in the run workdir:

```
├── plan
│   ├── one
│   │   ├── cleanup
│   │   ├── data
│   │   ├── discover
│   │   │   └── default-0
│   │   ├── execute
│   │   │   ├── data
│   │   │   └── default-0
│   │   ├── finish
│   │   ├── prepare
│   │   ├── provision
│   │   │   └── default-0
│   │   ├── report
│   │   └── tree
│   │       ├── nested
│   │       ├── plans
│   │       ├── requre
│   │       ├── scripts
│   │       ├── setup
│   │       └── tests
│   └── two
│       ├── cleanup
│       ├── data
│       ├── discover
│       │   └── default-0
│       ├── execute
│       │   ├── data
│       │   └── default-0
│       ├── finish
│       ├── prepare
│       ├── provision
│       │   └── default-0
│       ├── report
│       └── tree
│           ├── nested
│           ├── plans
│           ├── requre
│           ├── scripts
│           ├── setup
│           └── tests
```

So... is there actually anything needed?

**Comment by LecrisUT** [comment]
This one is about navigating through the callers of `plan.import`. E.g.
```yaml
plan:
  import:
    url: https://github.com/uesr/foo
    name: /some/plan
environment:
  SPEC_FILE: path/to/spec_file
```
where `SPEC_FILE` could be an input required by the plan where the file is located on the original repo's tree. If we use remote tests we can get around this issue by placing these in a predictable place in the plan's workdir, but we don't have an equivalent for plans.

With remote scripts this issue is partially solved, but still the required user setup is quite clunky.
