### ISSUE TITLE
replace/update the steps of remote plan

### ISSUE THREAD

**Issue by guazhang** [teemtee/tmt#2600]
when reuse some steps of the remote plan, but other steps need be replaced or updated.
so could we plan to support it ?

remote plan A:
 
```
summary:  this is remote plan
discover:
    how: fmf
    filter: "tag: t1"
provision:
    how: minute
    image: rhel-8
execute:
    how: tmt

```
plan B reuse the remote plan and need update the `provision` step 

```
provision:
    how: beaker
    image: rhel-9
```

**Comment by psss** [comment]
So, for the first implementation we agreed upon this:

    Plan steps must not be defined in the remote plan reference.
    The imported plan can be modified in only two ways. First way
    is via environment and context variables.

I guess, the extension is possible, the whole remote plan config then could look like this:

```yaml
/some-plan:
    context:
        ...
    environment:
        ...
    plan:
        import:
            ...
            inherit-context: false
            inherit-environment: false
    prepare:
        how: install
        package: different-package
```

Would the expectation be to only support overriding the remote plan steps? Or also extending like this?

```yaml
prepare+:
    how: install
    package: different-package
```

@guazhang, do the above-mentioned example match your expectations?
