### ISSUE TITLE
Pull `TMT_PLAN_DATA` at the end of the `finish` step

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#2681]
Use case: run script in `finish` which writes data to `$TMT_PLAN_DATA` and use `login` (`tmt run -a login`)

We need to 'pull' data before login 'push' or keep existing data on the guest. Currently the 'login' deletes everything produced by finish (as no pull happens before)

**Comment by psss** [comment]
Sounds like we just need to add `guest.pull()` at the end of the `finish` step. Reproducible easily with the following plan:

```yaml
provision:
    how: virtual
execute:
    how: tmt
    script: /bin/true
finish:
    script: echo hi > $TMT_PLAN_DATA/message
```

And this command:

```
tmt run -vvv login --command 'cat $TMT_PLAN_DATA/message'
```

Adding to the backlog.
