### ISSUE TITLE
Filter in the upgrade path plan is ignored

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#2704]
While creating reproducer for #2643 .. The filter of upgrade path plan is ignored...

There is not task (test) marked with 'tag:upgrade' but `tmt run -avvv plans -n parent` still runs `task-beakerlib` as part of the upgrade.

Behaviour doesn't change after `task-beakerlib` has `tag: upgrade` added and new (not tagged) tmt test is added to the repo - in such case both tests are run.

```sh
tmt init

cat > parent.fmf <<EOF
discover:
    how: shell
    tests:
    - name: foo
      test: echo

provision:
    how: container      
execute:
    how: upgrade
    path: upgrade-path
EOF

cat > task-beakerlib.fmf <<EOF
framework: beakerlib
test: |
    . /usr/share/beakerlib/beakerlib.sh || exit 1
    rlJournalStart
       rlPhaseStartTest 
            rlPass "yes"
      rlPhaseEnd
    rlJournalEnd
EOF

cat > upgrade-path.fmf <<EOF
discover:
    how: fmf
    filter: "tag:upgrade"
execute:
    how: tmt
EOF
```

**Comment by psss** [comment]
@lukaszachy, isn't the problem here with a wrong `path` key?

```
> tmt
Found 1 test: /task-beakerlib.
    warn: /parent:execute - {'how': 'upgrade', 'path': '/upgrade-path'} is not valid under any of the given schemas
Found 2 plans: /parent and /upgrade-path.
```

With the `upgrade-path` key used in `parent.fmf` instead of `path`:

```yaml
discover:
    how: shell
    tests:
      - name: foo
        test: echo

provision:
    how: container

execute:
    how: upgrade
    upgrade-path: /upgrade-path
```

It seems to be working as expected (no upgrade task is run).
