### ISSUE TITLE
Support additionas to context made by adjust rules for follow-up rules

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2706]
```yaml
adjust:
  - when: distro == rhel-9
    context+:
      llvm: 19

  - when: llvm == 19
    ...
```

Since fmf does not recognize `context`, this might need a combined effort of tmt and tmt, e.g. fmf accepting a callback updating context, or a list of keys affecting context...

No idea how messy this can get. Plus, I recall seeing similar questions in the past, there might be issues with discussions somewhere. Yet, it might be nice to give it a more thought.
