### ISSUE TITLE
bug: `plan.import` uses consumer's git path instead of consumed project's

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2737]
Doesn't work for me with `path: .`

My testing plan is 
```
plan:
    import:
        url: file:////tmp/r_150917_X8i/tmt
        ref: tag-beakerlib-tests
        path: /plans/friends
        name: /beakerlib
```

The file:////tmp/r_150917_X8i/tmt is git repo with commited `beakerlib.fmf` containing
```
discover:
    how: fmf
    path: .
    filter: "tag:beakerlib&tag:-provision-only"
```

But the `tmt run discover` ends with 0 tests selected. From the log it seems that it copied '.' but it was the parent plan's cwd.

_Originally posted by @lukaszachy in https://github.com/teemtee/tmt/issues/2731#issuecomment-1978877924_
