### ISSUE TITLE
Always prepend discover phase name to test name

### ISSUE THREAD

**Issue by The-Mule** [teemtee/tmt#2768]
Consider the following discover phase:

```
discover:
    - how: fmf
      url: <url1>
      name: libgcrypt
      test: /sanity/selftest
```

If there is just this single discover phase in this plan there will be `/sanity/selftest` in the reports. On the other hand if we add one more discover phase:

```
discover:
    - how: fmf
      url: <url2>
      name: stunnel
      test: /sanity/selftest
```

then there will be `/libgcrypt/sanity/selftest` and `/stunnel/sanity/selftest` in the results. It is because of this [conditional expression](https://github.com/teemtee/tmt/blob/632f2913c06525e376053bf908e1cc53b8e0b075/tmt/steps/discover/__init__.py#L318). It might look fine but suppose you have two plans - each with just a single discover phase, you run them and report them to the  Report Portal and merge their launches. You will end-up with two test of the same name there.

Hence I would like to propose to always prepend the phase name regardless or the number of discover phases in a plan.
