### ISSUE TITLE
Implement device.driver for Beaker plugin

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2820]
Motivated by the need to provision a machine with USB, "key values from beaker provision of USB controller could be request via specifying `MODULE=ahci OR MODULE=uhci`"

The corresponding request in tmt lingo:

```yaml
hardware:
  or:
    - device:
        driver: ahci
    - device:
        driver: uhci
```

```yaml
hardware:
  device:
    driver: .*hci
```

Should translate in Beaker to `MODULE` filter.
