### ISSUE TITLE
Testing Farm provision crash after tmt-reboot

### ISSUE THREAD

**Issue by Koncpa** [teemtee/tmt#2832]
When it's used tmt connect to TF machine and running test suites contain tmt-reboot, machine crash after some time from reboot. Just happened in case, when is provisioned machine by TF. 

Steps to reproduce.
1. Reserve TF machine - `$ testing-farm reserve --compose Fedora-Rawhide --ssh-public-key /home/user/.ssh/id_rsa.pub --arch x86_64 --duration 720`

3. create in initialized `.fmf` dir  corresponding plan `reproducer_plan.fmf`

```
summary:
  Reproducer plan

prepare:
  - how: shell
    script:
     - dnf install -y grubby --allowerasing


discover:
  how: fmf
  url: https://github.com/RedHat-SP-Security/keylime-tests
  ref: main
  test:
   - /setup/configure_swtpm_device
   # test with tmt reboot, ima setup and reboot
   - /setup/configure_kernel_ima_module/ima_policy_simple
   #
   - /functional/

execute:
    how: tmt
```

3. run plan via `tmt --context distro=Fedora-rawhide run plan --name reproducer prepare discover -h fmf -vv provision -h connect -g IP -u root execute --how tmt --interactive login finish
`
