### ISSUE TITLE
plan: Caching capability

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2847]
The idea is to have a similar feature to GH action cache where the user and action/tmt author are in charge of cache management. E.g. cache `venv` file with the key from `pyproject.toml`

### Implementation: As a prepare/finish step plugin

This is the most straight-forward implementation

**Pros:**
- More control on how it interacts with other prepare/finish steps
- Cache keys can be dynamic, e.g. depending on some artifacts of the prepare step

**Cons:**
- Harder to manage via CLI (may need the execution of previous prepare steps)

### Implementation: As a dedicated phase

Could be a phase just after `provision`, but before `prepare`

**Pros:**
- Easier to manage via CLI
- Cache keys are available statically

**Cons:**
- Cannot use any artifacts from prepare phase
- Could interfere with multi-host setup

### Provider's implementation

The provider could their own plugin to the cache plugin to provide their interface, e.g.:

#### Local provider

Under `/var/tmp/tmt` have a `cache` folder location with hashes of the cache key. Than mount/symlink the cache folder in the appropriate location, making sure it is read-only. Do the opposite if no cache key is found, and write a cache folder after the finish step

#### Other providers

Use the same principle for local provider, but before/after tmt execution load/save the cache, e.g. for github action [load/save](https://github.com/actions/toolkit/tree/main/packages/tool-cache#find) the cache. The issue is that the cache keys that need to be fetched must be made available before the tmt execution. So depending on the implementation used, this can either be queried via `tmt` cli, like a `tmt plans show`, or the provider would write a plugin such that these steps are executed within the tmt plan execution itself.

**Comment by LecrisUT** [comment]
Some examples of what would use cache storage:
- python `venv` environments in a `prepare` step
- ctest test costs in a `execute` plan step or `test` framework
- copr build times of dependencies in a `discover` plan step (e.g. for selecting a few random quick builds to reverse-dependency test)

**Comment by psss** [comment]
@LecrisUT, what about giving a short intro about the idea on the hacking session?

**Comment by LecrisUT** [comment]
To take the github actions caching as a comparison, a typical workflow for a python project can look like this:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache action
      uses: actions/cache@v4
      with:
        path: $HOME/.cache/pip
        key: pip-${{ hashFiles('pyproject.toml') }}
     
    - run: pip install .

#    - name: Post cache action (injected by Cache action)
#      run: upload-cache-to-github
```
The key functionality of "Cache action" is:
- Check for the presence of key in the cache storage. The key must be able to hash file contents
- If present, extract the content in the provided `path`
- Subsequent steps make use of the cache being in the right location
- Inject a Post cache action at the end
- If the key was not present, archive and upload the contents of `path` to the cache server

---

In tmt language, we can make an equivalent design
```yaml
prepare:
  - how: cache
    path: $HOME/.cache/pip
    key-files: pyproject.toml
    key-prefix: pip-
  - how: shell
    script: pip install .
# finish:
#   - name: Post cache action (injected by the prepare step)
#     how: post-cache
```
The functionality would go like
- Check for the presence of directory/archive `pip-$(sha256sum $key-files)` under `run-workdir`
- If present, copy/extract the content in the provided `path`
- Inject a Post cache finish step
- If the key was not present, copy/archive the contents of `path` and put them under `run-workdir`
- Depending on some global option choose an appropriate provider to extend these and upload to a network storage for testing-farm users
