### ISSUE TITLE
--fmf-id doesn't work with multiple configs in discover

### ISSUE THREAD

**Issue by Athwale** [teemtee/tmt#2863]
I run into this problem:
```
tmt run discover --how fmf --fmf-id
/var/tmp/tmt/run-102

/all-plan

plan failed

The exception was caused by 1 earlier exceptions

Cause number 1:

    Step 'discover' has multiple plugin configs which require running on their own. Combination of such configs is not possible.
```

The all-plan.fmf I am using contains many lines like this:
```
summary: Selects all tests from internal and public repositories.
discover:
  - name: upstream_autogen_0
    how: fmf 
    url: https://src.fedoraproject.org/tests/autogen.git
  - name: upstream_guile_0
    how: fmf 
    url: https://src.fedoraproject.org/tests/guile.git
  - name: upstream_geolite2_0
    how: fmf 
    url: https://src.fedoraproject.org/tests/geolite2.git
execute:
    how: tmt
```
