### ISSUE TITLE
`test.require` does not work with `context.distro`

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/tmt#2905]
In a test's fmf file I was trying:
```yaml
require:
  - python3-pytest
  - python3-pytest-check
  - python3-flexmock
test: python3 -m pytest

adjust:
  when: distro == ubuntu
  require-:
    - python3-pytest-check
    - python3-flexmock
```
But this does not seem to work: https://github.com/LecrisUT/tmt-cmake/pull/6

It doesn't seem to be the syntax since the same `when: distro == ubuntu` is in the tests with the `prepare`. But `discover` is done even before `provision` so there is no valid context for `distro` to be able to be used at that point.
