### ISSUE TITLE
Replace "plan+import" keys in favor of "import-plan"

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#2964]
It spurred as a quest to slightly improve readability of structure importing a plan:

```yaml
/myplan:
  plan:
    import:
      url: ...
```

There is a plan, called `/myplan`, and it contains a `plan` key, apparently duplicating the plan-ness of the entity. `plan` key is now necessary, because there is no `execute` which is used to identify plans, and `plan` key presence is used instead.

The `plan` key is slightly puzzling, we encountered the question fo where `adjust` should be placed:

```yaml
# In /myplan?
/myplan:
  plan:
    import:
      url: ...
  adjust:
    ...

# Or in plan?
/myplan:
  plan:
    import:
      url: ...
    adjust:
      ...
```

The first idea was to drop `plan` and promote `import` one level up. As shown above, `plan` serves as an anchor identifying plans: as briefly discussed, `tmt plan ls --shallow` would not work without it, even though we might open door to importing other entities, tests and stories - do we want to add support for that?

So, maybe dropping `plan` and moving `import` one level up is probably not as hairless as it might look, and has side-effects, how about dropping `plan`, moving `import` one level up **and** renaming it to `import-plan`? It would still serve as an anchor, we would be able to tell plans from other entities, we would remove one nested level in fmf files, and we can support both keys for some time, deprecating `plan` now and remove it in 2028 or something:

```yaml
# In /myplan?
/myplan:
  import-plan:
    url: ...
  adjust:
    ...
```

**Comment by LecrisUT** [comment]
My reading  w.r.t. `adjust` is that the first case adjusts the plan import itself, e.g.:
```yaml
/myplan:
  plan:
    import:
      url: ...
      ref: main
  adjust:
    when: distro == centos
    plan+:
      import+:
      ref: centos
```
And the second case would adjust the plan itself similar to the planned `adjust-tests` in `discover`:
```yaml
/myplan:
  plan:
    import:
      url: ...
    adjust-plan:
      when: distro == centos
      prepare+:
        - how: install
           ...
```

Currently the latter is not implemented afaik, but maybe it should have a similar naming scheme.

W.r.t. `plan` vs `import-plan` probably both formats can be structured to be more intuitive, e.g. `plan.adjust-plan` and `import-plan.adjust` (since `import-plan.adjust-plan` looks a bit much).

---

Also worth considering the original idea of [grafting](https://github.com/teemtee/fmf/issues/99) in fmf. I think having such a feature on `fmf` itself is also feasible.

**Comment by psss** [comment]
Another option could also be (if we are sure that there will not be any additional keys needed under the parent key) to just drop the `import` key and place the information about the remote plan directly into the parent:

```yaml
/some-plan:
    plan:
        url: ...
        name: ...
        ref: ...
        path: ...
```

This would also provide a backward compatible way / fluent transition: If the `import` is there, pick the data from it, if not take it directly from `plan`.
