### ISSUE TITLE
`remote_user` ansible key not working when ansible playbook is called by tmt

### ISSUE THREAD

**Issue by majamassarini** [teemtee/tmt#2965]
If I run the ansible playbook below in the `prepare` step of a locally virtual provisioned tmt machine I always get `root` as an output.

```
[...]
  prepare:
    - how: shell
      script: 'adduser -m packit'
    - how: ansible
      playbook: whoami.yml
      extra-args: '-vvv'
```
```
---
- name: whoami
  remote_user: packit
  hosts: all
  tasks:
    - name: Whoami
      ansible.builtin.command: whoami
      changed_when: False
```

If I change the `remote_user` key with the `become_user` key then I get the `packit` user. 
Unfortunately I can't use the `become_user` directive because I need a full working systemd environment for the `packit` user and this could be achieved logging into `packit` directly through ssh.
