### ISSUE TITLE
Is tmt plan import doing the actual import too early?

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#2968]
I was trying to add a condition around a test plan import but it didnt' work as expected.
E.g. this example with bogus url produces `git clone` error despite the plan being disabled.

```
/keylime-e2e:
  plan:
    import:
      url: hhttps://github.com/RedHat-SP-Security/keylime-plans.git
      name: /generic/minimal-e2e
  enabled: 0

$ tmt -c distro=rhel-10 run discover 
/var/tmp/tmt/run-015
    warn: /ci/keylime-e2e:enabled - 0 is not of type 'boolean'
fail: Command 'git clone hhttps://github.com/RedHat-SP-Security/keylime-plans.git /var/tmp/tmt/run-015/import/ci/keylime-e2e' returned 128.
```
Maybe the above is expected. I basically wanted to avoid fetching an internal URL for distros like Fedora or CS. For now I ended up with this which seems to work but looks unnecessarily complicated
```
/keylime-e2e:
  enabled: 0

  adjust:
   - when: distro == rhel
     enabled: 1
     plan:
      import:
        url: hhttps://github.com/RedHat-SP-Security/keylime-plans.git
        name: /generic/minimal-e2e
```
I am wondering if there is effectively any difference between these two approaches when the 1st one is doing the import early while the later one late. I can imagine that the imported plan may have also some adjust rules impacting plan status.
