### ISSUE TITLE
Check `context` in `tmt lint`

### ISSUE THREAD

**Issue by comps** [teemtee/tmt#2976]
I was rather surprised to see `tmt lint` pass:
```
/example-test
pass C000 fmf node passes schema validation
warn C001 summary key is missing
pass T001 correct keys are used
pass T002 test script is defined
pass T003 directory path is absolute
pass T004 test path '/home/comps/tmt-experiments/example-test' does exist
skip T005 legacy relevancy not detected
skip T006 legacy 'coverage' field not detected
skip T007 not a manual test
skip T008 not a manual test
skip T009 library/file requirements not used
```
while using
```
test: ./test.sh
adjust:
  - when: distro == rhel-7 || distro == centos-7
    enabled: false
```
because `||` is not a valid operator according to https://fmf.readthedocs.io/en/stable/context.html#context and the condition is silently ignored.
