### ISSUE TITLE
The prepare+ part in the child plan does not take effect when using adjust 

### ISSUE THREAD

**Issue by guoguojenna** [teemtee/tmt#3006]
When using adjust in tmt test plan, for example,

this is the parent plan
```
adjust:
 - when: distro == rhel-10
   prepare:
	……
```
This is a child plan,
```
prepare+:
 - how: install
   package: libiscsi-utils
   ……
```

When run `tmt run -c distro=rhel-10…`, the prepare+ part in the child plan does not take effect. Is it reasonable to append the prepare+ part in the child plan to the parent adjust prepare?

**Comment by lukaszachy** [comment]
What means `child`  here? Imported plan?

**Comment by guoguojenna** [comment]
> What means `child` here? Imported plan?

Sorry for the misunderstanding. My test structure is like this:

```
$ tree
.
├── iscsi
│   ├── libiscsi
│   │   └── main.fmf
├── main.fmf
```
The main.fmf under ./iscsi/libiscsi is the child and main.fmf under ./ is the parent here.

**Comment by psss** [comment]
The `adjust` rule provided above overrides the `prepare` step config. If you want to extend, you should use `prepare+` instead. Confirmed to be working as expected:

> cat main.fmf

```yaml
execute:
    how: tmt

adjust:
  - when: distro == rhel-10
    prepare+:
      - how: install
        package: some-other-package
```

> cat iscsi/libiscsi/main.fmf 

```yaml
prepare+:
  - how: install
    package: libiscsi-utils
```

Combines both parent and child:

```
> tmt -c distro=rhel-10 plan show
/iscsi/libiscsi
                 prepare 
                     how install
                 exclude 
                    when 
               directory 
                 package libiscsi-utils
                   where 
                 missing fail
                    copr 
                 prepare 
                     how install
                 exclude 
                    when 
               directory 
                 package some-other-package
                   where 
                 missing fail
                    copr 
             environment TMT_VERSION: 1.59.0.dev5+ged6eb2b70
                 context distro: rhel-10
                 enabled true
```

@guoguojenna, can you confirm this is working for you?
