### ISSUE TITLE
The `feature` plugin for `epel` does not work on command line

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#3032]
Seems that the `feature` plugin for `epel` is broken when called from the command line:

    tmt run provision --how container --image centos:stream9 prepare --how feature --epel enabled login finish

Results into:

    prepare
        prepare task #1: default-0 on default-0
        how: feature
        Enable EPEL
        fail: 

Works nicely when provided as a plan:

```yaml
provision:
    how: container
    image: centos:stream9
prepare:
  - how: feature
    epel: enabled
  - how: install
    package: beakerlib
execute:
    how: tmt
    script: rpm -q beakerlib
```
