### ISSUE TITLE
tmt run failed  if no "keyname" is specified for artemis 

### ISSUE THREAD

**Issue by skycastlelily** [teemtee/tmt#3089]
(dev) lnie@fedora:~/tmt$ tmt run plans --name plans/artemis$
/var/tmp/tmt/run-001
*****

            Connection: close
            content-length: '37'
            
            message: No such SSH key exists
    finish
        warn: Nothing to finish, no guests provisioned.

**Comment by skycastlelily** [comment]
We should change DEFAULT_KEYNAME from 'default' to 'master-key', which  is the default key name for artemis server,and without it artemis server won't be able to start,so users won't see the error above forever:)

**Comment by psss** [comment]
Could you please provide the example plan to reproduce this?

**Comment by skycastlelily** [comment]
sure, here is the plan

```
summary: Basic smoke test
provision:
    how: artemis
    # Specify the Artemis URL where the service is running.
    # Here is an example of a local Artemis instance
    api-url: "http://127.0.0.1:8001/v0.0.58"
    api-version: "0.0.58"
    image: fedora-42
    arch: x86_64
    pool: beaker
    #keyname: master-key
```
