### ISSUE TITLE
Require a `beakerlib` library using a relative path

### ISSUE THREAD

**Issue by jencce** [teemtee/tmt#3101]
To support something like this:

```
# Library from the local filesystem
require:
  - type: library
    path: ../library/openssl
    name: /certgen
```

To source a library from the same git repo with the test.

Now tmt supports using absolute path, which is working when tmt running from local but has limitation when trying to run on a remote environment, for example testing-farm. The absolute path varies on different systems, but the relative path stays the same within the git repository.
