### ISSUE TITLE
Export `TMT_SOURCE_DIR` in prepare/finish steps as well

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#3124]
Use case for 'prepare' is to be able to run 'autotools' with patches sources (eg. when it creates helper test executables)  and leave 'discover' to just specify the tests.

Current workaround is to have this 'autotools' action as part of the very first test, which makes it problematic for 'run just a single test' (`tmt run tests -n name`)

There is no clear use case for finish, but it shouldn't hurt to have that variable there  as well.

**Comment by CtrlZmaster** [comment]
I ran into this while trying to use `dist-git-source: true` and then use autotools on the extracted and patched sources. If `TMT_SOURCE_DIR` was exported in prepare, the following should work:
gating.fmf:
```yaml
summary: PCS gating test plan
description: Runs upstream tier0, tier1 and smoke tests

discover:
    dist-git-source: true
    dist-git-install-builddeps: true
    how: shell
    tests:
        - name: tier0
          test: $TMT_SOURCE_DIR/pcs-*/pcs_test/suite --tier0 -v --vanilla --installed
          duration: 10m
          tier: 0
          tag: fast
        - name: tier1
          test: $TMT_SOURCE_DIR/pcs-*/pcs_test/suite --tier1 -v --vanilla --installed
          duration: 2h
          tier: 1
        - name: smoke
          test: |
              systemctl start pcsd
              $TMT_SOURCE_DIR/pcs-*/pcs_test/smoke.sh
          duration: 10m
          tier: smoke
          tag: fast

prepare:
    - how: shell
      script: ./prepare-tests.sh
      order: 70

execute:
    how: tmt
```
prepare-tests.sh:
```shell
set -eo xtrace
cd $TMT_SOURCE_DIR
# RPM 4.20 changed the builddir structure - unpacked sources go to *-build but
# tmt copies them back to pcs-*, so the pcs-*-build folder is empty
# Remove pcs-web-ui, pcs-*-build for "cd pcs-*" to have exactly one match
rm -rf pcs-web-ui-* pcs-*-build
cd pcs-*/
# Run autotools, use bundled dependencies from the system
export PYTHONPATH=/usr/lib/pcs/pcs_bundled/packages/
export GEM_HOME=/usr/lib/pcsd/vendor/bundle/
# We need to use cd pcs-* because when pcs-web-ui starts using autotools, running
# autogen and configure with expanded TMT_SOURCE_DIR will match that too
./autogen.sh
./configure --enable-local-build --enable-use-local-cache-only \
  --enable-individual-bundling --with-pcs-lib-dir=/usr/lib
# Remove pcs sources to make sure tests are not using any of those files
rm -rf pcs
```
This currently fails with:
```
        Command '/var/tmp/tmt/run-009/gating/tree/tmt-prepare-wrapper.sh-default-0-default-0' returned 1.

        stderr (4 lines)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        +++ cd
        +++ rm -rf 'pcs-web-ui-*' 'pcs-*-build'
        +++ cd 'pcs-*/'
        ./prepare-tests.sh: line 7: cd: pcs-*/: No such file or directory
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
You can see that there was a plain `cd` which started an unfortunate chain of events. This was caused by `$TMT_SOURCE_DIR` not being exported during `prepare`.
