### ISSUE TITLE
Test discovery fails when `path` is used with `prune`

### ISSUE THREAD

**Issue by dracher** [teemtee/tmt#3131]
How to reproduce

```
- discover:
    - name: external
      how: fmf
      prune: True
      url: https://github.com/eclipse-bluechi
      ref: main
      path: tests
```

Error:
it try to locate resources

`[Errno 2] No such file or directory: '/var/tmp/tmt/run-001/bluechi/plans/tests/discover/external/tests/tests/tier0/...`

but the actual path is 
`/var/tmp/tmt/run-001/bluechi/plans/tests/discover/external/tests/tests/tests/tier0/...`
