### ISSUE TITLE
bug: tmt try multihost plan breaks terminal

### ISSUE THREAD

**Issue by spetrosi** [teemtee/tmt#3138]
After running a plan with multi-host provisioning with 3+ hosts, terminal "breaks", it prints many spaces in the beginning of the lines, and then doesn't work. With two nodes, the output is fine. With >3 nodes, it starts shifting.

Plan from plans/test_plan.fmf:

```
summary: A general test for a system role
tag: general_test
provision:
  - name: control_node
    role: control_node
    connection: system
  - name: managed_node1
    role: managed_node
    connection: system
  - name: managed_node2
    role: managed_node
    connection: system
  - name: managed_node3
    role: managed_node
    connection: system
environment:
    ANSIBLE_VER: 2.17
    REPO_NAME: "mssql"
    PYTHON_VERSION: 3.12
prepare:
  # Replace with feature: epel: enabled once https://github.com/teemtee/tmt/pull/3128 is merged
  - name: Enable epel to install beakerlib
    script: |
      # CS 10 and Fedora doesn't require epel
      if grep -q -e 'CentOS Stream release 10' -e 'Fedora release' /etc/redhat-release; then
        exit 0
      fi
      yum install epel-release yum-utils -y
      yum-config-manager --enable epel epel-debuginfo epel-source
discover:
  - name: Prepare managed nodes
    how: fmf
    url: https://github.com/linux-system-roles/tft-tests
    ref: main
    where: managed_node
    filter: tag:prep_managed_node
execute:
    how: tmt
```

I am running it with 

`tmt try -p plans/test_plan centos-stream-9`

What my terminal outputs: https://pastebin.com/Ae18humU

Terminal breaks after `Running 'rlImport library'` line

**Comment by spetrosi** [comment]
```
$ tmt --version
tmt version: 1.34.0
```

**Comment by spetrosi** [comment]
I am providing a simpler reproducer, a plan that provisions 3 nodes, and a simple test. It enough to create two files like below and run `tmt try -p plans/reproducer`.

`plans/reproducer.fmf`:
```
summary: Reproduce bug with extra indentation
provision:
  - name: control_node
    role: control_node
  - name: managed_node1
    role: managed_node
  - name: managed_node2
    role: managed_node
discover:
  - name: Run on 3 managed nodes
    how: fmf
    where: managed_node
    filter: tag:reproducer
  - name: Run on control node
    how: fmf
    where: control_node
    filter: tag:reproducer
execute:
    how: tmt

```

`tests/reproducer/main.fmf`:
```
summary: Print date for test purposes
framework: shell
duration: 1m
tag: reproducer
test: date
```

I noticed what exactly causes this - using `where` keyword to specify a role that has more than 2 nodes.

This issue blocks work on multi-node scenarios that use more than 2 nodes.
