### ISSUE TITLE
Add support for `environment` keyword in discover step for running tests with different arguments

### ISSUE THREAD

**Issue by adiosnb** [teemtee/tmt#3160]
# Feature Request

We propose adding an `environment` keyword in the discover step to enable running the same test with different arguments across multiple environments. This feature would enhance the flexibility of test configurations, making it easier to dynamically generate and modify test plans.

## Background

This feature is particularly useful for users migrating from Restraint, where similar functionality is often required. Currently, it is possible to include parameters directly within the test and filter specific tests for specific hosts. However, this approach is insufficient for scenarios where test plans need to be dynamically generated or modified. The current method lacks flexibility, especially when dealing with complex test environments or when running the same test across various configurations.

The need for this feature arose from discussions about running tests with different arguments in a more streamlined and automated manner, without the redundancy of creating multiple discover steps or manually adjusting configurations.

## Proposed Syntax

Here is an example of the proposed syntax (with random values used to avoid any sensitive information):

```yaml

/test-suite:
  discover+:
    - how: fmf
      order: 10
      url: https://gitlab.example.com/project/repo
      test:
        - /test_case
      environment:
        TESTCASE_PARAMS: --label RANDOM_LABEL_1 --option1 --option2 RANDOM_TEST_1 --filesystem random_fs --other-param 12345 --size 50g --runtime 1m

    - how: fmf
      order: 20
      url: https://gitlab.example.com/project/repo
      environment:
        TESTCASE_PARAMS: --label RANDOM_LABEL_2 --optionA --optionB RANDOM_TEST_2 --raid-level random_raid --filesystem random_fs_2 --rw optionX --size 25g
      test:
        - /test_case
```

## Current Limitation

The current method allows adding parameters directly to tests and filtering them by host, which works for static test plans. However, this is inadequate for dynamically generated and modified test plans where flexibility and automation are critical. This limitation becomes particularly apparent for users transitioning from Restraint, where such dynamic configuration capabilities are often needed.

The proposed enhancement would address these limitations by allowing dynamic environment configurations within the discover step.

## Impact

Implementing this feature will:

 - Simplify the management of dynamic test plans.
  - Allow more flexible and automated testing scenarios across different environments.
  - Facilitate migration from Restraint by providing similar functionality.
  - Reduce redundancy in test configurations and streamline the testing process.

## Request for Feedback

Has anyone else encountered similar needs, especially during migration from Restraint? If so, please share your use cases or any workarounds you've implemented. Additionally, if there are existing issues related to this in the TMT repo, please reference them here.
