### ISSUE TITLE
[FR] specify `ref` as "a branch I am on"

### ISSUE THREAD

**Issue by befeleme** [teemtee/tmt#3232]
I want to run tmt tests on a component python-sphinx-theme-alabaster for c10s branch of the centos stream dist git repository.
The tests are stored in another component - python-sphinx. I can use `url:` in the `discover` step to pull them. This doesn't work yet, because the default branch is used (in my case: c9s). 
I want to set the branch to the correct one. I can use `ref:` for that and specify the value to `c10s`. That works.
When c11s is created, I will have to manually change all the files. When I want to run the tests in different Fedoras, I'll have to manually specify the branches. I would like to have it possible to define `ref` as "a value of the branch I am currently on", so if I open a PR to `c10s`, tmt will look for the corresponding value in a remote repository.

The [docs](https://tmt.readthedocs.io/en/stable/spec/plans.html#fmf) say:
```
Additionally, one can set ref dynamically. This is possible using a special file in tmt format stored in the default branch of a tests repository.
This special file should contain rules assigning attribute ref in an adjust block, for example depending on a test run context.
```
The thing is, I don't really want to rely on the "default" branch, because that one can be switched to a different one in time.

Does there exist a solution for this? Would you be willing to add one?

**Comment by hroncok** [comment]
Note that Fedora and CentOS have different dist-git URLs, so this won't allow us to fork the tests from Fedora without adjustments, but at least the tests would fail (searching for c10s in Fedora distgit) instead of running something bad.

Ideally, if this is solved, the next step would be to be able to set `url` to something like `{distgit pkgname}`.

**Comment by tcornell-bus** [comment]
Currently to get that behavior to happen, you'd need to do one of these:
1. dynamic-ref solution ([docs](https://tmt.readthedocs.io/en/stable/examples.html#dynamic-ref)), which you already stated does not work for your use case
2. context variables 
```
summary: Basic smoke test
discover:
  - name: python-sphinx-theme-alabaster tests
    how: fmf
    url: https://url/to/python-sphinx
    ref: $@{current_branch}
execute:
  how: tmt
```
then in the command:
```
tmt -c current_branch=$(git branch --show-current) run discover
```
Which I do not think you can make happen with CI...?

---

I cannot think of a way to get the desired behavior with tmt version 1.75.0. 
This is what I think you are looking for (or something similar):
```
summary: Basic smoke test
discover:
  - name: python-sphinx-theme-alabaster tests
    how: fmf
    url: https://url/to/python-sphinx
    current-ref: true
execute:
  how: tmt
```

Then when CI goes to run on an MR against the `c11s` branch it would discover something like:
```
    discover
        url: https://url/to/python-sphinx
        cloned-commit-hash: blah
        ref: c11s
        how: fmf
        name: python-sphinx-theme-alabaster tests
        summary: 1 test selected
```
Does that look correct @befeleme ?

**Comment by befeleme** [comment]
> I cannot think of a way to get the desired behavior with tmt version 1.75.0. This is what I think you are looking for (or something similar):
> 
> ```
> summary: Basic smoke test
> discover:
>   - name: python-sphinx-theme-alabaster tests
>     how: fmf
>     url: https://url/to/python-sphinx
>     current-ref: true
> execute:
>   how: tmt
> ```
> 
> Then when CI goes to run on an MR against the `c11s` branch it would discover something like:
> 
> ```
>     discover
>         url: https://url/to/python-sphinx
>         cloned-commit-hash: blah
>         ref: c11s
>         how: fmf
>         name: python-sphinx-theme-alabaster tests
>         summary: 1 test selected
> ```
> 
> Does that look correct [@befeleme](https://github.com/befeleme) ?

Yes, your rephrasing of the issue is correct.

**Comment by tcornell-bus** [comment]
Seems like `tmt/utils/git.py:GitInfo.from_fmf_root()` could be helpful here.

**Comment by LecrisUT** [comment]
To add to the context, packit provides the ref via context [`dist-git-branch` on Fedora-CI](https://packit.dev/fedora-ci/tmt-integration) which exports the target branch. For source ref, it does not export anything like that, but that can be exposed. @befeleme would @tcornell-bus first suggestion with something like
```yaml
summary: Basic smoke test
discover:
  - name: python-sphinx-theme-alabaster tests
    how: fmf
    url: https://url/to/python-sphinx
    ref: $@{dist-git-branch}
execute:
  how: tmt
```
work instead?
