### ISSUE TITLE
or/and will override other hardware constraints in Beaker job XML

### ISSUE THREAD

**Issue by skycastlelily** [teemtee/tmt#3273]
Here is the hardware part of  a reproducer plan file:
```
    hardware:
        disk:
            - size: "> 32 GiB"
            - size: "> 16 GiB"
        memory: "> 6 GiB"
        or:
          - cpu:
               model: 65
          - cpu:
               model: 67
```
ie, a server with two disks, memory> 6GiB, cpu model is 65 or 67
And here is the hostRequires part of the beaker job xml

```
      <hostRequires>
        <and>
          <cpu>
            <model op="==" value="65"/>
          </cpu>
        </and>
        <system_type value="Machine"/>
      </hostRequires>
```
disk.size and memory requires are abandoned somehow
