### ISSUE TITLE
Plan environment file is not being sourced after `prepare` and `execute` in `tmt-try`

### ISSUE THREAD

**Issue by xduda** [teemtee/tmt#3315]
The documentation states file located at `TMT_PLAN_ENVIRONMENT_FILE`  should be sourced after steps `prepare` and `execute`. 
When running from `tmt try`, this doesn't happen.

Steps to reproduce:

/plan:
```
provision:
    how: local
discover:
    how: fmf
prepare:
    how: shell
    script: echo "VAR=hello" >> $TMT_PLAN_ENVIRONMENT_FILE
execute:
    how: tmt
```

/test:
```
framework: shell
test: test "${VAR}" = "hello"
```

the plan succeeds when running `tmt run plans -n plan`,
but fails when running as `tmt try -p plan`
