### ISSUE TITLE
Unable to skip `prepare` step - "Unrecognized package manager."

### ISSUE THREAD

**Issue by abitrolly** [teemtee/tmt#3405]
The following test/plan script fails with "Unrecognized package manager." error, but according to the script, the package manager should not run.

```yaml
summary: Test nix installer
provision:
    how: container
    image: archlinux
prepare:
    how: shell
    script: echo prepare
execute:
    how: tmt
    script: echo hello
```

The output of `tmt run`.
```shell
/var/tmp/tmt/run-012

/tmt_testing_plan
    discover
        how: shell
        summary: 1 test selected
    provision
        queued provision.provision task #1: default-0
        
        provision.provision task #1: default-0
        how: container
        image: archlinux
        multihost name: default-0
        arch: unknown
        distro: Arch Linux
    
        summary: 1 guest provisioned
    prepare
        queued push task #1: push to default-0
        
        push task #1: push to default-0
    
        queued prepare task #1: essential-requires on default-0
        queued prepare task #2: default-0 on default-0
        
        prepare task #1: essential-requires on default-0
        how: install
        summary: Install essential required packages
        name: essential-requires
        where: default-0
        fail: Unrecognized package manager.
    finish
    
        container: stopped
        container: removed
        container: network removed
        summary: 0 tasks completed

plan failed

The exception was caused by 1 earlier exceptions

Cause number 1:

    prepare step failed

    The exception was caused by 1 earlier exceptions

    Cause number 1:

        Unrecognized package manager.
```
