### ISSUE TITLE
User defined system configuration

### ISSUE THREAD

**Issue by bmeneg** [teemtee/tmt#3447]
This issue is a "re-open" of the issue #1601 that I closed by mistake.

When testing something like the kernel or even userspace with hardware dependent features, it's a good thing to define a set of system configurations with a single name, for instance: 

```
AMD__ROME:
CPU family=23
CPU model=49

MEMORY_MIN_64G
SYSTEM memory >= 64G

NOGSS:
SYSTEM name != "%gss%"
```
The first line would be the `host-filter` name, while the other lines would then be the actual system configuration requirements.
Some of these might make sense to all runners, but when using Beaker for bare-metal reservation and testing this feature is really important and a must, even more the idea of accepting some "regular expressions" for generalization.

On Beaker, all host-filters were just XML's tags dropped on the final recipe XML in the system requirements section, but on TMT/FMF it could follow another format for sure..

**Comment by psss** [comment]
If I understand it correctly, the `AMD__ROME` in the example above would be basically a nick name or alias for a group of settings. Is that right? I remember @kkaarreell recently mentioned a possibly similar use case where he wants to share some common setup across multiple plans. @bmeneg, where do you expect these groups of settings to be stored? In a user config directory? Or do you expect them to be shared across the team/repositories?

**Comment by bmeneg** [comment]
@psss yes, they're mostly aliases that contain hw settings, including possible hostnames. Also it's a common practice to have it somewhere public so it can be shared between teams using the same specification aliases (pretty common among kernel developers and QE for instance, that handle different subsystems). So having a way to specify both a local path *and* and URL to the host-filter file and the actual filter/alias I want from that file would be the best solution. 

Maybe something like the following:

```yaml
filters:
  - name: AMD__ROME
    hardware:
      cpu:
        family: 23
        model: 49
  - name: MEMORY_MIN_64G
    hardware:
      memory: ">= 64 GB"
```
The above would be the content of hostfilters file, which would have to follow the already known TMT hardware specification, but add the `filters` list.
```yaml
provision:
  hostfilter: 
    url: https://github.com/my-team/project/hostfilters.yml
    # path: /home/bmeneg/.hostfilters.yml
  hardware:
    filter: AMD__ROME
``` 
While on the provision stage of the plan there would be necessary to add the `hostfilter` keyword with the `url` to fetch the filters file, or the `path` for a local path under my system, and the `filter` under hardware to point to the actual filter present in the hostfilter file.
