### ISSUE TITLE
A caching layer for git checkouts

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#3482]
Based on https://issues.redhat.com/browse/TFT-2461:

```
discover:
  - name: first
    how: fmf
    url: http://github.com/kernel/big-pile-of-tests
    test:
      - networking/ipv6/misc/checksum
  - name: second
    how: fmf
    url: http://github.com/kernel/big-pile-of-tests
    test:
      - networking/ipv6/misc/checksum
```

is supported, but will consume a lot of resources - network traffic, disk space, time, etc. - by cloning a very large repository twice.

As discussed in the tmt hacking meeting, this is a complex subject. tmt lacks a caching layer for git repos, and the general mood was it should get one. `git clone` would then be able to save some space and network by re-using already cloned data for read-only access.

* Could we do some kind of caching?
  * Only the git metadata?
  * We could share the cached copy for the whole tmt run instance
  * There is some proof-of-concept already used in workflow-tomorrow
* What about handling different refs?
  * We could track cache per url-ref combination
* What is the essential problem?
  * Disk space or network connection bandwidth?
  * Seems the disk space is the more pressing one (for the kernel team)
  * Would be good to track disk/network issue separately
* Development branch means that the whole history is currently fetched
