### ISSUE TITLE
Execute tries to run tests from 'turned off' discover config

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#3492]
When there is a discover config turned off by using `when` key, `execute` still tries to run tests defined in that config and fails as no such test exists according to the discover. 

Thanks to @happz for initial investigation and finding likely cause at https://github.com/teemtee/tmt/blob/384bb5682984c5f4ae54e25fb62a6abfc04403a3/tmt/steps/execute/__init__.py#L1173 

Reproducer plan:
```
execute:
  how: tmt

provision:
  how: container

discover:
    - how: shell
      tests:
      - name: nope
        test: echo
      when: flag == on
    - how: shell
      tests:
      - name: yes
        test: echo
      when: flag is not defined
```
