### ISSUE TITLE
Discover does not update test attributes after pruning with `path` specified

### ISSUE THREAD

**Issue by therazix** [teemtee/tmt#3589]
When pruning a repository with a specified `path`, the discover step does not update certain test attributes after the pruned directory is moved from the temporary cloning directory to the test directory. As a result, attributes like `test.path` and `test.fmf_id` still reference the original structure.

How to reproduce:
Run the following plan:
```
discover:
    how: fmf
    url: https://github.com/teemtee/tests
    path: nested
    prune: true
provision:
    how: local
execute:
    how: tmt
```
Error:
`Discover[Errno 2] No such file or directory: '/var/tmp/tmt/run-001/nested/discover/default-0/tests/nested/file/...'`

The correct path is:
`/var/tmp/tmt/run-001/nested/discover/default-0/tests/file/...`

Also, the `fmf_id` of the discovered test has `fmf_root` incorrectly set to: `/var/tmp/tmt/run-001/nested/discover/default-0/tests/nested` instead of `/var/tmp/tmt/run-001/nested/discover/default-0/tests`. This will cause an exception when attempting to access the test's `fmf_id`.
