### ISSUE TITLE
test checks configured with context are not preserved if a test uses adjust

### ISSUE THREAD

**Issue by bgoncalv** [teemtee/tmt#3610]
example:

in the root of the repo we have:

```
check:                                                                          
  - how: avc                                                                    
  - how: dmesg                                                                  
    failure-pattern:                                                            
      # These are default patterns                                              
      - 'Call Trace:'                                                           
  - how: watchdog                                                               
adjust:                                                                         
  - when: check-result == info                                                  
    check:                                                                      
      - how: avc                                                                
        result: info                                                            
      - how: dmesg                                                              
        result: info                                                            
        failure-pattern:                                                        
          # These are default patterns                                          
          - 'Call Trace:'                                                       
      - how: watchdog                                                           
        result: info                                                            
  - when: check-result == disabled                                              
    check:                                                                      
      - how: avc                                                                
        enabled: false                                                          
      - how: dmesg                                                              
        enabled: false                                                          
      - how: watchdog                                                           
        enabled: false 
```

a test contains the following adjust rules:
```
adjust:                                                                         
    # numactl is not available for s390x/rhel7                                  
    - when: distro == rhel-7 and arch == s390x                                  
      enabled: false                  
```
running tmt with `-c check-result=info` I 'd expect the test to show the check with `result: info` for this test as:

```
                   check - how: avc
                           enabled: true
                           result: info
                         - how: dmesg
                           enabled: true
                           result: info
                           failure-pattern: Call Trace:
                         - how: watchdog
                           enabled: true
                           result: info
```

but the result is the default check, with `result: respect`:
```
                   check - how: avc
                           enabled: true
                           result: respect
                         - how: dmesg
                           enabled: true
                           result: respect
                           failure-pattern: Call Trace:
                         - how: watchdog
                           enabled: true
                           result: respect
```

note: if I remove the adjust rules the check behaves like expected...
