### ISSUE TITLE
Allow test checks for the `shell` discover step

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#3620]
Checks have no effect, for example:

```
discover:
    how: shell
    tests:
    - test: echo
      name: /
      check:
      - how: avc
```
