### ISSUE TITLE
tmt lint does not inspect keys in `adjust` for validity

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#3625]
```yaml
adjust:
  - when: ...
    enable: true
```

The correct key is `enabled`, this is a clear typo, and it is not reported by tmt lint.
