### ISSUE TITLE
Plans with both `execute` and `plan.import` are accepted, causing duplication

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#3652]
```yaml
execute:
    how: tmt

/binutils:
    /common:
        plan:
            import:
                url: ...
                ref: main
                name: /plans/build-gating/common

    /kernel-rebuild:
        plan:
            import:
                url: ...
                ref: main
                name: /plans/build-gating/kernel-rebuild
```

tmt will accept this fmf input, duplicating `/binutils/common` and `/binutils/kernel-rebuild`: one instance will come from being "local" plans, aka having `execute` key, the second instance because of being "remote reference" aka having `plan.import` keys. tmt should at least emit a warning for this, if not even reject it.
