### ISSUE TITLE
tmt plan export missing context values

### ISSUE THREAD

**Issue by jencce** [teemtee/tmt#3657]
TMT context values are not exported via `tmt plan export`.

This is problematic because testing-farm is using `tmt plan export` to get the plan for running.

Now testing-farm users' context values are lost within the process, not making to the final running plan.

By the way, `tmt plan show` can get the context values.

```
# git log --oneline -1
434cbe1e (HEAD -> main, origin/main, origin/HEAD) Drop unused parameter in the `coredump` test check (#3656)

# tmt -c arch=aarch64 plan show /plans/sanity/lint
/plans/sanity/lint
                 summary Metadata used by tmt itself are valid
                discover 
                   tests '/lint/tests' and '/lint/plans'
                 prepare 
                     how install
                 missing fail
                   where 
                 package 'jq', 'make' and 'python3-pip'
               directory 
                 exclude 
                    when 
                    copr 
                 prepare 
                     how shell
                   where 
                    when 
                  script pip3 install --user yq || pip3 install yq
                         yq --help
                 context arch: aarch64
                 enabled true

# tmt -c arch=aarch64 plan export /plans/sanity/lint 
  - name: /plans/sanity/lint
    summary: Metadata used by tmt itself are valid
    description:
    author: []
    contact: []
    enabled: true
    order: 50
    link: []
    id:
    tag: []
    tier:
    context: {}
    gate: []
    login:
    sources:
      - /root/upstream/tmt/plans/main.fmf
      - /root/upstream/tmt/plans/sanity/lint.fmf
    discover:
      - how: shell
        tests:
          - name: /lint/tests
            test: tmt tests lint
          - name: /lint/plans
            test: tmt plans lint
        name: default-0
    provision:
      - how: local
        name: default-0
    prepare:
      - how: install
        package:
          - jq
          - make
          - python3-pip
        name: default-0
      - how: shell
        script:
          - pip3 install --user yq || pip3 install yq
          - yq --help
        name: default-1
    execute:
      - how: tmt
        name: default-0
    report:
      - name: default-0
        how: display
    finish:
      - name: default-0
        how: shell

# tmt -c arch=aarch64 plan export /plans/sanity/lint | grep aarch64

```
