### ISSUE TITLE
adjust rules working with context defined within a plan

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#3668]
Currently, `adjust` rules work only with context which is given `tmt` from the outslide (cmdline).
However, it might be handy to reflect also context definition from the plan itself.
Of course, it would require processing plan attributes in a given order, first `context` and later`adjust`.

Use case:
Let's have a "configuration" in `main.fmf` that does test plan adjustments according to "switches" represented by context dimensions.

```
adjust:
  - when: do_something == yes
    discover+:
       - name: something
         ...

  - when: do_otherthing == yes
    discover+:
       - name: otherthing
         ...
```

Today, I need to run the plan as `tmt -c do_something=yes -c do_otherthing=no ...` but if I would be able to utilize context from the plan itself, I could have a plan that does particular settings (for a particular test scenario) or define a default.

```
name: child plan that does something but not other thing
context:
  do_something: yes
  do_otherthing: now
...
```
