### ISSUE TITLE
Unable to access an internal gitlab instance

### ISSUE THREAD

**Issue by fujiwarat** [teemtee/tmt#3684]
I run the following test case:
```
% cat tests/ibus-desktop-testing/install4-g-d-t/main.fmf
summary: Foo
description:
    foo.
require:
    - git
    - type: library
      url: https://gitlab.com/red123/123456-stream/12345/gnome-desktop-testing.git
```

I run `tmt` but failed.
```
% cd tests
% tmt run
/var/tmp/tmt/run-001

/plans/test
    discover
        how: fmf
        directory: /var/ARTIFACTS/git-456d1ecef124aa0932df0b82f8c2d62fa7f350081o_n42n1
        fail: Command 'git clone https://gitlab.com/red123/123456-stream/12345/gnome-desktop-testin /var/tmp/tmt/run-001/plans/test/discover/default-0/tmp4rgaly_h/gitlab.com/gnome-desktop-testin' returned 128.
        fail: Failed to fetch library 'gnome-desktop-testin/' from 'https://gitlab.com/red123/123456-stream/12345/gnome-desktop-testin'.

plan failed

The exception was caused by 1 earlier exceptions

        # stderr (3/3 lines)
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Cloning into '/var/tmp/tmt/run-001/plans/test/discover/default-0/tmp4rgaly_h/gitlab.com/gnome-desktop-testin'...
        remote: The project you were looking for could not be found or you don't have permission to view it.
        fatal: repository 'https://gitlab.com/red123/123456-stream/12345/gnome-desktop-testin.git/' not found
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
