### ISSUE TITLE
the disk.size can not transform to beaker xml

### ISSUE THREAD

**Issue by guazhang** [teemtee/tmt#3698]
tmt -c compose=RHEL-10.1-20250425.3  run -f --all -dv   provision -h beaker --hardware 'beaker.pool !=storage-qe' --hardware 'cpu.flag =avx2' --hardware 'disk[0].size >= 100 GiB' --hardware 'disk[1].size >= 200 GiB' --hardware 'memory >= 4 GB'

```
        Transformed hardware:
            and:
              - pool:
                    _op: '!='
                    _value: storage-qe
              - and:
                  - cpu:
                        flag:
                            _op: ==
                            _value: avx2
              - system:
                    memory:
                        _op: '>='
                        _value: '3814'
              - and:
                  - disk:
                        size:
                            _op: '>='
                            _value: '107374182400'
                  - disk:
                        size:
                            _op: '>='
                            _value: '214748364800'
        whiteboard: tmt-o4U-eGdJDqOf
        guest: has been requested
        job id: J:10995978

```

```

      <hostRequires>
        <and>
          <and>
            <pool op="!=" value="storage-qe"/>
            <and/>
            <system>
              <memory op="&gt;=" value="3814"/>
            </system>
            <and/>
          </and>
        </and>
        <system_type value="Machine"/>
      </hostRequires>

```

looks the beaker xml hostRequires don't include disk.size and cpu.flag

 
tmt+all-1.46.0-1.fc40.noarch
