### ISSUE TITLE
tmt expects scripts to be executable

### ISSUE THREAD

**Issue by hadess** [teemtee/tmt#3704]
In `tests/tests.fmf`:
```
summary: Check basic command line options
discover:
    how: shell
execute:
    script: tests/run_tests.sh
```

`tests/run_tests.sh` exists as a `0644` file, but tmt complains about not being able to execute it.

The script being executable a requirement in STI, and it probably shouldn't be one in tmt, as one would expect `scripts` to be executed by a shell.

At the very least, the migration documentation should mention this:
https://tmt.readthedocs.io/en/stable/questions.html#how-do-i-migrate-sti-tests-to-tmt
