### ISSUE TITLE
tmt context not honored when defined in fmf plan

### ISSUE THREAD

**Issue by stowellm** [teemtee/tmt#3758]
## Description

A custom tmt `context:` is not honored when placed directly into an fmf plan.  It will only be honored when put into a `--context` command-line argument.

## Reproducer

Create two files:

`main.fmf`:

```
summary: context-dependent provisioning filters

adjust:
  - when: hosts == 2
    provision:
      - name: server
        how: artemis
        arch: x86_64
        pool: beaker
      - name: client
        how: artemis
        arch: x86_64
        pool: beaker
  - when: hosts == 1
    provision:
      - name: standalone
        how: artemis
        arch: x86_64
        pool: beaker
 ```

`example/main.fmf`:

```
summary: example test using context

context:
  hosts: "2"

discover:
  - name: Example test
    how: fmf
    filter: tier:1
    where:
      - server
      - client

execute:
  how: tmt
```

Show the plan without specifying context (I have these under directory 'plans/rdma/reproduce/')

```
~$ tmt plans show reproduce/example
/plans/rdma/reproduce/example
                 summary example test using context
                discover
                    name Example test
                     how fmf
                 exclude
  dist-git-download-only false
                    when
dist-git-install-builddeps false
               sync-repo false
                   prune false
                   where 'server' and 'client'
                    test
                  fmf-id false
dist-git-remove-fmf-root false
        dist-git-require
            adjust-tests
           modified-only false
                    link
          dist-git-merge false
         dist-git-source false
                  filter tier:1
           dist-git-init false
                 context hosts: 2
                 enabled true
```

Show the plan with `--context` flag added:

```
~$ tmt --context "hosts=2" plans show reproduce/example
/plans/rdma/reproduce/example  
                 summary example test using context
                discover 
                    name Example test
                     how fmf   
                  fmf-id false 
                    when      
dist-git-remove-fmf-root false 
            adjust-tests        
               sync-repo false  
           dist-git-init false
                   prune false                
                    link  
         dist-git-source false           
           modified-only false
          dist-git-merge false
                    test                      
                 exclude      
                   where 'server' and 'client'
        dist-git-require      
                  filter tier:1
dist-git-install-builddeps false
  dist-git-download-only false
               provision         
                    name server
                     how artemis
                 api-url http://127.0.0.1:8001
                    when                                     
             api-timeout 10                                                                                           
               kickstart {}      
                  become false
             api-version 0.0.74
              ssh-option 
       provision-timeout 600                                 
                log-type                                                                                             
          priority-group default-priority
 skip-prepare-verify-ssh false
                    pool beaker
             api-retries 10
          provision-tick 60
                    user root
                     key 
api-retry-backoff-factor 1
                    arch x86_64
               user-data {}
                 keyname default
               provision 
                    name client
                     how artemis
                 api-url http://127.0.0.1:8001
                    when 
             api-timeout 10
               kickstart {}
                  become false
             api-version 0.0.74
              ssh-option 
       provision-timeout 600
                log-type 
          priority-group default-priority
 skip-prepare-verify-ssh false
                    pool beaker
             api-retries 10
          provision-tick 60
                    user root
                     key 
api-retry-backoff-factor 1
                    arch x86_64
               user-data {}
                 keyname default
                 context hosts: 2
                 enabled true
```

## Current Output

When you do not specify `--context "hosts=2"` in the command, the context-dependent adjustments in `main.fmf` ('provision') do not show.

However by adding `--context "hosts=2" to the command, the 'provision' stage shows.

## Expected Output

Since `example/main.fmf` already has `context: hosts: "2"`, a user should not have to additionally specify `--context` flag in the command; the 'provision' stage from `main.fmf` should always be present.
