### ISSUE TITLE
Apply importing plan's context and variables to an imported plan

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/tmt#3774]
When importing a test plan, it would be very handy if one could adjust `context` of  the imported plan from the importing plan.
E.g.
```
/plan:
  context:
   foo: bar
  plan:
    import:
      url: https://path/to/repo.git
      name: /plans/myplan
```
would cause the `foo=bar` is a defined `context` for `/plans/myplan`. Such a context should be applied both during the discover and execution of the plan but also during dynamic ref evaluation.

The same thing can be applied to environment variables

Since making it a default could have unpredictable consequences for existing plans, we could control it through an option.
E.g.
```
/plan:
  context:
   foo: bar
  plan:
    import:
      url: https://path/to/repo.git
      name: /plans/myplan
      inherit_context: True
      inherit_environment: True
```
