### ISSUE TITLE
`test` in `discover -h fmf` ignored `order` in test metadata

### ISSUE THREAD

**Issue by smyle10** [teemtee/tmt#3782]
tests:
```
/testa:
  test: echo aaaa
  order: 10
/testb:
  test: echo bbbb
  order: 20
```
plan:
```
discover:
    how: fmf
    test:
        - testb
        - testa
```

`tmt run` will run testb (order=20) first, then testa (order=10).

A new tmt user may get confused since this is an implicit mechanism, isn't documented explicitly.

The above example is simple, [in this slack thread](https://redhat-internal.slack.com/archives/C04LRPNDZ4Y/p1748500672607489) there is a more human natural example why it is confusing and discussion.
