### ISSUE TITLE
Emit a better warning message when a particular hardware contraint is not supported

### ISSUE THREAD

**Issue by tcornell-bus** [teemtee/tmt#3812]
Issue originates from this [discussion](https://github.com/teemtee/tmt/pull/3810/files#r2143466602). 
Take this hardware requirement as an example:
```
        hardware:
            or:
              - memory: '>= 4 GB'
              - memory: < 4 GB
```
Currently a warning like this `warn: Hardware requirement 'memory' is not supported.` is emitted, but the first requirement `memory: '>= 4 GB'` is still honored, it is actually warning about no support for the `<` operator in `memory: < 4 GB`. The warning could be made more clear to the user. Something like this `warn: Hardware requirement 'memory: < 4 GB' is not supported.` instead would suffice.
