### ISSUE TITLE
No error is thrown on missing cructial FMF entry

### ISSUE THREAD

**Issue by pvalena** [teemtee/tmt#447]
If I have this in my plan:
```

prepare:
    - name: Dependencies
      how: install
      copr: pvalena/bughunting
      packages: bughunting bughunting-tasks bughunting-server
      order: 20

    - name: Build tasks
      how: shell
      script: /usr/share/bughunting/scripts/build_tasks.sh .
      order: 80
```

~~The order is always ignored, no matter what value I set.~~ Or am I writing it wrong? (Syntax copied from documentation.)
