### ISSUE TITLE
Install plugin fails on empty value

### ISSUE THREAD

**Issue by pvalena** [teemtee/tmt#454]
```console
$ tmt run -a plan --name '/ci-testing$' provision -h container report -vvv
[ . . . ]
    prepare
        how: install
        name: Install Dependencies
        copr: pvalena/bughunting
        package: bughunting, bughunting-client, bughunting-server and 5 more
[ . . . ]
stdout (7/7 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Last metadata expiration check: 0:00:47 ago on Tue Nov 24 21:49:50 2020.
No match for argument: bughunting
No match for argument: bughunting-client
No match for argument: bughunting-server
No match for argument:
Copr repo for bughunting owned by pvalena       6.2 kB/s | 6.9 kB     00:01
No match for argument:

stderr (5/5 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: Cache-only enabled but no cache for 'copr:copr.fedorainfracloud.org:pvalena:bughunting'
Ignoring repositories: copr:copr.fedorainfracloud.org:pvalena:bughunting
Error: Unable to find a match: bughunting bughunting-client bughunting-server
Error: Unable to find a match
Error: exec session exited with non-zero exit code 1: OCI runtime error

Failed to run command 'podman exec tmt-var-tmp-tmt-run-088-ci-testing sh -c dnf --cacheonly install -y "bughunting" "bughunting-client" "bughunting-server" "perl-YAML-Syck" "git" "rpm-build" "procps-ng" "" || dnf install -y "bughunting" "bughunting-client" "bughunting-server" "perl-YAML-Syck" "git" "rpm-build" "procps-ng" ""'.
```

Notice the last `""` - empty arg / value.

The error came from parsing the following in my plan:
```yaml

prepare:
    - name: Install Dependencies
      how: install
      copr: pvalena/bughunting
      package: |
               bughunting bughunting-client bughunting-server
               perl-YAML-Syck git rpm-build procps-ng

    - name: Build tasks
      how: shell
      script: /usr/share/bughunting/scripts/build_tasks.sh ../../../discover/default/tests/

```
Only thing that helped was changing `package:` from multiline into single-line:
```
      package: bughunting bughunting-client bughunting-server perl-YAML-Syck git rpm-build procps-ng
```
_ _ _ _

FYI, from, the same plan, with non-printable symbols:
```
······copr:·pvalena/bughunting
······package:·|
···············bughunting·bughunting-client·bughunting-server
···············perl-YAML-Syck·git·rpm-build·procps-ng

····-·name:·Build·tasks
······how:·shell
```
