### ISSUE TITLE
allow to specify packages what are not satisfied by current repos

### ISSUE THREAD

**Issue by jscotka** [teemtee/tmt#685]
Story is based on `require` attribute of L1 metadata.
When using more distros, especially fedora and RHEL with same tests. It happened, that in RHEL there are some packages missing of contains older version that tests expects.

there is more solution how to solve this: 
 - Allow also pip installation (but specific to python, and what others, perl CPAN, nodeJS NPM so probably harder)
 - Allow to use some `script:` what allows to solve more complex deps by own script - more less elegant, just not able to optimise
 - Allow to enable custom COPR/EPELs repo inside L1 or maybe in L2 metadata, before package installation **(probably best solution)**

Currently it is possible to use `ajust` with adjusting prepare steps with `order` attribute to enable COPR or upgrade package via PIP after package installation.
But this solution is little bit tricky and not so straightforward, and at least needs to know how to work with it properly.
I can imagine solution like `plan`:
```
summary: Session recording testcases
discover:
  how: fmf
  filter: tier:2
execute:
  how: tmt
prepare:
    - how: repository
      #default_order: 10
      name: name1
      url: url://url1/like/epel
   - how: repository
      #default_order: 10
      name: name2
      url: url_to_copr_jscotka/requre
```
maybe there could be some shotcuts, e.g. key `epel: True` means enable epel for prorep release if there is some (ignore for fedora) or for copr it could be: `copr: jscotka/requre`

Question is about conditions, because these repositories are more less important  mainly for older distros or RHEL, and `adjust` is possible but why :-)
