### ISSUE TITLE
tmt should detect default context from the environment

### ISSUE THREAD

**Issue by stepnem** [teemtee/tmt#771]
Reproducer:
```shell
#!/bin/sh

set -e

tmt --version

cat /etc/fedora-release

testdir="$(mktemp -d)"
oldpwd="$(pwd)"

cd "$testdir"
tmt init
tmt test create -t shell adjust-test
cat <<EOF >>./adjust-test/main.fmf
adjust:
    enabled: false
    when: distro == fedora-33
EOF

tmt run -avvv provision -h local

cd "$oldpwd"
rm -rf "$testdir"
tmt clean runs -lv
```

This runs the test, even on Fedora 33, where I would expect (after having read [the documentation](https://tmt.readthedocs.io/en/latest/spec/core.html?highlight=adjust#adjust) repeatedly) the test to be skipped, same as when `enabled: false` is specified as a top level attribute in the same `main.fmf`.

Otherwise I don't understand the purpose of `adjust` used in L1 metadata [1], or the meaning of examples in the documentation (linked above) such as the following:

```yaml
# Disable a test for older distros
enabled: true
adjust:
    enabled: false
    when: distro < fedora-33
    because: the feature was added in Fedora 33
```

[1] `adjust` is [documented](https://tmt.readthedocs.io/en/latest/spec.html#metadata-specification) as L0 / core metadata, "which are common and can be used across all metadata levels".
