### ISSUE TITLE
Provision plugin for the Resource Hub

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#848]
Let's outline how the possible future integration with the Resource Hub could look like. The project is at an early stage of development with just a basic functionality implemented. Relevant git repositories:

 * https://github.com/resource-hub-dev/rhub-app
 * https://github.com/resource-hub-dev/rhub-api

It would help to provide a small but clear and tangible user story touching a couple of essential features needed from the `tmt` point of view. For the brainstorming of the `provision` step config let's start with something very simple:

```yaml
provision:
    how: resourcehub
    image: fedora-33
    hardware:
        memory: 8 GB
        cpu:
            processors: 2
        disk:
            space: 500 GB
```

The Resource Hub API should provide a way to specify [hardware](https://tmt.readthedocs.io/en/latest/spec/plans.html#hardware) requirements as outlined above and provision a guest satisfying all of them.
