### ISSUE TITLE
Fragmented execute -vvv output (output.txt is correct though)

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#849]
I'm not sure why but `execute -vvv` out for following test's out is fragmented. Content of `/var/tmp/tmt/run-058/plans/execute/data/repro/output.txt` is correct. 
```
require:
- javapackages-bootstrap
test: $(rpm -ql javapackages-bootstrap | grep /xmvn$) --version
```

`tmt run execute -vvv` shows: 
```
test: /smoke
                out: Warning: Permanently added '[127.0.0.1]:10025' (ED25519) to the list of known hosts.
                out: 
out: [1m
                out: Re
                out: d 
                out: Ha
                out: t XM
                out: vn
....
```
However `plans/execute/data/repro/output.txt` contains expected content (`cat -A`)
```Warning: Permanently added '[127.0.0.1]:10025' (ED25519) to the list of known hosts.^M$
^[[1mRed Hat XMvn 3.6.3 (3.6.3)^[[m$
XMvn home: /usr/share/javapackages-bootstrap$
Java version: 11.0.11, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-5.fc34.x86_64$
Default locale: en_US, platform encoding: UTF-8$
OS name: "linux", version: "5.11.12-300.fc34.x86_64", arch: "amd64", family: "unix"$
```
